// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from ARKit.framework (session.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.ARKit;

import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "ARKit")

public objc interface OS_ar_device : NSObjectProtocol { }

/// macOS 26.0 and later.
public using ar_device_t = NSObject;

public objc interface OS_ar_session : NSObjectProtocol { }

/// macOS 26.0 and later.
public using ar_session_t = NSObject;

/// macOS 26.0 and later.
public extern "C" ar_session_t ar_session_create_with_device(ar_device_t device);

/// macOS 26.0 and later.
public enum ar_session_error_code_t : long
{
    not_authorized = 100,
    failed_to_run = 101,
}

/// macOS 26.0 and later.
public objc closure void ar_session_data_provider_state_change_handler_t(ar_data_providers_t arg0, ar_data_provider_state_t arg1, ar_error_t? arg2, ar_data_provider_t? arg3);

/// macOS 26.0 and later.
public extern "C" void ar_session_set_data_provider_state_change_handler(ar_session_t session, dispatch_queue_t? queue, ar_session_data_provider_state_change_handler_t? data_provider_state_change_handler);

/// macOS 26.0 and later.
public delegate void ar_session_data_provider_state_change_handler_function_t(void* arg0, void* arg1, ar_data_provider_state_t arg2, void* arg3, void* arg4);

/// macOS 26.0 and later.
public extern "C" void ar_session_set_data_provider_state_change_handler_f(ar_session_t session, dispatch_queue_t? queue, void* context, ar_session_data_provider_state_change_handler_function_t data_provider_state_change_handler_function);

/// macOS 26.0 and later.
public extern "C" void ar_session_run(ar_session_t session, ar_data_providers_t data_providers);

/// macOS 26.0 and later.
public extern "C" void ar_session_stop(ar_session_t session);

/// macOS 26.0 and later.
public extern "C" ar_data_providers_t ar_session_copy_data_providers(ar_session_t session);

/// macOS 26.0 and later.
public objc closure void ar_authorization_update_handler_t(ar_authorization_result_t arg0);

/// macOS 26.0 and later.
public delegate void ar_authorization_update_handler_function_t(void* arg0, void* arg1);

/// macOS 26.0 and later.
public objc closure void ar_authorization_results_handler_t(ar_authorization_results_t arg0, ar_error_t? arg1);

/// macOS 26.0 and later.
public delegate void ar_authorization_results_handler_function_t(void* arg0, void* arg1, void* arg2);

#endif
