// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from NetworkExtension.framework (NEFilterProvider.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.NetworkExtension;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "NetworkExtension")

public objc closure void NEFilterProviderStartFilterWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void NEFilterProviderStopFilterWithReasonCompletionHandlerCompletionHandlerBlock();

public extern objc class NEFilterProvider : NEProvider
{
    [Selector("filterConfiguration")] public NEFilterProviderConfiguration FilterConfiguration { get; }
    [Selector("startFilterWithCompletionHandler:")] public void StartFilterWithCompletionHandler(NEFilterProviderStartFilterWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("stopFilterWithReason:completionHandler:")] public void StopFilterWithReasonCompletionHandler(NEProviderStopReason reason, NEFilterProviderStopFilterWithReasonCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("handleReport:")] public void HandleReport(NEFilterReport report);
}

public enum NEFilterReportFrequency : long
{
    None = 0,
    Low = 1,
    Medium = 2,
    High = 3,
}

public extern objc class NEFilterVerdict : NSObject, NSSecureCoding, NSCopying
{
    [Selector("shouldReport", "setShouldReport:")] public bool ShouldReport { get; set; }
}

public extern objc class NEFilterNewFlowVerdict : NEFilterVerdict, NSSecureCoding, NSCopying
{
    [Selector("statisticsReportFrequency", "setStatisticsReportFrequency:")] public NEFilterReportFrequency StatisticsReportFrequency { get; set; }
    [Selector("allowVerdict")] public static NEFilterNewFlowVerdict AllowVerdict();
    [Selector("dropVerdict")] public static NEFilterNewFlowVerdict DropVerdict();
    [Selector("filterDataVerdictWithFilterInbound:peekInboundBytes:filterOutbound:peekOutboundBytes:")] public static NEFilterNewFlowVerdict FilterDataVerdictWithFilterInboundPeekInboundBytesFilterOutboundPeekOutboundBytes(bool filterInbound, NSUInteger peekInboundBytes, bool filterOutbound, NSUInteger peekOutboundBytes);
    [Selector("pauseVerdict")] public static NEFilterNewFlowVerdict PauseVerdict();
}

public enum NEFilterAction : long
{
    Invalid = 0,
    Allow = 1,
    Drop = 2,
    Remediate = 3,
    FilterData = 4,
}

public enum NEFilterReportEvent : long
{
    NewFlow = 1,
    DataDecision = 2,
    FlowClosed = 3,
    Statistics = 4,
}

public extern objc class NEFilterReport : NSObject, NSSecureCoding, NSCopying
{
    [Selector("flow")] public NEFilterFlow? Flow { get; }
    [Selector("action")] public NEFilterAction Action { get; }
    [Selector("event")] public NEFilterReportEvent Event { get; }
    [Selector("bytesInboundCount")] public NSUInteger BytesInboundCount { get; }
    [Selector("bytesOutboundCount")] public NSUInteger BytesOutboundCount { get; }
}

public const NSString NEFilterProviderRemediationURLFlowURLHostname = "NE_FLOW_HOSTNAME";

public const NSString NEFilterProviderRemediationURLFlowURL = "NE_FLOW_URL";

public const NSString NEFilterProviderRemediationURLOrganization = "NE_ORGANIZATION";

public const NSString NEFilterProviderRemediationURLUsername = "NE_USERNAME";

#endif
