// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from NetworkExtension.framework (NEOnDemandRule.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.NetworkExtension;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "NetworkExtension")

public enum NEOnDemandRuleAction : long
{
    Connect = 1,
    Disconnect = 2,
    EvaluateConnection = 3,
    Ignore = 4,
}

public enum NEOnDemandRuleInterfaceType : long
{
    Any = 0,
    Ethernet = 1,
    WiFi = 2,
}

public extern objc class NEOnDemandRule : NSObject, NSSecureCoding, NSCopying
{
    [Selector("action")] public NEOnDemandRuleAction Action { get; }
    [Selector("DNSSearchDomainMatch", "setDNSSearchDomainMatch:")] public NSArray? DNSSearchDomainMatch { get; set; }
    [Selector("DNSServerAddressMatch", "setDNSServerAddressMatch:")] public NSArray? DNSServerAddressMatch { get; set; }
    [Selector("interfaceTypeMatch", "setInterfaceTypeMatch:")] public NEOnDemandRuleInterfaceType InterfaceTypeMatch { get; set; }
    [Selector("SSIDMatch", "setSSIDMatch:")] public NSArray? SSIDMatch { get; set; }
    [Selector("probeURL", "setProbeURL:")] public NSURL? ProbeURL { get; set; }
}

public extern objc class NEOnDemandRuleConnect : NEOnDemandRule { }

public extern objc class NEOnDemandRuleDisconnect : NEOnDemandRule { }

public extern objc class NEOnDemandRuleIgnore : NEOnDemandRule { }

public extern objc class NEOnDemandRuleEvaluateConnection : NEOnDemandRule
{
    [Selector("connectionRules", "setConnectionRules:")] public NSArray? ConnectionRules { get; set; }
}

public enum NEEvaluateConnectionRuleAction : long
{
    ConnectIfNeeded = 1,
    NeverConnect = 2,
}

public extern objc class NEEvaluateConnectionRule : NSObject, NSSecureCoding, NSCopying
{
    [Selector("action")] public NEEvaluateConnectionRuleAction Action { get; }
    [Selector("matchDomains")] public NSArray? MatchDomains { get; }
    [Selector("useDNSServers", "setUseDNSServers:")] public NSArray? UseDNSServers { get; set; }
    [Selector("probeURL", "setProbeURL:")] public NSURL? ProbeURL { get; set; }
    [Selector("initWithMatchDomains:andAction:")] public Self InitWithMatchDomainsAndAction(NSArray domains, NEEvaluateConnectionRuleAction action);
}

#endif
