// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from FSKit.framework (FSContainer.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.FSKit;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "FSKit")

public enum FSContainerState : long
{
    NotReady = 0,
    Blocked = 1,
    Ready = 2,
    Active = 3,
}

public extern objc class FSContainerStatus : NSObject, NSCopying
{
    [Selector("state")] public FSContainerState State { get; }
    [Selector("status")] public NSError? Status { get; }
    [Selector("active")] public static FSContainerStatus Active { get; }
    [Selector("ready")] public static FSContainerStatus Ready { get; }
    [Selector("activeWithStatus:")] public static Self ActiveWithStatus(NSError errorStatus);
    [Selector("blockedWithStatus:")] public static Self BlockedWithStatus(NSError errorStatus);
    [Selector("notReadyWithStatus:")] public static Self NotReadyWithStatus(NSError errorStatus);
    [Selector("readyWithStatus:")] public static Self ReadyWithStatus(NSError errorStatus);
}

/// macOS 15.4 and later.
public extern objc class FSContainerIdentifier : FSEntityIdentifier
{
    [Selector("volumeIdentifier")] public FSVolumeIdentifier VolumeIdentifier { get; }
}

#endif
