// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Carbon.framework (HIToolbox_HITheme.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Carbon;

import MacOS.ApplicationServices;
import MacOS.CoreFoundation;
import MacOS.CoreGraphics;
import MacOS.CoreText;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Carbon")

public const int kHIThemeOrientationNormal = 0;
public const int kHIThemeOrientationInverted = 1;

public using HIThemeOrientation = UInt32;

public const int kHIThemeSplitterAdornmentNone = 0;
public const int kHIThemeSplitterAdornmentMetal = 1;

public using HIThemeSplitterAdornment = UInt32;

public const int kHIThemeGrowBoxKindNormal = 0;
public const int kHIThemeGrowBoxKindNone = 1;

public using HIThemeGrowBoxKind = UInt32;

public const int kHIThemeGrowBoxSizeNormal = 0;
public const int kHIThemeGrowBoxSizeSmall = 1;

public using HIThemeGrowBoxSize = UInt32;

public const int kHIThemeGroupBoxKindPrimary = 0;
public const int kHIThemeGroupBoxKindSecondary = 1;
public const int kHIThemeGroupBoxKindPrimaryOpaque = 3;
public const int kHIThemeGroupBoxKindSecondaryOpaque = 4;

public using HIThemeGroupBoxKind = UInt32;

public const int kHIThemeHeaderKindWindow = 0;
public const int kHIThemeHeaderKindList = 1;

public using HIThemeHeaderKind = UInt32;

public const int kHIThemeFrameTextFieldSquare = 0;
public const int kHIThemeFrameListBox = 1;
public const int kHIThemeFrameTextFieldRound = 1000;
public const int kHIThemeFrameTextFieldRoundSmall = 1001;
public const int kHIThemeFrameTextFieldRoundMini = 1002;

public using HIThemeFrameKind = UInt32;

public const int kHIThemeMenuTitleDrawCondensed = 1;

[Pack(2)]
public struct HIScrollBarTrackInfo
{
    public UInt32 version;
    public ThemeTrackEnableState enableState;
    public ThemeTrackPressState pressState;
    public CGFloat viewsize;
}

[Pack(2)]
public union HIThemeTrackDrawInfoTrackInfo
{
    public ScrollBarTrackInfo scrollbar;
    public SliderTrackInfo slider;
    public ProgressTrackInfo progress;
}

[Pack(2)]
public struct HIThemeTrackDrawInfo
{
    public UInt32 version;
    public ThemeTrackKind kind;
    public HIRect bounds;
    public SInt32 min;
    public SInt32 max;
    public SInt32 value;
    public UInt32 reserved;
    public ThemeTrackAttributes attributes;
    public ThemeTrackEnableState enableState;
    public UInt8 filler1;
    public HIThemeTrackDrawInfoTrackInfo trackInfo;
}

[Pack(2)]
public struct HIThemeAnimationTimeInfo
{
    public CFAbsoluteTime start;
    public CFAbsoluteTime current;
}

[Pack(2)]
public struct HIThemeAnimationFrameInfo
{
    public UInt32 index;
}

[Pack(2)]
public union HIThemeButtonDrawInfoAnimation
{
    public HIThemeAnimationTimeInfo time;
    public HIThemeAnimationFrameInfo frame;
}

[Pack(2)]
public struct HIThemeButtonDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeButtonKind kind;
    public ThemeButtonValue value;
    public ThemeButtonAdornment adornment;
    public HIThemeButtonDrawInfoAnimation animation;
}

public using HIThemeButtonDrawInfoPtr = HIThemeButtonDrawInfo*;

[Pack(2)]
public struct HIThemeSplitterDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public HIThemeSplitterAdornment adornment;
}

public using HIThemeSplitterDrawInfoPtr = HIThemeSplitterDrawInfo*;

public const int kHIThemeTabAdornmentNone = 0;
public const int kHIThemeTabAdornmentFocus = 4;
public const int kHIThemeTabAdornmentLeadingSeparator = 8;
public const int kHIThemeTabAdornmentTrailingSeparator = 16;

public using HIThemeTabAdornment = UInt32;

public const int kHIThemeTabSizeNormal = 0;
public const int kHIThemeTabSizeSmall = 1;
public const int kHIThemeTabSizeMini = 3;

public using HIThemeTabSize = UInt32;

public const int kHIThemeTabPositionFirst = 0;
public const int kHIThemeTabPositionMiddle = 1;
public const int kHIThemeTabPositionLast = 2;
public const int kHIThemeTabPositionOnly = 3;

public using HIThemeTabPosition = UInt32;

public const int kHIThemeTabKindNormal = 0;

public using HIThemeTabKind = UInt32;

[Pack(2)]
public struct HIThemeTabDrawInfo
{
    public UInt32 version;
    public ThemeTabStyle style;
    public ThemeTabDirection direction;
    public HIThemeTabSize size;
    public HIThemeTabAdornment adornment;
    public HIThemeTabKind kind;
    public HIThemeTabPosition position;
}

[Pack(2)]
public struct HIThemeTabDrawInfoVersionZero
{
    public UInt32 version;
    public ThemeTabStyle style;
    public ThemeTabDirection direction;
    public HIThemeTabSize size;
    public HIThemeTabAdornment adornment;
}

public const int kHIThemeTabPaneAdornmentNormal = 0;

public using HIThemeTabPaneAdornment = UInt32;

[Pack(2)]
public struct HIThemeTabPaneDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeTabDirection direction;
    public HIThemeTabSize size;
    public HIThemeTabKind kind;
    public HIThemeTabPaneAdornment adornment;
}

[Pack(2)]
public struct HIThemeTabPaneDrawInfoVersionZero
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeTabDirection direction;
    public HIThemeTabSize size;
}

public const int kHIThemeMenuDrawInfoVersionZero = 0;
public const int kHIThemeMenuDrawInfoVersionOne = 1001;

[Pack(2)]
public struct HIThemeMenuDrawInfo
{
    public UInt32 version;
    public ThemeMenuType menuType;
    public ulong reserved1;
    public CGFloat reserved2;
    public UInt32 menuDirection;
    public CGFloat reserved3;
    public CGFloat reserved4;
}

public using HIThemeMenuDrawInfoPtr = HIThemeMenuDrawInfo*;

[Pack(2)]
public struct HIThemeMenuDrawInfoVersionZero
{
    public UInt32 version;
    public ThemeMenuType menuType;
}

public using HIThemeMenuDrawInfoVersionZeroPtr = HIThemeMenuDrawInfoVersionZero*;

[Pack(2)]
public struct HIThemeMenuItemDrawInfo
{
    public UInt32 version;
    public ThemeMenuItemType itemType;
    public ThemeMenuState state;
}

public using HIThemeMenuItemDrawInfoPtr = HIThemeMenuItemDrawInfo*;

[Pack(2)]
public struct HIThemeFrameDrawInfo
{
    public UInt32 version;
    public HIThemeFrameKind kind;
    public ThemeDrawState state;
    public Boolean isFocused;
}

public using HIThemeFrameDrawInfoPtr = HIThemeFrameDrawInfo*;

[Pack(2)]
public struct HIThemeGroupBoxDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public HIThemeGroupBoxKind kind;
}

public using HIThemeGroupBoxDrawInfoPtr = HIThemeGroupBoxDrawInfo*;

[Pack(2)]
public struct HIThemeGrabberDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
}

public using HIThemeGrabberDrawInfoPtr = HIThemeGrabberDrawInfo*;

[Pack(2)]
public struct HIThemePlacardDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
}

public using HIThemePlacardDrawInfoPtr = HIThemePlacardDrawInfo*;

[Pack(2)]
public struct HIThemeHeaderDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public HIThemeHeaderKind kind;
}

public using HIThemeHeaderDrawInfoPtr = HIThemeHeaderDrawInfo*;

[Pack(2)]
public struct HIThemeMenuBarDrawInfo
{
    public UInt32 version;
    public ThemeMenuBarState state;
    public OptionBits attributes;
}

public using HIThemeMenuBarDrawInfoPtr = HIThemeMenuBarDrawInfo*;

[Pack(2)]
public struct HIThemeMenuTitleDrawInfo
{
    public UInt32 version;
    public ThemeMenuState state;
    public OptionBits attributes;
    public CGFloat condensedTitleExtra;
}

public using HIThemeMenuTitleDrawInfoPtr = HIThemeMenuTitleDrawInfo*;

[Pack(2)]
public struct HIThemeTickMarkDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
}

public using HIThemeTickMarkDrawInfoPtr = HIThemeTickMarkDrawInfo*;

[Pack(2)]
public struct HIThemeWindowDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeWindowType windowType;
    public ThemeWindowAttributes attributes;
    public CGFloat titleHeight;
    public CGFloat titleWidth;
}

public using HIThemeWindowDrawInfoPtr = HIThemeWindowDrawInfo*;

[Pack(2)]
public struct HIThemeWindowWidgetDrawInfo
{
    public UInt32 version;
    public ThemeDrawState widgetState;
    public ThemeTitleBarWidget widgetType;
    public ThemeDrawState windowState;
    public ThemeWindowType windowType;
    public ThemeWindowAttributes attributes;
    public CGFloat titleHeight;
    public CGFloat titleWidth;
}

public using HIThemeWindowWidgetDrawInfoPtr = HIThemeWindowWidgetDrawInfo*;

[Pack(2)]
public struct HIThemeSeparatorDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
}

public using HIThemeSeparatorDrawInfoPtr = HIThemeSeparatorDrawInfo*;

[Pack(2)]
public struct HIThemeScrollBarDelimitersDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeWindowType windowType;
    public ThemeWindowAttributes attributes;
}

public using HIThemeScrollBarDelimitersDrawInfoPtr = HIThemeScrollBarDelimitersDrawInfo*;

[Pack(2)]
public struct HIThemeChasingArrowsDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public UInt32 index;
}

public using HIThemeChasingArrowsDrawInfoPtr = HIThemeChasingArrowsDrawInfo*;

[Pack(2)]
public struct HIThemePopupArrowDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeArrowOrientation orientation;
    public ThemePopupArrowSize size;
}

public using HIThemePopupArrowDrawInfoPtr = HIThemePopupArrowDrawInfo*;

[Pack(2)]
public struct HIThemeGrowBoxDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public HIThemeGrowBoxKind kind;
    public ThemeGrowDirection direction;
    public HIThemeGrowBoxSize size;
}

public using HIThemeGrowBoxDrawInfoPtr = HIThemeGrowBoxDrawInfo*;

[Pack(2)]
public struct HIThemeBackgroundDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeBackgroundKind kind;
}

public using HIThemeBackgroundDrawInfoPtr = HIThemeBackgroundDrawInfo*;

public extern "C" OSStatus HIThemeDrawButton(HIRect* inBounds, HIThemeButtonDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation, HIRect* outLabelRect);

public extern "C" OSStatus HIThemeGetButtonShape(HIRect* inBounds, HIThemeButtonDrawInfo* inDrawInfo, __HIShape** outShape);

public extern "C" OSStatus HIThemeGetButtonContentBounds(HIRect* inBounds, HIThemeButtonDrawInfo* inDrawInfo, HIRect* outBounds);

public extern "C" OSStatus HIThemeGetButtonBackgroundBounds(HIRect* inBounds, HIThemeButtonDrawInfo* inDrawInfo, HIRect* outBounds);

public extern "C" OSStatus HIThemeDrawChasingArrows(HIRect* inBounds, HIThemeChasingArrowsDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawPopupArrow(HIRect* inBounds, HIThemePopupArrowDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawMenuBarBackground(HIRect* inBounds, HIThemeMenuBarDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawMenuTitle(HIRect* inMenuBarRect, HIRect* inTitleRect, HIThemeMenuTitleDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation, HIRect* outLabelRect);

public extern "C" OSStatus HIThemeDrawMenuBackground(HIRect* inMenuRect, HIThemeMenuDrawInfo* inMenuDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawMenuItem(HIRect* inMenuRect, HIRect* inItemRect, HIThemeMenuItemDrawInfo* inItemDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation, HIRect* outContentRect);

public extern "C" OSStatus HIThemeDrawMenuSeparator(HIRect* inMenuRect, HIRect* inItemRect, HIThemeMenuItemDrawInfo* inItemDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeGetMenuBackgroundShape(HIRect* inMenuRect, HIThemeMenuDrawInfo* inMenuDrawInfo, __HIShape** outShape);

public const int kHIThemeSegmentPositionFirst = 0;
public const int kHIThemeSegmentPositionMiddle = 1;
public const int kHIThemeSegmentPositionLast = 2;
public const int kHIThemeSegmentPositionOnly = 3;

public using HIThemeSegmentPosition = UInt32;

public const int kHIThemeSegmentKindNormal = 0;
public const int kHIThemeSegmentKindTextured = 1;
public const int kHIThemeSegmentKindInset = 1;

public using HIThemeSegmentKind = UInt32;

public const int kHIThemeSegmentSizeNormal = 0;
public const int kHIThemeSegmentSizeSmall = 1;
public const int kHIThemeSegmentSizeMini = 3;

public using HIThemeSegmentSize = UInt32;

public const int kHIThemeSegmentAdornmentNone = 0;
public const int kHIThemeSegmentAdornmentFocus = 4;
public const int kHIThemeSegmentAdornmentLeadingSeparator = 8;
public const int kHIThemeSegmentAdornmentTrailingSeparator = 16;

public using HIThemeSegmentAdornment = UInt32;

[Pack(2)]
public struct HIThemeSegmentDrawInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeButtonValue value;
    public HIThemeSegmentSize size;
    public HIThemeSegmentKind kind;
    public HIThemeSegmentPosition position;
    public HIThemeSegmentAdornment adornment;
}

public using HIThemeSegmentDrawInfoPtr = HIThemeSegmentDrawInfo*;

public extern "C" OSStatus HIThemeDrawSegment(HIRect* inBounds, HIThemeSegmentDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawTabPane(HIRect* inRect, HIThemeTabPaneDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawTab(HIRect* inRect, HIThemeTabDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation, HIRect* outLabelRect);

public extern "C" OSStatus HIThemeGetTabPaneDrawShape(HIRect* inRect, ThemeTabDirection inDirection, HIThemeTabSize inTabSize, __HIShape** outShape);

public extern "C" OSStatus HIThemeGetTabPaneContentShape(HIRect* inRect, ThemeTabDirection inDirection, HIThemeTabSize inTabSize, __HIShape** outShape);

public extern "C" OSStatus HIThemeGetTabDrawShape(HIRect* inRect, HIThemeTabDrawInfo* inDrawInfo, __HIShape** outShape);

public extern "C" OSStatus HIThemeGetTabShape(HIRect* inRect, HIThemeTabDrawInfo* inDrawInfo, __HIShape** outShape);

public const int kHIThemeTextTruncationNone = 0;
public const int kHIThemeTextTruncationMiddle = 1;
public const int kHIThemeTextTruncationEnd = 2;
public const int kHIThemeTextTruncationDefault = 3;

public using HIThemeTextTruncation = UInt32;

public const int kHIThemeTextHorizontalFlushLeft = 0;
public const int kHIThemeTextHorizontalFlushCenter = 1;
public const int kHIThemeTextHorizontalFlushRight = 2;
public const int kHIThemeTextHorizontalFlushDefault = 3;

public using HIThemeTextHorizontalFlush = UInt32;

public const int kHIThemeTextVerticalFlushTop = 0;
public const int kHIThemeTextVerticalFlushCenter = 1;
public const int kHIThemeTextVerticalFlushBottom = 2;
public const int kHIThemeTextVerticalFlushDefault = 3;

public using HIThemeTextVerticalFlush = UInt32;

public const int kHIThemeTextBoxOptionNone = 0;
public const int kHIThemeTextBoxOptionStronglyVertical = 2;
public const int kHIThemeTextBoxOptionEngraved = 4;
public const int kHIThemeTextBoxOptionDontClip = 262144;

public using HIThemeTextBoxOptions = OptionBits;

public const int kHIThemeTextInfoVersionZero = 0;
public const int kHIThemeTextInfoVersionOne = 1;

[Pack(2)]
public struct HIThemeTextInfo
{
    public UInt32 version;
    public ThemeDrawState state;
    public ThemeFontID fontID;
    public HIThemeTextHorizontalFlush horizontalFlushness;
    public HIThemeTextVerticalFlush verticalFlushness;
    public HIThemeTextBoxOptions options;
    public HIThemeTextTruncation truncationPosition;
    public UInt32 truncationMaxLines;
    public Boolean truncationHappened;
    public UInt8 filler1;
    public __CTFont* font;
}

public extern "C" OSStatus HIThemeGetTextDimensions(CFTypeRef? inString, CGFloat inWidth, HIThemeTextInfo* inTextInfo, CGFloat* outWidth, CGFloat* outHeight, CGFloat* outBaseline);

public extern "C" OSStatus HIThemeDrawTextBox(CFTypeRef? inString, HIRect* inBounds, HIThemeTextInfo* inTextInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" CTFontUIFontType HIThemeGetUIFontType(ThemeFontID inFontID);

public extern "C" OSStatus HIThemeDrawTrack(HIThemeTrackDrawInfo* inDrawInfo, HIRect* inGhostRect, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawTrackTickMarks(HIThemeTrackDrawInfo* inDrawInfo, ItemCount inNumTicks, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawTickMark(HIRect* inBounds, HIThemeTickMarkDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeGetTrackThumbShape(HIThemeTrackDrawInfo* inDrawInfo, __HIShape** outThumbShape);

public extern "C" Boolean HIThemeHitTestTrack(HIThemeTrackDrawInfo* inDrawInfo, HIPoint* inMousePoint, ControlPartCode* outPartHit);

public extern "C" OSStatus HIThemeGetTrackBounds(HIThemeTrackDrawInfo* inDrawInfo, HIRect* outBounds);

public extern "C" OSStatus HIThemeGetTrackPartBounds(HIThemeTrackDrawInfo* inDrawInfo, ControlPartCode inPartCode, HIRect* outPartBounds);

public extern "C" OSStatus HIThemeGetTrackParts(HIThemeTrackDrawInfo* inDrawInfo, UInt32* outNumberOfParts, UInt32 inMaxParts, ControlPartCode* ioPartsBuffer);

public extern "C" OSStatus HIThemeGetTrackDragRect(HIThemeTrackDrawInfo* inDrawInfo, HIRect* outDragRect);

public extern "C" OSStatus HIThemeGetTrackThumbPositionFromOffset(HIThemeTrackDrawInfo* inDrawInfo, HIPoint* inThumbOffset, CGFloat* outRelativePosition);

public extern "C" OSStatus HIThemeGetTrackThumbPositionFromBounds(HIThemeTrackDrawInfo* inDrawInfo, HIRect* inThumbBounds, CGFloat* outRelativePosition);

public extern "C" OSStatus HIThemeGetTrackLiveValue(HIThemeTrackDrawInfo* inDrawInfo, CGFloat inRelativePosition, SInt32* outValue);

public extern "C" OSStatus HIThemeGetScrollBarTrackRect(HIRect* inBounds, HIScrollBarTrackInfo* inTrackInfo, Boolean inIsHoriz, HIRect* outTrackBounds);

public extern "C" Boolean HIThemeHitTestScrollBarArrows(HIRect* inScrollBarBounds, HIScrollBarTrackInfo* inTrackInfo, Boolean inIsHoriz, HIPoint* inPtHit, HIRect* outTrackBounds, ControlPartCode* outPartCode);

public extern "C" OSStatus HIThemeDrawScrollBarDelimiters(HIRect* inContRect, HIThemeScrollBarDelimitersDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawWindowFrame(HIRect* inContRect, HIThemeWindowDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation, HIRect* outTitleRect);

public extern "C" OSStatus HIThemeDrawTitleBarWidget(HIRect* inContRect, HIThemeWindowWidgetDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawGrowBox(HIPoint* inOrigin, HIThemeGrowBoxDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeGetGrowBoxBounds(HIPoint* inOrigin, HIThemeGrowBoxDrawInfo* inDrawInfo, HIRect* outBounds);

public extern "C" OSStatus HIThemeGetWindowShape(HIRect* inContRect, HIThemeWindowDrawInfo* inDrawInfo, WindowRegionCode inWinRegion, __HIShape** outShape);

public extern "C" Boolean HIThemeGetWindowRegionHit(HIRect* inContRect, HIThemeWindowDrawInfo* inDrawInfo, HIPoint* inPoint, WindowRegionCode* outRegionHit);

public extern "C" OSStatus HIThemeDrawFrame(HIRect* inRect, HIThemeFrameDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawGroupBox(HIRect* inRect, HIThemeGroupBoxDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawGenericWell(HIRect* inRect, HIThemeButtonDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawPaneSplitter(HIRect* inRect, HIThemeSplitterDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawGrabber(HIRect* inRect, HIThemeGrabberDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawPlacard(HIRect* inRect, HIThemePlacardDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawHeader(HIRect* inRect, HIThemeHeaderDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawFocusRect(HIRect* inRect, Boolean inHasFocus, CGContextRef? inContext, HIThemeOrientation inOrientation);

public const int kHIThemeFocusRingOnly = 0;
public const int kHIThemeFocusRingAbove = 1;
public const int kHIThemeFocusRingBelow = 2;

public using HIThemeFocusRing = UInt32;

public extern "C" OSStatus HIThemeBeginFocus(CGContextRef? inContext, HIThemeFocusRing inRing, void* inReserved);

public extern "C" OSStatus HIThemeEndFocus(CGContextRef? inContext);

public extern "C" OSStatus HIThemeDrawSeparator(HIRect* inRect, HIThemeSeparatorDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeSetFill(ThemeBrush inBrush, void* inInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeSetStroke(ThemeBrush inBrush, void* inInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeSetTextFill(ThemeTextColor inColor, void* inInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeApplyBackground(HIRect* inBounds, HIThemeBackgroundDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeDrawBackground(HIRect* inBounds, HIThemeBackgroundDrawInfo* inDrawInfo, CGContextRef? inContext, HIThemeOrientation inOrientation);

public extern "C" OSStatus HIThemeBrushCreateCGColor(ThemeBrush inBrush, CGColor** outColor);

public extern "C" OSStatus HIThemeGetTextColorForThemeBrush(ThemeBrush inBrush, Boolean inWindowIsActive, ThemeTextColor* outColor);

public extern "C" OSStatus GetThemeMenuSeparatorHeight(SInt16* outHeight);

public extern "C" OSStatus GetThemeMenuItemExtra(ThemeMenuItemType inItemType, SInt16* outHeight, SInt16* outWidth);

public extern "C" OSStatus GetThemeMenuTitleExtra(SInt16* outWidth, Boolean inIsSquished);

public const int kThemeMetricScrollBarWidth = 0;
public const int kThemeMetricSmallScrollBarWidth = 1;
public const int kThemeMetricCheckBoxHeight = 2;
public const int kThemeMetricRadioButtonHeight = 3;
public const int kThemeMetricEditTextWhitespace = 4;
public const int kThemeMetricEditTextFrameOutset = 5;
public const int kThemeMetricListBoxFrameOutset = 6;
public const int kThemeMetricFocusRectOutset = 7;
public const int kThemeMetricImageWellThickness = 8;
public const int kThemeMetricScrollBarOverlap = 9;
public const int kThemeMetricLargeTabHeight = 10;
public const int kThemeMetricLargeTabCapsWidth = 11;
public const int kThemeMetricTabFrameOverlap = 12;
public const int kThemeMetricTabIndentOrStyle = 13;
public const int kThemeMetricTabOverlap = 14;
public const int kThemeMetricSmallTabHeight = 15;
public const int kThemeMetricSmallTabCapsWidth = 16;
public const int kThemeMetricPushButtonHeight = 19;
public const int kThemeMetricListHeaderHeight = 20;
public const int kThemeMetricDisclosureTriangleHeight = 25;
public const int kThemeMetricDisclosureTriangleWidth = 26;
public const int kThemeMetricLittleArrowsHeight = 27;
public const int kThemeMetricLittleArrowsWidth = 28;
public const int kThemeMetricPopupButtonHeight = 30;
public const int kThemeMetricSmallPopupButtonHeight = 31;
public const int kThemeMetricLargeProgressBarThickness = 32;
public const int kThemeMetricPullDownHeight = 33;
public const int kThemeMetricSmallPullDownHeight = 34;
public const int kThemeMetricResizeControlHeight = 38;
public const int kThemeMetricSmallResizeControlHeight = 39;
public const int kThemeMetricHSliderHeight = 41;
public const int kThemeMetricHSliderTickHeight = 42;
public const int kThemeMetricVSliderWidth = 45;
public const int kThemeMetricVSliderTickWidth = 46;
public const int kThemeMetricTitleBarControlsHeight = 49;
public const int kThemeMetricCheckBoxWidth = 50;
public const int kThemeMetricRadioButtonWidth = 52;
public const int kThemeMetricNormalProgressBarThickness = 58;
public const int kThemeMetricProgressBarShadowOutset = 59;
public const int kThemeMetricSmallProgressBarShadowOutset = 60;
public const int kThemeMetricPrimaryGroupBoxContentInset = 61;
public const int kThemeMetricSecondaryGroupBoxContentInset = 62;
public const int kThemeMetricMenuMarkColumnWidth = 63;
public const int kThemeMetricMenuExcludedMarkColumnWidth = 64;
public const int kThemeMetricMenuMarkIndent = 65;
public const int kThemeMetricMenuTextLeadingEdgeMargin = 66;
public const int kThemeMetricMenuTextTrailingEdgeMargin = 67;
public const int kThemeMetricMenuIndentWidth = 68;
public const int kThemeMetricMenuIconTrailingEdgeMargin = 69;

public const int kThemeMetricDisclosureButtonHeight = 17;
public const int kThemeMetricRoundButtonSize = 18;
public const int kThemeMetricSmallCheckBoxHeight = 21;
public const int kThemeMetricDisclosureButtonWidth = 22;
public const int kThemeMetricSmallDisclosureButtonHeight = 23;
public const int kThemeMetricSmallDisclosureButtonWidth = 24;
public const int kThemeMetricPaneSplitterHeight = 29;
public const int kThemeMetricSmallPushButtonHeight = 35;
public const int kThemeMetricSmallRadioButtonHeight = 36;
public const int kThemeMetricRelevanceIndicatorHeight = 37;
public const int kThemeMetricLargeRoundButtonSize = 40;
public const int kThemeMetricSmallHSliderHeight = 43;
public const int kThemeMetricSmallHSliderTickHeight = 44;
public const int kThemeMetricSmallVSliderWidth = 47;
public const int kThemeMetricSmallVSliderTickWidth = 48;
public const int kThemeMetricSmallCheckBoxWidth = 51;
public const int kThemeMetricSmallRadioButtonWidth = 53;
public const int kThemeMetricSmallHSliderMinThumbWidth = 54;
public const int kThemeMetricSmallVSliderMinThumbHeight = 55;
public const int kThemeMetricSmallHSliderTickOffset = 56;
public const int kThemeMetricSmallVSliderTickOffset = 57;

public const int kThemeMetricComboBoxLargeBottomShadowOffset = 70;
public const int kThemeMetricComboBoxLargeRightShadowOffset = 71;
public const int kThemeMetricComboBoxSmallBottomShadowOffset = 72;
public const int kThemeMetricComboBoxSmallRightShadowOffset = 73;
public const int kThemeMetricComboBoxLargeDisclosureWidth = 74;
public const int kThemeMetricComboBoxSmallDisclosureWidth = 75;
public const int kThemeMetricRoundTextFieldContentInsetLeft = 76;
public const int kThemeMetricRoundTextFieldContentInsetRight = 77;
public const int kThemeMetricRoundTextFieldContentInsetBottom = 78;
public const int kThemeMetricRoundTextFieldContentInsetTop = 79;
public const int kThemeMetricRoundTextFieldContentHeight = 80;
public const int kThemeMetricComboBoxMiniBottomShadowOffset = 81;
public const int kThemeMetricComboBoxMiniDisclosureWidth = 82;
public const int kThemeMetricComboBoxMiniRightShadowOffset = 83;
public const int kThemeMetricLittleArrowsMiniHeight = 84;
public const int kThemeMetricLittleArrowsMiniWidth = 85;
public const int kThemeMetricLittleArrowsSmallHeight = 86;
public const int kThemeMetricLittleArrowsSmallWidth = 87;
public const int kThemeMetricMiniCheckBoxHeight = 88;
public const int kThemeMetricMiniCheckBoxWidth = 89;
public const int kThemeMetricMiniDisclosureButtonHeight = 90;
public const int kThemeMetricMiniDisclosureButtonWidth = 91;
public const int kThemeMetricMiniHSliderHeight = 92;
public const int kThemeMetricMiniHSliderMinThumbWidth = 93;
public const int kThemeMetricMiniHSliderTickHeight = 94;
public const int kThemeMetricMiniHSliderTickOffset = 95;
public const int kThemeMetricMiniPopupButtonHeight = 96;
public const int kThemeMetricMiniPullDownHeight = 97;
public const int kThemeMetricMiniPushButtonHeight = 98;
public const int kThemeMetricMiniRadioButtonHeight = 99;
public const int kThemeMetricMiniRadioButtonWidth = 100;
public const int kThemeMetricMiniTabCapsWidth = 101;
public const int kThemeMetricMiniTabFrameOverlap = 102;
public const int kThemeMetricMiniTabHeight = 103;
public const int kThemeMetricMiniTabOverlap = 104;
public const int kThemeMetricMiniVSliderMinThumbHeight = 105;
public const int kThemeMetricMiniVSliderTickOffset = 106;
public const int kThemeMetricMiniVSliderTickWidth = 107;
public const int kThemeMetricMiniVSliderWidth = 108;
public const int kThemeMetricRoundTextFieldContentInsetWithIconLeft = 109;
public const int kThemeMetricRoundTextFieldContentInsetWithIconRight = 110;
public const int kThemeMetricRoundTextFieldMiniContentHeight = 111;
public const int kThemeMetricRoundTextFieldMiniContentInsetBottom = 112;
public const int kThemeMetricRoundTextFieldMiniContentInsetLeft = 113;
public const int kThemeMetricRoundTextFieldMiniContentInsetRight = 114;
public const int kThemeMetricRoundTextFieldMiniContentInsetTop = 115;
public const int kThemeMetricRoundTextFieldMiniContentInsetWithIconLeft = 116;
public const int kThemeMetricRoundTextFieldMiniContentInsetWithIconRight = 117;
public const int kThemeMetricRoundTextFieldSmallContentHeight = 118;
public const int kThemeMetricRoundTextFieldSmallContentInsetBottom = 119;
public const int kThemeMetricRoundTextFieldSmallContentInsetLeft = 120;
public const int kThemeMetricRoundTextFieldSmallContentInsetRight = 121;
public const int kThemeMetricRoundTextFieldSmallContentInsetTop = 122;
public const int kThemeMetricRoundTextFieldSmallContentInsetWithIconLeft = 123;
public const int kThemeMetricRoundTextFieldSmallContentInsetWithIconRight = 124;
public const int kThemeMetricSmallTabFrameOverlap = 125;
public const int kThemeMetricSmallTabOverlap = 126;
public const int kThemeMetricSmallPaneSplitterHeight = 127;

public const int kThemeMetricHSliderTickOffset = 128;
public const int kThemeMetricVSliderTickOffset = 129;
public const int kThemeMetricSliderMinThumbHeight = 130;
public const int kThemeMetricSliderMinThumbWidth = 131;
public const int kThemeMetricScrollBarMinThumbHeight = 132;
public const int kThemeMetricScrollBarMinThumbWidth = 133;
public const int kThemeMetricSmallScrollBarMinThumbHeight = 134;
public const int kThemeMetricSmallScrollBarMinThumbWidth = 135;
public const int kThemeMetricButtonRoundedHeight = 136;
public const int kThemeMetricButtonRoundedRecessedHeight = 137;

public const int kThemeMetricSeparatorSize = 138;
public const int kThemeMetricTexturedPushButtonHeight = 139;
public const int kThemeMetricTexturedSmallPushButtonHeight = 140;

public using ThemeMetric = UInt32;

public extern "C" OSStatus GetThemeMetric(ThemeMetric inMetric, SInt32* outMetric);

public extern "C" OSStatus CopyThemeIdentifier(__CFString** outIdentifier);

public const int kThemeMetricCheckBoxGlyphHeight = 2;
public const int kThemeMetricRadioButtonGlyphHeight = 3;
public const int kThemeMetricDisclosureButtonSize = 17;
public const int kThemeMetricBestListHeaderHeight = 20;
public const int kThemeMetricSmallProgressBarThickness = 58;
public const int kThemeMetricProgressBarThickness = 32;

#endif
