// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from ScreenSaver.framework (ScreenSaverView.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.ScreenSaver;

import MacOS.AppKit;
import MacOS.Foundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "ScreenSaver")

public extern objc class ScreenSaverView : NSView
{
    [Selector("animationTimeInterval", "setAnimationTimeInterval:")]
    public NSTimeInterval AnimationTimeInterval { get; set; }
    [Selector("isAnimating")]
    public bool Animating { get; }
    [Selector("hasConfigureSheet")]
    public bool HasConfigureSheet { get; }
    [Selector("configureSheet")]
    public NSWindow? ConfigureSheet { get; }
    [Selector("isPreview")]
    public bool Preview { get; }
    [Selector("backingStoreType")]
    public static NSBackingStoreType BackingStoreType();
    [Selector("performGammaFade")]
    public static bool PerformGammaFade();
    [Selector("initWithFrame:isPreview:")]
    public Self? InitWithFrameIsPreview(NSRect frame, bool isPreview);
    [Selector("startAnimation")]
    public void StartAnimation();
    [Selector("stopAnimation")]
    public void StopAnimation();
    [Selector("drawRect:")]
    public void DrawRect(NSRect rect);
    [Selector("animateOneFrame")]
    public void AnimateOneFrame();
}

#endif
