// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from JavaRuntimeSupport.framework (JRSSecurity.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.JavaRuntimeSupport;

import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "JavaRuntimeSupport")

#if X64
public const int JRSSecurityExecutableCodeSignatureMissing = 0;
public const int JRSSecurityExecutableCodeSignatureUnverifiable = 1;
public const int JRSSecurityExecutableCodeSignatureValidatedThroughTrustedCA = 2;
public const int JRSSecurityExecutableCodeSignatureExplicitlyTrusted = 3;
public const int JRSSecurityExecutableCodeSignatureExplicitlyUntrusted = 4;
public const int JRSSecurityExecutableCodeSignatureExpired = 5;
#endif

#if X64
public using JRSSecurityExecutableCodeSignatureEvaluation = uint;
#endif

#if X64
public const int JRSSecurityExecutionPolicyNoPrompt = 0;
public const int JRSSecurityExecutionPolicyOKPrompt = 1;
public const int JRSSecurityExecutionPolicyWarnPrompt = 2;
public const int JRSSecurityExecutionPolicyBlockExecution = 3;
#endif

#if X64
public using JRSSecurityExecutionPolicy = uint;
#endif

#if X64
/// Deprecated in macOS 11.0.
public extern objc class JRSSecurity : NSObject
{
    [Selector("executionPolicyForExecutableCodeSignatureEvaluation:")]
    public static JRSSecurityExecutionPolicy ExecutionPolicyForExecutableCodeSignatureEvaluation(JRSSecurityExecutableCodeSignatureEvaluation evaluation);
}
#endif

#endif
