// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from MetalKit.framework (MTKModel.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.MetalKit;

import MacOS.Foundation;
import MacOS.Metal;
import MacOS.ModelIO;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "MetalKit")

public using MTKModelError = NSString;

public extern "C" MTKModelError? MTKModelErrorDomain;

public extern "C" MTKModelError? MTKModelErrorKey;

public extern objc class MTKMeshBufferAllocator : NSObject, MDLMeshBufferAllocator
{
    [Selector("device")] public MTLDevice Device { get; }
    [Selector("initWithDevice:")] public Self InitWithDevice(MTLDevice device);
}

public extern objc class MTKMeshBuffer : NSObject, MDLMeshBuffer, MDLNamed
{
    [Selector("length")] public NSUInteger Length { get; }
    [Selector("allocator")] public MTKMeshBufferAllocator Allocator { get; }
    [Selector("zone")] public MDLMeshBufferZone? Zone { get; }
    [Selector("buffer")] public MTLBuffer Buffer { get; }
    [Selector("offset")] public NSUInteger Offset { get; }
    [Selector("type")] public MDLMeshBufferType Type { get; }
}

public extern objc class MTKSubmesh : NSObject
{
    [Selector("primitiveType")] public MTLPrimitiveType PrimitiveType { get; }
    [Selector("indexType")] public MTLIndexType IndexType { get; }
    [Selector("indexBuffer")] public MTKMeshBuffer IndexBuffer { get; }
    [Selector("indexCount")] public NSUInteger IndexCount { get; }
    [Selector("mesh")] public MTKMesh? Mesh { get; }
    [Selector("name", "setName:")] public NSString Name { get; set; }
}

public extern objc class MTKMesh : NSObject
{
    [Selector("vertexBuffers")] public NSArray VertexBuffers { get; }
    [Selector("vertexDescriptor")] public MDLVertexDescriptor VertexDescriptor { get; }
    [Selector("submeshes")] public NSArray Submeshes { get; }
    [Selector("vertexCount")] public NSUInteger VertexCount { get; }
    [Selector("name", "setName:")] public NSString Name { get; set; }
    [Selector("initWithMesh:device:error:")] public Self? InitWithMeshDeviceError(MDLMesh mesh, MTLDevice device, out NSError? error);
    [Selector("newMeshesFromAsset:device:sourceMeshes:error:")] public static NSArray? NewMeshesFromAssetDeviceSourceMeshesError(MDLAsset asset, MTLDevice device, out NSArray? sourceMeshes, out NSError? error);
}

public extern "C" MDLVertexDescriptor MTKModelIOVertexDescriptorFromMetal(MTLVertexDescriptor metalDescriptor);

public extern "C" MDLVertexDescriptor MTKModelIOVertexDescriptorFromMetalWithError(MTLVertexDescriptor metalDescriptor, void** error);

public extern "C" MTLVertexDescriptor? MTKMetalVertexDescriptorFromModelIO(MDLVertexDescriptor modelIODescriptor);

public extern "C" MTLVertexDescriptor? MTKMetalVertexDescriptorFromModelIOWithError(MDLVertexDescriptor modelIODescriptor, void** error);

public extern "C" MDLVertexFormat MTKModelIOVertexFormatFromMetal(MTLVertexFormat vertexFormat);

public extern "C" MTLVertexFormat MTKMetalVertexFormatFromModelIO(MDLVertexFormat vertexFormat);

#endif
