// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreData.framework (NSPersistentCloudKitContainer.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreData;

import MacOS.CloudKit;
import MacOS.Foundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CoreData")

[Flags]
public enum NSPersistentCloudKitContainerSchemaInitializationOptions : ulong
{
    None = 0,
    DryRun = 2,
    PrintSchema = 4,
}

public extern objc class NSPersistentCloudKitContainer : NSPersistentContainer
{
    [Selector("initializeCloudKitSchemaWithOptions:error:")]
    public bool InitializeCloudKitSchemaWithOptionsError(NSPersistentCloudKitContainerSchemaInitializationOptions options, out NSError? error);
    [Selector("recordForManagedObjectID:")]
    public CKRecord? RecordForManagedObjectID(NSManagedObjectID managedObjectID);
    [Selector("recordsForManagedObjectIDs:")]
    public NSDictionary RecordsForManagedObjectIDs(NSArray managedObjectIDs);
    [Selector("recordIDForManagedObjectID:")]
    public CKRecordID? RecordIDForManagedObjectID(NSManagedObjectID managedObjectID);
    [Selector("recordIDsForManagedObjectIDs:")]
    public NSDictionary RecordIDsForManagedObjectIDs(NSArray managedObjectIDs);
    [Selector("canUpdateRecordForManagedObjectWithID:")]
    public bool CanUpdateRecordForManagedObjectWithID(NSManagedObjectID objectID);
    [Selector("canDeleteRecordForManagedObjectWithID:")]
    public bool CanDeleteRecordForManagedObjectWithID(NSManagedObjectID objectID);
    [Selector("canModifyManagedObjectsInStore:")]
    public bool CanModifyManagedObjectsInStore(NSPersistentStore store);
}

#endif
