// Stainless - an experimental systems language.
// Copyright (C) 2026 Brandon Scott
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Text;
using Stainless.Binding;
using Stainless.Syntax;

namespace Stainless.Emit;

/// <summary>
/// Writes a C header describing a shared library's exported surface.
///
/// This is possible only because a Stainless <c>struct</c> is a C struct and an
/// <c>export "C"</c> function uses the platform C convention: the header is a
/// restatement of what is already true, not a marshalling layer.
/// </summary>
public static class CHeaderWriter
{
    public static string Write(BoundProgram program, string headerPath)
    {
        var exports = program.Modules
            .SelectMany(m => m.Functions)
            .Where(f => f.Linkage == LinkageKind.ExportC)
            .GroupBy(f => f.Name, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(f => f.Name, StringComparer.Ordinal)
            .ToList();

        // Only the named types an export actually mentions, in an order C accepts.
        var named = new List<NamedTypeSymbol>();
        var seen = new HashSet<NamedTypeSymbol>();
        foreach (var function in exports)
        {
            Collect(function.ReturnType, named, seen);
            foreach (var parameter in function.Parameters) Collect(parameter.Type, named, seen);
        }

        string guard = GuardName(headerPath);
        var sb = new StringBuilder();

        sb.AppendLine("/*");
        sb.AppendLine(" * Generated by the Stainless compiler. Do not edit.");
        sb.AppendLine(" *");
        sb.AppendLine(" * Declares the exported surface of this library. The types below are the");
        sb.AppendLine(" * same bytes Stainless uses, so nothing here marshals or converts.");
        sb.AppendLine(" */");
        sb.AppendLine();
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine("#include <stdbool.h>");
        sb.AppendLine("#include <stddef.h>");
        sb.AppendLine("#include <stdint.h>");

        // char16_t and char32_t are keywords in C++ and typedefs in C, and the
        // C header that defines them is one C++ must not include.
        if (MentionsWideChar(exports, named))
        {
            sb.AppendLine("#ifndef __cplusplus");
            sb.AppendLine("#include <uchar.h>");
            sb.AppendLine("#endif");
        }

        sb.AppendLine();
        sb.AppendLine("#ifdef __cplusplus");
        sb.AppendLine("extern \"C\" {");
        sb.AppendLine("#endif");
        sb.AppendLine();

        // [Align(N)] has no portable spelling, and the two that exist go in the
        // same place: after the `struct` keyword, where both compilers take it.
        if (named.Any(t => t is StructTypeSymbol { RequestedAlignment: not null }))
        {
            sb.AppendLine("#if defined(_MSC_VER)");
            sb.AppendLine("#define SL_ALIGN(n) __declspec(align(n))");
            sb.AppendLine("#else");
            sb.AppendLine("#define SL_ALIGN(n) __attribute__((aligned(n)))");
            sb.AppendLine("#endif");
            sb.AppendLine();
        }

        foreach (var type in named)
        {
            // The type a nameless member became is written inside its parent,
            // where the source wrote it, so it gets no typedef of its own.
            if (AnonymousMembers.IsGenerated(type)) continue;

            switch (type)
            {
                // A variant is a tag and enough bytes for the widest case. Its
                // two fields are spelled with a character C has no use for, and
                // the cases overlap in a way a C struct cannot state, so the
                // shape is written out rather than the fields copied across.
                case VariantTypeSymbol variant:
                    sb.AppendLine($"/* variant {variant.QualifiedName}:");
                    foreach (var variantCase in variant.Cases)
                        sb.AppendLine($"     {variantCase.Tag} = {variantCase.Signature}");
                    sb.AppendLine("   The payload is that case's fields, laid out as a struct.");
                    sb.AppendLine("   Read it by checking the tag first; there is no other way. */");
                    sb.AppendLine($"typedef struct {CName(variant)} {{");
                    sb.AppendLine("    uint8_t tag;");
                    // As an array of the integer the payload is aligned to,
                    // rather than of bytes with an alignment attribute: this
                    // spelling is the same in C and in C++, and the two of them
                    // do not share one for alignment.
                    if (variant.PayloadStorage is { Fields.Count: > 0 } storage)
                    {
                        sb.AppendLine($"    {TypeName(storage.Fields[0].Type)} " +
                                      $"payload[{storage.Fields.Count}];");
                    }
                    sb.AppendLine($"}} {CName(variant)};");
                    break;

                // A union is a union: C has the shape already, and every
                // member is where Stainless put it, which is offset zero.
                case UnionTypeSymbol union:
                {
                    if (union.IsPacked) sb.AppendLine("#pragma pack(push, 1)");

                    string unionAlign = union.RequestedAlignment is { } unionBytes
                        ? $"SL_ALIGN({unionBytes}) "
                        : "";

                    sb.AppendLine($"typedef union {unionAlign}{CName(union)} {{");
                    WriteFields(sb, union, "    ");
                    sb.AppendLine($"}} {CName(union)};");

                    if (union.IsPacked) sb.AppendLine("#pragma pack(pop)");
                    break;
                }

                // An incomplete type, written as C writes one. There is no
                // typedef, because the whole point is that nobody here knows
                // what it holds -- a `typedef struct X { } X;` would hand C a
                // one-byte struct where the real thing is something else.
                case StructTypeSymbol { IsOpaque: true } opaque:
                    sb.AppendLine($"struct {CName(opaque)};");
                    break;

                case StructTypeSymbol structType:
                {
                    // `#pragma pack` rather than an attribute: it is the one
                    // spelling MSVC, gcc and clang all take, and it says the
                    // same thing to each of them.
                    if (structType.IsPacked) sb.AppendLine("#pragma pack(push, 1)");

                    string aligned = structType.RequestedAlignment is { } bytes
                        ? $"SL_ALIGN({bytes}) "
                        : "";

                    sb.AppendLine($"typedef struct {aligned}{CName(structType)} {{");
                    WriteFields(sb, structType, "    ");
                    sb.AppendLine($"}} {CName(structType)};");

                    if (structType.IsPacked) sb.AppendLine("#pragma pack(pop)");
                    break;
                }

                // A C enum has an implementation-defined width, so the constants
                // and the type are declared separately: the constants as an
                // anonymous enum, the type as the integer Stainless actually uses.
                case EnumTypeSymbol enumType:
                    sb.AppendLine($"typedef {TypeName(enumType.UnderlyingType)} {CName(enumType)};");
                    if (enumType.Members.Count > 0)
                    {
                        sb.AppendLine("enum {");
                        foreach (var member in enumType.Members)
                            sb.AppendLine($"    {CName(enumType)}_{member.Name} = {member.Value},");
                        sb.AppendLine("};");
                    }
                    break;

                case DelegateTypeSymbol delegateType:
                    var signature = delegateType.Signature.Count == 0
                        ? "void"
                        : string.Join(", ", delegateType.Signature.Select(Declarator));
                    sb.AppendLine(
                        $"typedef {TypeName(delegateType.ReturnType)} " +
                        $"(*{CName(delegateType)})({signature});");
                    break;
            }

            sb.AppendLine();
        }

        if (exports.Count == 0)
        {
            sb.AppendLine("/* This library exports nothing. Mark a function 'export \"C\"'. */");
            sb.AppendLine();
        }

        // A public alias, written as the typedef it is. Signatures below still
        // spell the underlying type, because the header states the ABI and an
        // alias is a name rather than a type; these are here so C code can say
        // `App_HWND` where the Stainless source says `HWND`.
        var aliases = program.Modules
            .SelectMany(m => m.Aliases.Values)
            .Where(a => a.IsPublic && a.Target is not null && !a.Target.IsError())
            .OrderBy(a => a.QualifiedName, StringComparer.Ordinal)
            .ToList();

        if (aliases.Count > 0)
        {
            foreach (var alias in aliases)
                sb.AppendLine($"typedef {Declarator(alias.Target!, CName(alias))};");
            sb.AppendLine();
        }

        foreach (var function in exports)
        {
            var parameters = function.Parameters
                .Where(p => !p.IsThis)
                .Select(Declarator)
                .ToList();

            // No '...' here: an exported function cannot be variadic (SL0493),
            // precisely so that this header never promises a convention the
            // definition does not use.
            string list = parameters.Count == 0 ? "void" : string.Join(", ", parameters);

            sb.AppendLine($"{TypeName(function.ReturnType)} {function.Name}({list});");
        }

        sb.AppendLine();
        sb.AppendLine("#ifdef __cplusplus");
        sb.AppendLine("}");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine($"#endif /* {guard} */");
        return sb.ToString();
    }

    /// <summary>
    /// Gathers the named types an export mentions, depth first, so anything a
    /// declaration depends on is written before the declaration itself.
    /// </summary>
    /// <summary>
    /// Whether char16 or char32 appears anywhere the header will spell out.
    ///
    /// <see cref="Collect"/> has already walked every exported signature into
    /// <paramref name="named"/>, so between the two lists every type the header
    /// writes is reachable from here without walking the program again.
    /// </summary>
    private static bool MentionsWideChar(
        IReadOnlyList<FunctionSymbol> exports, IReadOnlyList<NamedTypeSymbol> named)
    {
        static bool Wide(TypeSymbol type) => Bare(type) is
            PrimitiveTypeSymbol { Kind: PrimitiveKind.Char16 or PrimitiveKind.Char32 };

        static TypeSymbol Bare(TypeSymbol type) => type switch
        {
            PointerTypeSymbol pointer => Bare(pointer.Element),
            FixedArrayTypeSymbol fixedArray => Bare(fixedArray.Element),
            _ => type,
        };

        foreach (var function in exports)
        {
            if (Wide(function.ReturnType)) return true;
            if (function.Parameters.Any(p => Wide(p.Type))) return true;
        }

        foreach (var type in named)
        {
            if (type.Fields.Any(f => Wide(f.Type))) return true;
            if (type is DelegateTypeSymbol signature &&
                (Wide(signature.ReturnType) || signature.Signature.Any(p => Wide(p.Type))))
                return true;
        }

        return false;
    }

    private static void Collect(
        TypeSymbol type, List<NamedTypeSymbol> ordered, HashSet<NamedTypeSymbol> seen)
    {
        switch (type)
        {
            case VariantTypeSymbol variant when seen.Add(variant):
                ordered.Add(variant);
                break;

            case UnionTypeSymbol union when seen.Add(union):
                foreach (var member in union.Fields) Collect(member.Type, ordered, seen);
                ordered.Add(union);
                break;

            case StructTypeSymbol { IsOpaque: true } opaque when seen.Add(opaque):
                ordered.Add(opaque);
                break;

            case StructTypeSymbol structType when seen.Add(structType):
                foreach (var field in structType.Fields) Collect(field.Type, ordered, seen);
                ordered.Add(structType);
                break;

            case EnumTypeSymbol enumType when seen.Add(enumType):
                ordered.Add(enumType);
                break;

            case DelegateTypeSymbol delegateType when seen.Add(delegateType):
                Collect(delegateType.ReturnType, ordered, seen);
                foreach (var parameter in delegateType.Signature)
                    Collect(parameter.Type, ordered, seen);
                ordered.Add(delegateType);
                break;

            case PointerTypeSymbol pointer:
                Collect(pointer.Element, ordered, seen);
                break;
        }
    }

    private static string GuardName(string headerPath)
    {
        string name = Path.GetFileName(headerPath);
        var guard = new string(name.Select(c => char.IsLetterOrDigit(c) ? char.ToUpperInvariant(c) : '_')
            .ToArray());
        return char.IsDigit(guard.FirstOrDefault()) ? "H_" + guard : guard;
    }

    private static string CName(NamedTypeSymbol type) => Mangler.SymbolSafe(type.QualifiedName);
    private static string CName(AliasSymbol alias) => Mangler.SymbolSafe(alias.QualifiedName);

    /// <summary>A C declaration of <paramref name="name"/> with the given type.</summary>
    /// <summary>
    /// The members of a struct or union, one per line.
    ///
    /// A field that came from a nameless <c>struct { }</c> or <c>union { }</c>
    /// is written back as one, nested where it was written: C11 has anonymous
    /// members, so the header can say exactly what the source said rather than
    /// naming something the source did not.
    /// </summary>
    private static void WriteFields(StringBuilder sb, NamedTypeSymbol type, string indent)
    {
        foreach (var field in type.Fields)
        {
            if (field.IsAnonymous && field.Type is NamedTypeSymbol inner)
            {
                sb.AppendLine($"{indent}{(inner is UnionTypeSymbol ? "union" : "struct")} {{");
                WriteFields(sb, inner, indent + "    ");
                sb.AppendLine($"{indent}}};");
                continue;
            }

            sb.AppendLine($"{indent}{Declarator(field.Type, field.Name)}" +
                          (field.BitWidth is { } bits ? $" : {bits}" : "") + ";");
        }
    }

    /// <summary>
    /// A field or parameter as C declares it.
    ///
    /// C writes an array's length after the name rather than after the type, and
    /// nested lengths outermost-first, so `int[3][2]` here is `int32_t x[2][3]`
    /// there. Threading the name through the recursion is what gets that order
    /// right without a second pass.
    /// </summary>
    private static string Declarator(TypeSymbol type, string name) => type switch
    {
        FixedArrayTypeSymbol inline => Declarator(inline.Element, $"{name}[{inline.Length}]"),
        _ => $"{TypeName(type)} {name}",
    };

    /// <summary>
    /// A parameter as C sees it. A <c>ref T</c> is a <c>T*</c> and an <c>in T</c>
    /// a <c>const T*</c>, which is not a translation so much as a restatement:
    /// that is exactly what the two are at the ABI, and the <c>const</c> says in
    /// C what the mode says here.
    /// </summary>
    private static string Declarator(ParameterSymbol parameter) => parameter.Mode switch
    {
        ParameterMode.Ref => $"{TypeName(parameter.Type)}* {parameter.Name}",
        ParameterMode.In => $"const {TypeName(parameter.Type)}* {parameter.Name}",
        _ => Declarator(parameter.Type, parameter.Name),
    };

    private static string TypeName(TypeSymbol type) => type switch
    {
        PrimitiveTypeSymbol primitive => primitive.Kind switch
        {
            PrimitiveKind.Void => "void",
            PrimitiveKind.Bool => "bool",
            PrimitiveKind.Char => "char",
            PrimitiveKind.Char16 => "char16_t",
            PrimitiveKind.Char32 => "char32_t",
            PrimitiveKind.SByte => "int8_t",
            PrimitiveKind.Short => "int16_t",
            PrimitiveKind.Int => "int32_t",
            PrimitiveKind.Long => "int64_t",
            PrimitiveKind.NInt => "intptr_t",
            PrimitiveKind.Byte => "uint8_t",
            PrimitiveKind.UShort => "uint16_t",
            PrimitiveKind.UInt => "uint32_t",
            PrimitiveKind.ULong => "uint64_t",
            PrimitiveKind.NUInt => "size_t",
            PrimitiveKind.Float => "float",
            _ => "double",
        },

        PointerTypeSymbol pointer => TypeName(pointer.Element) + "*",

        // No typedef exists for an incomplete type, so it is named by its tag.
        StructTypeSymbol { IsOpaque: true } opaque => "struct " + CName(opaque),

        VariantTypeSymbol variant => CName(variant),
        UnionTypeSymbol union => CName(union),
        StructTypeSymbol structType => CName(structType),

        // An enum is its underlying integer, and a delegate is a function
        // pointer; both are typedef'd above, so the name is enough here.
        EnumTypeSymbol enumType => CName(enumType),
        DelegateTypeSymbol delegateType => CName(delegateType),

        // A managed reference has no C spelling. It crosses as an opaque handle,
        // which the caller must not free or dereference.
        _ => "void*",
    };
}
