// Stainless - an experimental systems language.
// Copyright (C) 2026 Brandon Scott
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Text;
using Stainless.Binding;
using Stainless.Syntax;

namespace Stainless.Emit;

/// <summary>
/// Writes a C header describing a shared library's exported surface.
///
/// This is possible only because a Stainless <c>struct</c> is a C struct and an
/// <c>export "C"</c> function uses the platform C convention: the header is a
/// restatement of what is already true, not a marshalling layer.
/// </summary>
public static class CHeaderWriter
{
    public static string Write(BoundProgram program, string headerPath)
    {
        var exports = program.Modules
            .SelectMany(m => m.Functions)
            .Where(f => f.Linkage == LinkageKind.ExportC)
            .GroupBy(f => f.Name, StringComparer.Ordinal)
            .Select(g => g.First())
            .OrderBy(f => f.Name, StringComparer.Ordinal)
            .ToList();

        // Only the named types an export actually mentions, in an order C accepts.
        var named = new List<NamedTypeSymbol>();
        var seen = new HashSet<NamedTypeSymbol>();
        foreach (var function in exports)
        {
            Collect(function.ReturnType, named, seen);
            foreach (var parameter in function.Parameters) Collect(parameter.Type, named, seen);
        }

        string guard = GuardName(headerPath);
        var sb = new StringBuilder();

        sb.AppendLine("/*");
        sb.AppendLine(" * Generated by the Stainless compiler. Do not edit.");
        sb.AppendLine(" *");
        sb.AppendLine(" * Declares the exported surface of this library. The types below are the");
        sb.AppendLine(" * same bytes Stainless uses, so nothing here marshals or converts.");
        sb.AppendLine(" */");
        sb.AppendLine();
        sb.AppendLine($"#ifndef {guard}");
        sb.AppendLine($"#define {guard}");
        sb.AppendLine();
        sb.AppendLine("#include <stdbool.h>");
        sb.AppendLine("#include <stddef.h>");
        sb.AppendLine("#include <stdint.h>");
        sb.AppendLine();
        sb.AppendLine("#ifdef __cplusplus");
        sb.AppendLine("extern \"C\" {");
        sb.AppendLine("#endif");
        sb.AppendLine();

        foreach (var type in named)
        {
            switch (type)
            {
                case StructTypeSymbol structType:
                    sb.AppendLine($"typedef struct {CName(structType)} {{");
                    foreach (var field in structType.Fields)
                        sb.AppendLine($"    {Declarator(field.Type, field.Name)};");
                    sb.AppendLine($"}} {CName(structType)};");
                    break;

                // A C enum has an implementation-defined width, so the constants
                // and the type are declared separately: the constants as an
                // anonymous enum, the type as the integer Stainless actually uses.
                case EnumTypeSymbol enumType:
                    sb.AppendLine($"typedef {TypeName(enumType.UnderlyingType)} {CName(enumType)};");
                    if (enumType.Members.Count > 0)
                    {
                        sb.AppendLine("enum {");
                        foreach (var member in enumType.Members)
                            sb.AppendLine($"    {CName(enumType)}_{member.Name} = {member.Value},");
                        sb.AppendLine("};");
                    }
                    break;

                case DelegateTypeSymbol delegateType:
                    var signature = delegateType.Signature.Count == 0
                        ? "void"
                        : string.Join(", ", delegateType.Signature.Select(p => Declarator(p.Type, p.Name)));
                    sb.AppendLine(
                        $"typedef {TypeName(delegateType.ReturnType)} " +
                        $"(*{CName(delegateType)})({signature});");
                    break;
            }

            sb.AppendLine();
        }

        if (exports.Count == 0)
        {
            sb.AppendLine("/* This library exports nothing. Mark a function 'export \"C\"'. */");
            sb.AppendLine();
        }

        foreach (var function in exports)
        {
            var parameters = function.Parameters
                .Where(p => !p.IsThis)
                .Select(p => Declarator(p.Type, p.Name))
                .ToList();

            if (function.IsVariadic) parameters.Add("...");
            string list = parameters.Count == 0 ? "void" : string.Join(", ", parameters);

            sb.AppendLine($"{TypeName(function.ReturnType)} {function.Name}({list});");
        }

        sb.AppendLine();
        sb.AppendLine("#ifdef __cplusplus");
        sb.AppendLine("}");
        sb.AppendLine("#endif");
        sb.AppendLine();
        sb.AppendLine($"#endif /* {guard} */");
        return sb.ToString();
    }

    /// <summary>
    /// Gathers the named types an export mentions, depth first, so anything a
    /// declaration depends on is written before the declaration itself.
    /// </summary>
    private static void Collect(
        TypeSymbol type, List<NamedTypeSymbol> ordered, HashSet<NamedTypeSymbol> seen)
    {
        switch (type)
        {
            case StructTypeSymbol structType when seen.Add(structType):
                foreach (var field in structType.Fields) Collect(field.Type, ordered, seen);
                ordered.Add(structType);
                break;

            case EnumTypeSymbol enumType when seen.Add(enumType):
                ordered.Add(enumType);
                break;

            case DelegateTypeSymbol delegateType when seen.Add(delegateType):
                Collect(delegateType.ReturnType, ordered, seen);
                foreach (var parameter in delegateType.Signature)
                    Collect(parameter.Type, ordered, seen);
                ordered.Add(delegateType);
                break;

            case PointerTypeSymbol pointer:
                Collect(pointer.Element, ordered, seen);
                break;
        }
    }

    private static string GuardName(string headerPath)
    {
        string name = Path.GetFileName(headerPath);
        var guard = new string(name.Select(c => char.IsLetterOrDigit(c) ? char.ToUpperInvariant(c) : '_')
            .ToArray());
        return char.IsDigit(guard.FirstOrDefault()) ? "H_" + guard : guard;
    }

    private static string CName(NamedTypeSymbol type) => Mangler.SymbolSafe(type.QualifiedName);

    /// <summary>A C declaration of <paramref name="name"/> with the given type.</summary>
    private static string Declarator(TypeSymbol type, string name) => $"{TypeName(type)} {name}";

    private static string TypeName(TypeSymbol type) => type switch
    {
        PrimitiveTypeSymbol primitive => primitive.Kind switch
        {
            PrimitiveKind.Void => "void",
            PrimitiveKind.Bool => "bool",
            PrimitiveKind.Char => "char",
            PrimitiveKind.SByte => "int8_t",
            PrimitiveKind.Short => "int16_t",
            PrimitiveKind.Int => "int32_t",
            PrimitiveKind.Long => "int64_t",
            PrimitiveKind.NInt => "intptr_t",
            PrimitiveKind.Byte => "uint8_t",
            PrimitiveKind.UShort => "uint16_t",
            PrimitiveKind.UInt => "uint32_t",
            PrimitiveKind.ULong => "uint64_t",
            PrimitiveKind.NUInt => "size_t",
            PrimitiveKind.Float => "float",
            _ => "double",
        },

        PointerTypeSymbol pointer => TypeName(pointer.Element) + "*",
        StructTypeSymbol structType => CName(structType),

        // An enum is its underlying integer, and a delegate is a function
        // pointer; both are typedef'd above, so the name is enough here.
        EnumTypeSymbol enumType => CName(enumType),
        DelegateTypeSymbol delegateType => CName(delegateType),

        // A managed reference has no C spelling. It crosses as an opaque handle,
        // which the caller must not free or dereference.
        _ => "void*",
    };
}
