// Stainless - an experimental systems language.
// Copyright (C) 2026 Brandon Scott
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Globalization;
using System.Text;
using Stainless.Binding;
using Stainless.Syntax;

namespace Stainless.Emit;

/// <summary>
/// The scaffolding a module needs before a single function is written:
/// the target triple, the struct types, and every declaration of
/// something defined elsewhere.
///
/// The ABI coercion helpers are here because they decide what an
/// external declaration says, and a declaration must agree with the
/// call sites exactly.
/// </summary>
public sealed partial class LlvmEmitter
{
    // ============================================================ module scaffolding

    private void Header()
    {
        _module.AppendLine("; Generated by the Stainless compiler.");
        _module.AppendLine("; The target triple and data layout are left to clang so that this");
        _module.AppendLine("; file stays valid for whichever host toolchain compiles it.");
        _module.AppendLine();
    }

    private void StructTypes(BoundProgram program)
    {
        // Declared structs and instantiated generic ones both, which is why this
        // reads the program's list rather than walking the module type tables:
        // `Pair<int>` is in no module's table.
        var structs = program.Structs.Distinct().ToList();

        foreach (var structType in structs)
        {
            // An opaque type has no layout to state and nothing to state it
            // for: every use of one is a pointer, and a pointer is `ptr`.
            // Emitting `{ i8 }` would be a claim about a size nobody knows.
            if (structType.IsOpaque) continue;

            // A union's members overlap, and LLVM has no union type. What it is
            // given is storage of the right size and alignment -- as many
            // integers of the alignment as it takes to cover the widest member
            // -- and every member is read from the union's own address, which is
            // where all of them start.
            // A struct with bit-fields is storage too. Its fields do not line up
            // with LLVM's, because several of them share one, so there is nothing
            // to describe field by field; every access is a byte offset instead.
            if (structType is not UnionTypeSymbol && HasBitFields(structType))
            {
                _module.AppendLine(
                    $"{StructName(structType)} = type {{ [{Math.Max(1, structType.Size)} x i8] }}");
                if (structType.Alignment > 1)
                    _structAlignment[StructName(structType)] = structType.Alignment;
                continue;
            }

            if (structType is UnionTypeSymbol union)
            {
                int element = Math.Max(1, union.Alignment);
                int count = Math.Max(1, union.Size / element);
                _module.AppendLine(
                    $"{StructName(union)} = type {{ [{count} x i{element * 8}] }}");
                if (union.Alignment > 1) _structAlignment[StructName(union)] = union.Alignment;
                continue;
            }

            string fields = string.Join(", ", structType.Fields.Select(f => LlvmTypeOf(f.Type)));
            if (fields.Length == 0) fields = "i8";

            // A packed struct is spelled `<{ }>`, which is how LLVM is told to
            // put the fields where the C rules with no padding put them. Without
            // it LLVM would insert its own and every offset after the first
            // would disagree with the one the binder computed.
            _module.AppendLine(structType.IsPacked
                ? $"{StructName(structType)} = type <{{ {fields} }}>"
                : $"{StructName(structType)} = type {{ {fields} }}");

            // Alignment is not part of an LLVM struct type; it is stated at each
            // alloca and each global. So it is remembered here, by name, for the
            // places that have only the name to go on.
            if (structType.Alignment > 1) _structAlignment[StructName(structType)] = structType.Alignment;
        }

        // The header every reference type is prefixed with: strong, weak, TypeInfo*.
        _module.AppendLine("%SlObjectHeader = type { i64, i64, ptr }");
        // size, destroy, name, interfaces, fieldCount, fields, attributeCount,
        // attributes, base, vtable, com. The last three are appended rather
        // than inserted so that every offset the emitter already hard-codes --
        // the interface table at 24, above all -- goes on meaning what it meant.
        _module.AppendLine(
            "%SlTypeInfo = type { i64, ptr, ptr, ptr, i64, ptr, i64, ptr, ptr, ptr, ptr }");
        _module.AppendLine("%SlFieldInfo = type { ptr, i64, i32, ptr, i64, ptr }");
        _module.AppendLine("%SlAttribute = type { ptr, i64, ptr }");
        _module.AppendLine("%SlAttributeValue = type { i32, i64, ptr }");
        _module.AppendLine();
    }

    /// <summary>
    /// Symbols this module has already declared. The standard library declares
    /// some runtime entry points itself with <c>extern "C"</c>, and LLVM rejects
    /// a second declaration of the same name.
    /// </summary>
    private readonly HashSet<string> _declared = new(StringComparer.Ordinal);

    private void Declare(string name, string signature)
    {
        if (!_declared.Add(name)) return;
        _module.AppendLine(signature);
    }

    /// <summary>
    /// What the optimiser is allowed to assume about a runtime call.
    ///
    /// A bare <c>declare</c> is the most pessimistic thing LLVM can be told: a
    /// call that may unwind, may not return, and may read and write every byte
    /// the program can reach. Every reference-counting call is therefore a
    /// barrier -- a load cannot move across one, a loop containing one cannot
    /// be vectorised -- and hello-world makes 844 of them.
    ///
    /// These say what is actually true, and no more than that. Each is read off
    /// <c>runtime/arc.c</c> rather than assumed, because an attribute that
    /// overstates is not a missed optimisation but a miscompilation:
    ///
    /// <list type="bullet">
    /// <item><c>nounwind</c> everywhere: the language has no unwinding at all.
    /// A failure aborts through <c>sl_fail</c>.</item>
    /// <item><c>memory(argmem: readwrite)</c> only where the body provably
    /// touches nothing but the header of the object it was handed.</item>
    /// <item><c>noalias</c> on the allocators, which return fresh
    /// <c>calloc</c> memory that by definition aliases nothing.</item>
    /// </list>
    ///
    /// The two that look like they belong here and do not:
    /// <c>sl_release</c> runs <c>type->destroy</c>, an arbitrary user
    /// destructor that may touch anything and call anything, and the COM pair
    /// makes an indirect call into foreign code. Giving either a memory clause
    /// would be wrong, so neither has one.
    /// </summary>
    private const string HeaderOnly = "nounwind willreturn memory(argmem: readwrite)";

    private void RuntimeDeclarations()
    {
        // Fresh memory from calloc: noalias is what makes it worth saying.
        // Not `willreturn` -- both abort through sl_fail when they cannot
        // allocate, and sl_fail does not come back.
        Declare("sl_alloc", "declare noalias ptr @sl_alloc(ptr) nounwind");

        Declare("sl_retain", $"declare void @sl_retain(ptr) {HeaderOnly}");

        // No memory clause: this is the one that runs a destructor.
        Declare("sl_release", "declare void @sl_release(ptr) nounwind");

        Declare("sl_make_immortal", $"declare void @sl_make_immortal(ptr) {HeaderOnly}");
        Declare("sl_weak_retain", $"declare void @sl_weak_retain(ptr) {HeaderOnly}");

        // free() touches the allocator's own bookkeeping, which is reachable
        // from neither the argument nor a global -- that is what
        // inaccessiblemem names. It still touches nothing else.
        Declare("sl_weak_release",
            "declare void @sl_weak_release(ptr) nounwind willreturn " +
            "memory(argmem: readwrite, inaccessiblemem: readwrite)");

        // The header and nothing else, but through a compare-exchange loop, so
        // `willreturn` is left off: it retries until it wins.
        Declare("sl_weak_load",
            "declare ptr @sl_weak_load(ptr) nounwind memory(argmem: readwrite)");
        // The runtime's own tables. When it is a shared library on Windows
        // these are reached through the import address table, and only the
        // declaration can say so.
        string runtimeConstant = sharedRuntime && OperatingSystem.IsWindows()
            ? "external dllimport constant"
            : "external constant";

        Declare("sl_string_type_info",
            $"@sl_string_type_info = {runtimeConstant} %SlTypeInfo");
        Declare("sl_utf16_string_type_info",
            $"@sl_utf16_string_type_info = {runtimeConstant} %SlTypeInfo");
        Declare("sl_string_builder_type_info",
            $"@sl_string_builder_type_info = {runtimeConstant} %SlTypeInfo");
        Declare("sl_array_alloc",
            "declare noalias ptr @sl_array_alloc(ptr, i64, i64) nounwind");

        // The entry point hands the runtime what main() was given, and asks it
        // back as a String[] when Main declared one.
        Declare("sl_args_set", "declare void @sl_args_set(i32, ptr) nounwind");
        Declare("sl_args_array", "declare noalias ptr @sl_args_array(ptr) nounwind");

        // Reads type tables, which are constants in this module or the
        // runtime's. Neither writes anything.
        Declare("sl_is_instance",
            "declare i32 @sl_is_instance(ptr, ptr) nounwind willreturn memory(read)");
        Declare("sl_implements",
            "declare i32 @sl_implements(ptr, i64) nounwind willreturn memory(read)");

        // Ends the program, so the block after a call to one is unreachable and
        // LLVM may say so.
        Declare("sl_cast_failed", "declare void @sl_cast_failed(ptr, ptr) noreturn nounwind");
        Declare("sl_com_retain", "declare void @sl_com_retain(ptr)");
        Declare("sl_com_release", "declare void @sl_com_release(ptr)");
        Declare("sl_com_query", "declare ptr @sl_com_query(ptr, ptr)");
        Declare("sl_com_is", "declare i32 @sl_com_is(ptr, ptr)");
        Declare("sl_com_cast_failed",
            "declare void @sl_com_cast_failed(ptr, ptr) noreturn nounwind");
        Declare("sl_com_object_query",
            "declare i32 @sl_com_object_query(ptr, ptr, ptr)");
        Declare("sl_com_object_add_ref", "declare i32 @sl_com_object_add_ref(ptr)");
        Declare("sl_com_object_release", "declare i32 @sl_com_object_release(ptr)");
        // Every one of these ends in sl_fail, which ends in abort. Saying so is
        // what makes a bounds check's failure arm genuinely cold: the success
        // path stops being a branch that might come back.
        Declare("sl_array_bounds_fail",
            "declare void @sl_array_bounds_fail(i64, i64) noreturn nounwind");
        Declare("sl_slice_bounds_fail",
            "declare void @sl_slice_bounds_fail(i64, i64, i64) noreturn nounwind");
        Declare("sl_divide_by_zero",
            "declare void @sl_divide_by_zero() noreturn nounwind");
        Declare("sl_divide_overflow",
            "declare void @sl_divide_overflow() noreturn nounwind");
        Declare("llvm.memcpy.p0.p0.i64", "declare void @llvm.memcpy.p0.p0.i64(ptr, ptr, i64, i1)");

        // Up here rather than at its first use: a declaration goes straight into
        // the module, and the first use is inside an open function body.
        if (debug is not null)
            Declare("llvm.dbg.declare", "declare void @llvm.dbg.declare(metadata, metadata, metadata)");
        ConcurrencyDeclarations();
        _module.AppendLine();
    }

    private void FactoryDeclarations(BoundProgram program)
    {
        foreach (string factory in program.RuntimeFactories)
            Declare(factory, $"declare ptr @{factory}()");

        if (program.RuntimeFactories.Count > 0) _module.AppendLine();
    }

    /// <summary>
    /// How one parameter is passed.
    ///
    /// A <c>ref</c> or <c>in</c> parameter is the caller's storage, so it is a
    /// pointer and the classifier is not consulted: there is nothing to
    /// classify, and a struct that would have gone <c>byval</c> must not be
    /// copied on the way in. That is the whole of the ABI change, and it makes
    /// such a parameter exactly a <c>T*</c> — which is why one crosses
    /// <c>extern "C"</c> with nothing in between.
    /// </summary>
    /// <summary>
    /// How one parameter is spelled in a declaration: its own type, a pointer
    /// it is passed behind, or one entry per register it travels in.
    /// </summary>
    private IEnumerable<string> Declared(ArgInfo info) =>
        info.Style switch
        {
            PassStyle.Indirect => [$"ptr byval({StructName((StructTypeSymbol)info.Type)})"],
            PassStyle.Coerce => info.Pieces,
            _ => [info.LlvmType],
        };

    /// <summary>
    /// The address of the eight bytes a coerced struct's <paramref name="index"/>
    /// register covers.
    ///
    /// Each piece is sized to what the value actually occupies there, so this
    /// plus that size never reaches past the object -- which is why a
    /// three-byte struct travels as an `i24` and not as an `i32` reading a
    /// fourth byte that does not exist.
    /// </summary>
    /// <summary>
    /// Reads a struct at <paramref name="address"/> as the value its ABI says
    /// it returns in: one register, or a struct of the two it uses.
    /// </summary>
    private string LoadCoerced(string address, ArgInfo info)
    {
        if (info.Pieces.Count <= 1)
            return Emit(info.LlvmType, $"load {info.LlvmType}, ptr {address}");

        string built = "undef";
        for (int piece = 0; piece < info.Pieces.Count; piece++)
        {
            string spelling = info.Pieces[piece];
            string loaded = Emit(spelling,
                $"load {spelling}, ptr {PieceAddress(address, piece)}");

            built = Emit(info.LlvmType,
                $"insertvalue {info.LlvmType} {built}, {spelling} {loaded}, {piece}");
        }
        return built;
    }

    /// <summary>Writes such a value back into an object, piece by piece.</summary>
    private void StoreCoerced(string address, string value, ArgInfo info)
    {
        if (info.Pieces.Count <= 1)
        {
            Line($"store {info.LlvmType} {value}, ptr {address}");
            return;
        }

        for (int piece = 0; piece < info.Pieces.Count; piece++)
        {
            string spelling = info.Pieces[piece];
            string part = Emit(spelling, $"extractvalue {info.LlvmType} {value}, {piece}");
            Line($"store {spelling} {part}, ptr {PieceAddress(address, piece)}");
        }
    }

    private string PieceAddress(string address, int index) =>
        index == 0
            ? address
            : Emit("ptr", $"getelementptr inbounds i8, ptr {address}, i64 {index * 8}");

    private ArgInfo ClassifyParameter(ParameterSymbol parameter) =>
        parameter.IsByReference
            ? new ArgInfo(PassStyle.Direct, "ptr", parameter.Type)
            : ClassifyValue(parameter.Type);

    private void ExternalDeclarations(BoundProgram program)
    {
        foreach (var function in program.ExternalFunctions)
        {
            var returnInfo = ClassifyResult(function.ReturnType);
            var parts = new List<string>();

            if (returnInfo.Style == PassStyle.Indirect)
                parts.Add($"ptr sret({StructName((StructTypeSymbol)function.ReturnType)})");

            foreach (var parameter in function.Parameters)
                parts.AddRange(Declared(ClassifyParameter(parameter)));

            if (function.IsVariadic) parts.Add("...");

            string returnType = returnInfo.Style == PassStyle.Indirect ? "void" : returnInfo.LlvmType;
            Declare(function.MangledName,
                $"declare {returnType} {Symbol(function)}({string.Join(", ", parts)})");
        }

        if (program.ExternalFunctions.Count > 0) _module.AppendLine();
    }
}
