// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AppKit.framework (NSSliderTouchBarItem.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AppKit;

import MacOS.CoreFoundation;
import MacOS.Foundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "AppKit")

public using NSSliderAccessoryWidth = CGFloat;

public extern "C" NSSliderAccessoryWidth NSSliderAccessoryWidthDefault;

public extern "C" NSSliderAccessoryWidth NSSliderAccessoryWidthWide;

public extern objc class NSSliderTouchBarItem : NSTouchBarItem
{
    [Selector("view")]
    public NSView? View { get; }
    [Selector("slider", "setSlider:")]
    public NSSlider? Slider { get; set; }
    [Selector("doubleValue", "setDoubleValue:")]
    public double DoubleValue { get; set; }
    [Selector("minimumSliderWidth", "setMinimumSliderWidth:")]
    public CGFloat MinimumSliderWidth { get; set; }
    [Selector("maximumSliderWidth", "setMaximumSliderWidth:")]
    public CGFloat MaximumSliderWidth { get; set; }
    [Selector("label", "setLabel:")]
    public NSString? Label { get; set; }
    [Selector("minimumValueAccessory", "setMinimumValueAccessory:")]
    public NSSliderAccessory? MinimumValueAccessory { get; set; }
    [Selector("maximumValueAccessory", "setMaximumValueAccessory:")]
    public NSSliderAccessory? MaximumValueAccessory { get; set; }
    [Selector("valueAccessoryWidth", "setValueAccessoryWidth:")]
    public NSSliderAccessoryWidth ValueAccessoryWidth { get; set; }
    [Selector("target", "setTarget:")]
    public AnyObject? Target { get; set; }
    [Selector("action", "setAction:")]
    public Selector Action { get; set; }
    [Selector("customizationLabel", "setCustomizationLabel:")]
    public NSString? CustomizationLabel { get; set; }
}

#endif
