// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AppKit.framework (NSTokenField.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AppKit;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "AppKit")

public objc interface NSTokenFieldDelegate : NSTextFieldDelegate
{
    [Optional] [Selector("tokenField:completionsForSubstring:indexOfToken:indexOfSelectedItem:")] NSArray? TokenFieldCompletionsForSubstringIndexOfTokenIndexOfSelectedItem(NSTokenField tokenField, NSString substring, NSInteger tokenIndex, NSInteger* selectedIndex);
    [Optional] [Selector("tokenField:shouldAddObjects:atIndex:")] NSArray TokenFieldShouldAddObjectsAtIndex(NSTokenField tokenField, NSArray tokens, NSUInteger index);
    [Optional] [Selector("tokenField:displayStringForRepresentedObject:")] NSString? TokenFieldDisplayStringForRepresentedObject(NSTokenField tokenField, AnyObject representedObject);
    [Optional] [Selector("tokenField:editingStringForRepresentedObject:")] NSString? TokenFieldEditingStringForRepresentedObject(NSTokenField tokenField, AnyObject representedObject);
    [Optional] [Selector("tokenField:representedObjectForEditingString:")] AnyObject? TokenFieldRepresentedObjectForEditingString(NSTokenField tokenField, NSString editingString);
    [Optional] [Selector("tokenField:writeRepresentedObjects:toPasteboard:")] bool TokenFieldWriteRepresentedObjectsToPasteboard(NSTokenField tokenField, NSArray objects, NSPasteboard pboard);
    [Optional] [Selector("tokenField:readFromPasteboard:")] NSArray? TokenFieldReadFromPasteboard(NSTokenField tokenField, NSPasteboard pboard);
    [Optional] [Selector("tokenField:menuForRepresentedObject:")] NSMenu? TokenFieldMenuForRepresentedObject(NSTokenField tokenField, AnyObject representedObject);
    [Optional] [Selector("tokenField:hasMenuForRepresentedObject:")] bool TokenFieldHasMenuForRepresentedObject(NSTokenField tokenField, AnyObject representedObject);
    [Optional] [Selector("tokenField:styleForRepresentedObject:")] NSTokenStyle TokenFieldStyleForRepresentedObject(NSTokenField tokenField, AnyObject representedObject);
}

public extern objc class NSTokenField : NSTextField
{
    [Selector("delegate", "setDelegate:")] public NSTokenFieldDelegate? Delegate { get; set; }
    [Selector("tokenStyle", "setTokenStyle:")] public NSTokenStyle TokenStyle { get; set; }
    [Selector("completionDelay", "setCompletionDelay:")] public NSTimeInterval CompletionDelay { get; set; }
    [Selector("defaultCompletionDelay")] public static NSTimeInterval DefaultCompletionDelay { get; }
    [Selector("tokenizingCharacterSet", "setTokenizingCharacterSet:")] public NSCharacterSet? TokenizingCharacterSet { get; set; }
    [Selector("defaultTokenizingCharacterSet")] public static NSCharacterSet DefaultTokenizingCharacterSet { get; }
}

#endif
