// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AppKit.framework (NSTypesetter.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AppKit;

import MacOS.CoreFoundation;
import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "AppKit")

public extern objc class NSTypesetter : NSObject
{
    [Selector("usesFontLeading", "setUsesFontLeading:")]
    public bool UsesFontLeading { get; set; }
    [Selector("typesetterBehavior", "setTypesetterBehavior:")]
    public NSTypesetterBehavior TypesetterBehavior { get; set; }
    [Selector("hyphenationFactor", "setHyphenationFactor:")]
    public float HyphenationFactor { get; set; }
    [Selector("lineFragmentPadding", "setLineFragmentPadding:")]
    public CGFloat LineFragmentPadding { get; set; }
    [Selector("bidiProcessingEnabled", "setBidiProcessingEnabled:")]
    public bool BidiProcessingEnabled { get; set; }
    [Selector("attributedString", "setAttributedString:")]
    public NSAttributedString? AttributedString { get; set; }
    [Selector("paragraphGlyphRange")]
    public NSRange ParagraphGlyphRange { get; }
    [Selector("paragraphSeparatorGlyphRange")]
    public NSRange ParagraphSeparatorGlyphRange { get; }
    [Selector("paragraphCharacterRange")]
    public NSRange ParagraphCharacterRange { get; }
    [Selector("paragraphSeparatorCharacterRange")]
    public NSRange ParagraphSeparatorCharacterRange { get; }
    [Selector("attributesForExtraLineFragment")]
    public NSDictionary AttributesForExtraLineFragment { get; }
    [Selector("layoutManager")]
    public NSLayoutManager? LayoutManager { get; }
    [Selector("textContainers")]
    public NSArray? TextContainers { get; }
    [Selector("currentTextContainer")]
    public NSTextContainer? CurrentTextContainer { get; }
    [Selector("currentParagraphStyle")]
    public NSParagraphStyle? CurrentParagraphStyle { get; }
    [Selector("sharedSystemTypesetter")]
    public static NSTypesetter SharedSystemTypesetter { get; }
    [Selector("defaultTypesetterBehavior")]
    public static NSTypesetterBehavior DefaultTypesetterBehavior { get; }
    [Selector("substituteFontForFont:")]
    public NSFont SubstituteFontForFont(NSFont originalFont);
    [Selector("textTabForGlyphLocation:writingDirection:maxLocation:")]
    public NSTextTab? TextTabForGlyphLocationWritingDirectionMaxLocation(CGFloat glyphLocation, NSWritingDirection direction, CGFloat maxLocation);
    [Selector("setParagraphGlyphRange:separatorGlyphRange:")]
    public void SetParagraphGlyphRangeSeparatorGlyphRange(NSRange paragraphRange, NSRange paragraphSeparatorRange);
    [Selector("layoutParagraphAtPoint:")]
    public NSUInteger LayoutParagraphAtPoint(NSPointPointer lineFragmentOrigin);
    [Selector("beginParagraph")]
    public void BeginParagraph();
    [Selector("endParagraph")]
    public void EndParagraph();
    [Selector("beginLineWithGlyphAtIndex:")]
    public void BeginLineWithGlyphAtIndex(NSUInteger glyphIndex);
    [Selector("endLineWithGlyphRange:")]
    public void EndLineWithGlyphRange(NSRange lineGlyphRange);
    [Selector("lineSpacingAfterGlyphAtIndex:withProposedLineFragmentRect:")]
    public CGFloat LineSpacingAfterGlyphAtIndexWithProposedLineFragmentRect(NSUInteger glyphIndex, NSRect rect);
    [Selector("paragraphSpacingBeforeGlyphAtIndex:withProposedLineFragmentRect:")]
    public CGFloat ParagraphSpacingBeforeGlyphAtIndexWithProposedLineFragmentRect(NSUInteger glyphIndex, NSRect rect);
    [Selector("paragraphSpacingAfterGlyphAtIndex:withProposedLineFragmentRect:")]
    public CGFloat ParagraphSpacingAfterGlyphAtIndexWithProposedLineFragmentRect(NSUInteger glyphIndex, NSRect rect);
    [Selector("getLineFragmentRect:usedRect:forParagraphSeparatorGlyphRange:atProposedOrigin:")]
    public void GetLineFragmentRectUsedRectForParagraphSeparatorGlyphRangeAtProposedOrigin(NSRectPointer lineFragmentRect, NSRectPointer lineFragmentUsedRect, NSRange paragraphSeparatorGlyphRange, NSPoint lineOrigin);
    [Selector("setHardInvalidation:forGlyphRange:")]
    public void SetHardInvalidationForGlyphRange(bool flag, NSRange glyphRange);
    [Selector("layoutGlyphsInLayoutManager:startingAtGlyphIndex:maxNumberOfLineFragments:nextGlyphIndex:")]
    public void LayoutGlyphsInLayoutManagerStartingAtGlyphIndexMaxNumberOfLineFragmentsNextGlyphIndex(NSLayoutManager layoutManager, NSUInteger startGlyphIndex, NSUInteger maxNumLines, NSUInteger* nextGlyph);
    [Selector("layoutCharactersInRange:forLayoutManager:maximumNumberOfLineFragments:")]
    public NSRange LayoutCharactersInRangeForLayoutManagerMaximumNumberOfLineFragments(NSRange characterRange, NSLayoutManager layoutManager, NSUInteger maxNumLines);
    [Selector("printingAdjustmentInLayoutManager:forNominallySpacedGlyphRange:packedGlyphs:count:")]
    public static NSSize PrintingAdjustmentInLayoutManagerForNominallySpacedGlyphRangePackedGlyphsCount(NSLayoutManager layoutMgr, NSRange nominallySpacedGlyphsRange, byte* packedGlyphs, NSUInteger packedGlyphsCount);
    [Selector("baselineOffsetInLayoutManager:glyphIndex:")]
    public CGFloat BaselineOffsetInLayoutManagerGlyphIndex(NSLayoutManager layoutMgr, NSUInteger glyphIndex);
    [Selector("sharedSystemTypesetterForBehavior:")]
    public static AnyObject SharedSystemTypesetterForBehavior(NSTypesetterBehavior behavior);
}

/// NSLayoutPhaseInterface, a category of NSTypesetter.
public extern objc class NSTypesetter
{
    [Selector("willSetLineFragmentRect:forGlyphRange:usedRect:baselineOffset:")]
    public void WillSetLineFragmentRectForGlyphRangeUsedRectBaselineOffset(NSRectPointer lineRect, NSRange glyphRange, NSRectPointer usedRect, CGFloat* baselineOffset);
    [Selector("shouldBreakLineByWordBeforeCharacterAtIndex:")]
    public bool ShouldBreakLineByWordBeforeCharacterAtIndex(NSUInteger charIndex);
    [Selector("shouldBreakLineByHyphenatingBeforeCharacterAtIndex:")]
    public bool ShouldBreakLineByHyphenatingBeforeCharacterAtIndex(NSUInteger charIndex);
    [Selector("hyphenationFactorForGlyphAtIndex:")]
    public float HyphenationFactorForGlyphAtIndex(NSUInteger glyphIndex);
    [Selector("hyphenCharacterForGlyphAtIndex:")]
    public UTF32Char HyphenCharacterForGlyphAtIndex(NSUInteger glyphIndex);
    [Selector("boundingBoxForControlGlyphAtIndex:forTextContainer:proposedLineFragment:glyphPosition:characterIndex:")]
    public NSRect BoundingBoxForControlGlyphAtIndexForTextContainerProposedLineFragmentGlyphPositionCharacterIndex(NSUInteger glyphIndex, NSTextContainer textContainer, NSRect proposedRect, NSPoint glyphPosition, NSUInteger charIndex);
}

/// NSGlyphStorageInterface, a category of NSTypesetter.
public extern objc class NSTypesetter
{
    [Selector("characterRangeForGlyphRange:actualGlyphRange:")]
    public NSRange CharacterRangeForGlyphRangeActualGlyphRange(NSRange glyphRange, NSRangePointer actualGlyphRange);
    [Selector("glyphRangeForCharacterRange:actualCharacterRange:")]
    public NSRange GlyphRangeForCharacterRangeActualCharacterRange(NSRange charRange, NSRangePointer actualCharRange);
    [Selector("getLineFragmentRect:usedRect:remainingRect:forStartingGlyphAtIndex:proposedRect:lineSpacing:paragraphSpacingBefore:paragraphSpacingAfter:")]
    public void GetLineFragmentRectUsedRectRemainingRectForStartingGlyphAtIndexProposedRectLineSpacingParagraphSpacingBeforeParagraphSpacingAfter(NSRectPointer lineFragmentRect, NSRectPointer lineFragmentUsedRect, NSRectPointer remainingRect, NSUInteger startingGlyphIndex, NSRect proposedRect, CGFloat lineSpacing, CGFloat paragraphSpacingBefore, CGFloat paragraphSpacingAfter);
    [Selector("setLineFragmentRect:forGlyphRange:usedRect:baselineOffset:")]
    public void SetLineFragmentRectForGlyphRangeUsedRectBaselineOffset(NSRect fragmentRect, NSRange glyphRange, NSRect usedRect, CGFloat baselineOffset);
    [Selector("setNotShownAttribute:forGlyphRange:")]
    public void SetNotShownAttributeForGlyphRange(bool flag, NSRange glyphRange);
    [Selector("setDrawsOutsideLineFragment:forGlyphRange:")]
    public void SetDrawsOutsideLineFragmentForGlyphRange(bool flag, NSRange glyphRange);
    [Selector("setLocation:withAdvancements:forStartOfGlyphRange:")]
    public void SetLocationWithAdvancementsForStartOfGlyphRange(NSPoint location, CGFloat* advancements, NSRange glyphRange);
    [Selector("setAttachmentSize:forGlyphRange:")]
    public void SetAttachmentSizeForGlyphRange(NSSize attachmentSize, NSRange glyphRange);
    [Selector("setBidiLevels:forGlyphRange:")]
    public void SetBidiLevelsForGlyphRange(byte* levels, NSRange glyphRange);
}

[Flags]
public enum NSTypesetterControlCharacterAction : ulong
{
    ZeroAdvancementAction = 1,
    WhitespaceAction = 2,
    HorizontalTabAction = 4,
    LineBreakAction = 8,
    ParagraphBreakAction = 16,
    ContainerBreakAction = 32,
}

/// NSTypesetter_Deprecated, a category of NSTypesetter.
public extern objc class NSTypesetter
{
    [Selector("actionForControlCharacterAtIndex:")]
    public NSTypesetterControlCharacterAction ActionForControlCharacterAtIndex(NSUInteger charIndex);
    /// Deprecated in macOS 10.13.
    [Selector("getGlyphsInRange:glyphs:characterIndexes:glyphInscriptions:elasticBits:bidiLevels:")]
    public NSUInteger GetGlyphsInRangeGlyphsCharacterIndexesGlyphInscriptionsElasticBitsBidiLevels(NSRange glyphsRange, NSGlyph* glyphBuffer, NSUInteger* charIndexBuffer, NSGlyphInscription* inscribeBuffer, bool* elasticBuffer, byte* bidiLevelBuffer);
    /// Deprecated in macOS 10.13.
    [Selector("substituteGlyphsInRange:withGlyphs:")]
    public void SubstituteGlyphsInRangeWithGlyphs(NSRange glyphRange, NSGlyph* glyphs);
    /// Deprecated in macOS 10.13.
    [Selector("insertGlyph:atGlyphIndex:characterIndex:")]
    public void InsertGlyphAtGlyphIndexCharacterIndex(NSGlyph glyph, NSUInteger glyphIndex, NSUInteger characterIndex);
    /// Deprecated in macOS 10.13.
    [Selector("deleteGlyphsInRange:")]
    public void DeleteGlyphsInRange(NSRange glyphRange);
}

#endif
