// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from SystemConfiguration.framework (SCDynamicStoreKey.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.SystemConfiguration;

import MacOS.CoreFoundation;

#if MACOS

#pragma comment(framework, "SystemConfiguration")

public extern "C" CFStringRef SCDynamicStoreKeyCreate(CFAllocatorRef allocator, CFStringRef fmt, ...);

public extern "C" CFStringRef SCDynamicStoreKeyCreateNetworkGlobalEntity(CFAllocatorRef allocator, CFStringRef domain, CFStringRef entity);

public extern "C" CFStringRef SCDynamicStoreKeyCreateNetworkInterface(CFAllocatorRef allocator, CFStringRef domain);

public extern "C" CFStringRef SCDynamicStoreKeyCreateNetworkInterfaceEntity(CFAllocatorRef allocator, CFStringRef domain, CFStringRef ifname, CFStringRef entity);

public extern "C" CFStringRef SCDynamicStoreKeyCreateNetworkServiceEntity(CFAllocatorRef allocator, CFStringRef domain, CFStringRef serviceID, CFStringRef entity);

public extern "C" CFStringRef SCDynamicStoreKeyCreateComputerName(CFAllocatorRef allocator);

public extern "C" CFStringRef SCDynamicStoreKeyCreateConsoleUser(CFAllocatorRef allocator);

public extern "C" CFStringRef SCDynamicStoreKeyCreateHostNames(CFAllocatorRef allocator);

public extern "C" CFStringRef SCDynamicStoreKeyCreateLocation(CFAllocatorRef allocator);

public extern "C" CFStringRef SCDynamicStoreKeyCreateProxies(CFAllocatorRef allocator);

#endif
