// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from MLCompute.framework (MLCMultiheadAttentionDescriptor.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.MLCompute;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "MLCompute")

/// Deprecated in macOS 14.3.
public extern objc class MLCMultiheadAttentionDescriptor : NSObject, NSCopying
{
    [Selector("modelDimension")]
    public NSUInteger ModelDimension { get; }
    [Selector("keyDimension")]
    public NSUInteger KeyDimension { get; }
    [Selector("valueDimension")]
    public NSUInteger ValueDimension { get; }
    [Selector("headCount")]
    public NSUInteger HeadCount { get; }
    [Selector("dropout")]
    public float Dropout { get; }
    [Selector("hasBiases")]
    public bool HasBiases { get; }
    [Selector("hasAttentionBiases")]
    public bool HasAttentionBiases { get; }
    [Selector("addsZeroAttention")]
    public bool AddsZeroAttention { get; }
    [Selector("descriptorWithModelDimension:keyDimension:valueDimension:headCount:dropout:hasBiases:hasAttentionBiases:addsZeroAttention:")]
    public static Self? DescriptorWithModelDimensionKeyDimensionValueDimensionHeadCountDropoutHasBiasesHasAttentionBiasesAddsZeroAttention(NSUInteger modelDimension, NSUInteger keyDimension, NSUInteger valueDimension, NSUInteger headCount, float dropout, bool hasBiases, bool hasAttentionBiases, bool addsZeroAttention);
    [Selector("descriptorWithModelDimension:headCount:")]
    public static Self DescriptorWithModelDimensionHeadCount(NSUInteger modelDimension, NSUInteger headCount);
}

#endif
