// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreImage.framework (CIImageAccumulator.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreImage;

import MacOS.CoreFoundation;
import MacOS.CoreGraphics;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CoreImage")

public extern objc class CIImageAccumulator : NSObject
{
    [Selector("extent")] public CGRect Extent { get; }
    [Selector("format")] public CIFormat Format { get; }
    [Selector("imageAccumulatorWithExtent:format:")] public static Self? ImageAccumulatorWithExtentFormat(CGRect extent, CIFormat format);
    [Selector("imageAccumulatorWithExtent:format:colorSpace:")] public static Self? ImageAccumulatorWithExtentFormatColorSpace(CGRect extent, CIFormat format, CGColorSpaceRef colorSpace);
    [Selector("initWithExtent:format:")] public Self? InitWithExtentFormat(CGRect extent, CIFormat format);
    [Selector("initWithExtent:format:colorSpace:")] public Self? InitWithExtentFormatColorSpace(CGRect extent, CIFormat format, CGColorSpaceRef colorSpace);
    [Selector("image")] public CIImage Image();
    [Selector("setImage:")] public void SetImage(CIImage image);
    [Selector("setImage:dirtyRect:")] public void SetImageDirtyRect(CIImage image, CGRect dirtyRect);
    [Selector("clear")] public void Clear();
}

#endif
