// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from BackgroundAssets.framework (BAError.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.BackgroundAssets;

import MacOS.Foundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "BackgroundAssets")

/// macOS 14.0 and later.
public extern "C" NSString? BAErrorDomain;

/// macOS 14.0 and later.
public enum BAErrorCode : long
{
    DownloadInvalid = 0,
    CallFromExtensionNotAllowed = 50,
    CallFromInactiveProcessNotAllowed = 51,
    CallerConnectionNotAccepted = 55,
    CallerConnectionInvalid = 56,
    DownloadAlreadyScheduled = 100,
    DownloadNotScheduled = 101,
    DownloadFailedToStart = 102,
    DownloadAlreadyFailed = 103,
    DownloadEssentialDownloadNotPermitted = 109,
    DownloadBackgroundActivityProhibited = 111,
    DownloadWouldExceedAllowance = 112,
    DownloadDoesNotExist = 113,
    SessionDownloadDisallowedByDomain = 202,
    SessionDownloadDisallowedByAllowance = 203,
    SessionDownloadAllowanceExceeded = 204,
    SessionDownloadNotPermittedBeforeAppLaunch = 206,
}

#endif
