// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CompositorServices.framework (drawable.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CompositorServices;

import MacOS.ARKit;
import MacOS.Metal;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CompositorServices")

/// macOS 26.0 and later.
public enum cp_drawable_state : uint
{
    available = 0,
    rendering = 1,
    presenting = 2,
}

/// macOS 26.0 and later.
public enum cp_drawable_target : uint
{
    built_in = 0,
    capture = 1,
}

public struct cp_drawable;

/// macOS 26.0 and later.
public using cp_drawable_t = cp_drawable*;

/// macOS 26.0 and later.
public extern "C" nuint cp_drawable_get_texture_count(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" nuint cp_drawable_get_tracking_areas_texture_count(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" MTLTexture cp_drawable_get_depth_texture(cp_drawable_t drawable, nuint index);

/// macOS 26.0 and later.
public extern "C" MTLTexture cp_drawable_get_color_texture(cp_drawable_t drawable, nuint index);

/// macOS 26.0 and later.
public extern "C" MTLTexture cp_drawable_get_tracking_areas_texture(cp_drawable_t drawable, nuint index);

/// macOS 26.0 and later.
public extern "C" cp_tracking_area_t cp_drawable_add_tracking_area(cp_drawable_t drawable, cp_tracking_area_identifier identifier);

/// macOS 26.0 and later.
public extern "C" nuint cp_drawable_get_rasterization_rate_map_count(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" MTLRasterizationRateMap cp_drawable_get_rasterization_rate_map(cp_drawable_t drawable, nuint index);

/// macOS 26.0 and later.
public extern "C" MTLRasterizationRateMap cp_drawable_get_flipped_rasterization_rate_map(cp_drawable_t drawable, nuint index);

/// macOS 26.0 and later.
public extern "C" nuint cp_drawable_get_view_count(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" cp_view_t cp_drawable_get_view(cp_drawable_t drawable, nuint index);

/// macOS 26.0 and later.
public extern "C" void cp_drawable_set_device_anchor(cp_drawable_t drawable, ar_device_anchor_t? device_anchor);

/// macOS 26.0 and later.
public extern "C" ar_device_anchor_t? cp_drawable_get_device_anchor(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" simd_float2 cp_drawable_get_depth_range(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" void cp_drawable_set_depth_range(cp_drawable_t drawable, simd_float2 depth_range);

/// macOS 26.0 and later.
public extern "C" void cp_drawable_encode_present(cp_drawable_t drawable, MTLCommandBuffer command_buffer);

/// macOS 26.0 and later.
public extern "C" void cp_drawable_mtl4_encode_present(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" cp_drawable_state cp_drawable_get_state(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" cp_drawable_target cp_drawable_get_target(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" cp_compositor_frame_index_t cp_drawable_get_presentation_frame_index(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" cp_frame_timing_t cp_drawable_get_frame_timing(cp_drawable_t drawable);

/// macOS 26.0 and later.
public extern "C" simd_float4x4 cp_drawable_compute_projection(cp_drawable_t drawable, cp_axis_direction_convention normalized_device_coordinates_convension, nuint view_index);

/// macOS 26.0 and later.
public extern "C" cp_drawable_render_context_t cp_drawable_add_render_context(cp_drawable_t drawable, MTLCommandBuffer cmd_buffer);

/// macOS 26.0 and later.
public extern "C" cp_drawable_render_context_t cp_drawable_add_mtl4_render_context(cp_drawable_t drawable);

public struct cp_drawable_array;

/// macOS 26.0 and later.
public using cp_drawable_array_t = cp_drawable_array*;

/// macOS 26.0 and later.
public extern "C" cp_drawable_t cp_drawable_array_get_drawable(cp_drawable_array_t drawable_array, nuint index);

/// macOS 26.0 and later.
public extern "C" nuint cp_drawable_array_get_count(cp_drawable_array_t drawable_array);

#endif
