// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from VideoSubscriberAccount.framework (VSUserAccount.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.VideoSubscriberAccount;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "VideoSubscriberAccount")

public enum VSUserAccountType : long
{
    Free = 0,
    Paid = 1,
}

public enum VSOriginatingDeviceCategory : long
{
    Mobile = 0,
    Other = 1,
}

public extern objc class VSUserAccount : NSObject
{
    [Selector("updateURL", "setUpdateURL:")]
    public NSURL? UpdateURL { get; set; }
    [Selector("requiresSystemTrust", "setRequiresSystemTrust:")]
    public bool RequiresSystemTrust { get; set; }
    [Selector("accountProviderIdentifier", "setAccountProviderIdentifier:")]
    public NSString? AccountProviderIdentifier { get; set; }
    [Selector("identifier", "setIdentifier:")]
    public NSString? Identifier { get; set; }
    [Selector("accountType", "setAccountType:")]
    public VSUserAccountType AccountType { get; set; }
    [Selector("isSignedOut", "setSignedOut:")]
    public bool SignedOut { get; set; }
    [Selector("subscriptionBillingCycleEndDate", "setSubscriptionBillingCycleEndDate:")]
    public NSDate? SubscriptionBillingCycleEndDate { get; set; }
    [Selector("tierIdentifiers", "setTierIdentifiers:")]
    public NSArray? TierIdentifiers { get; set; }
    [Selector("billingIdentifier", "setBillingIdentifier:")]
    public NSString? BillingIdentifier { get; set; }
    [Selector("authenticationData", "setAuthenticationData:")]
    public NSString? AuthenticationData { get; set; }
    [Selector("isFromCurrentDevice")]
    public bool FromCurrentDevice { get; }
    [Selector("deviceCategory")]
    public VSOriginatingDeviceCategory DeviceCategory { get; }
    [Selector("appleSubscription", "setAppleSubscription:")]
    public VSAppleSubscription? AppleSubscription { get; set; }
    [Selector("initWithAccountType:updateURL:")]
    public Self InitWithAccountTypeUpdateURL(VSUserAccountType accountType, NSURL? url);
}

#endif
