// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from PencilKit.framework (PKStroke.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.PencilKit;

import MacOS.AppKit;
import MacOS.CoreFoundation;
import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "PencilKit")

public extern objc class PKStroke : NSObject, NSCopying
{
    [Selector("ink")] public PKInk Ink { get; }
    [Selector("transform")] public CGAffineTransform Transform { get; }
    [Selector("path")] public PKStrokePath Path { get; }
    [Selector("mask")] public NSBezierPath? Mask { get; }
    [Selector("renderBounds")] public CGRect RenderBounds { get; }
    [Selector("maskedPathRanges")] public NSArray MaskedPathRanges { get; }
    [Selector("randomSeed")] public uint RandomSeed { get; }
    [Selector("requiredContentVersion")] public PKContentVersion RequiredContentVersion { get; }
    [Selector("initWithInk:strokePath:transform:mask:")] public Self InitWithInkStrokePathTransformMask(PKInk ink, PKStrokePath strokePath, CGAffineTransform transform, NSBezierPath? mask);
    [Selector("initWithInk:strokePath:transform:mask:randomSeed:")] public Self InitWithInkStrokePathTransformMaskRandomSeed(PKInk ink, PKStrokePath strokePath, CGAffineTransform transform, NSBezierPath? mask, uint randomSeed);
}

#endif
