// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from ApplicationServices.framework (HIServices_AXTextAttributedString.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.ApplicationServices;

import MacOS.CoreFoundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "ApplicationServices")

public extern "C" CFStringRef? kAXFontTextAttribute;

public extern "C" CFStringRef? kAXForegroundColorTextAttribute;

public extern "C" CFStringRef? kAXBackgroundColorTextAttribute;

public extern "C" CFStringRef? kAXUnderlineColorTextAttribute;

public extern "C" CFStringRef? kAXStrikethroughColorTextAttribute;

public extern "C" CFStringRef? kAXUnderlineTextAttribute;

public extern "C" CFStringRef? kAXSuperscriptTextAttribute;

public extern "C" CFStringRef? kAXStrikethroughTextAttribute;

public extern "C" CFStringRef? kAXShadowTextAttribute;

public extern "C" CFStringRef? kAXAttachmentTextAttribute;

public extern "C" CFStringRef? kAXLinkTextAttribute;

public extern "C" CFStringRef? kAXNaturalLanguageTextAttribute;

public extern "C" CFStringRef? kAXReplacementStringTextAttribute;

public extern "C" CFStringRef? kAXMisspelledTextAttribute;

public extern "C" CFStringRef? kAXMarkedMisspelledTextAttribute;

public extern "C" CFStringRef? kAXAutocorrectedTextAttribute;

public extern "C" CFStringRef? kAXListItemPrefixTextAttribute;

public extern "C" CFStringRef? kAXListItemIndexTextAttribute;

public extern "C" CFStringRef? kAXListItemLevelTextAttribute;

public extern "C" CFStringRef? kAXFontNameKey;

public extern "C" CFStringRef? kAXFontFamilyKey;

public extern "C" CFStringRef? kAXVisibleNameKey;

public extern "C" CFStringRef? kAXFontSizeKey;

public enum AXUnderlineStyle : uint
{
    None = 0,
    Single = 1,
    Thick = 2,
    Double = 9,
}

public extern "C" CFStringRef? kAXForegoundColorTextAttribute;

#endif
