// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from ApplicationServices.framework (HIServices_AXRoleConstants.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.ApplicationServices;

import MacOS.CoreFoundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "ApplicationServices")

public const CFStringRef kAXApplicationRole = "AXApplication";

public const CFStringRef kAXSystemWideRole = "AXSystemWide";

public const CFStringRef kAXWindowRole = "AXWindow";

public const CFStringRef kAXSheetRole = "AXSheet";

public const CFStringRef kAXDrawerRole = "AXDrawer";

public const CFStringRef kAXGrowAreaRole = "AXGrowArea";

public const CFStringRef kAXImageRole = "AXImage";

public const CFStringRef kAXUnknownRole = "AXUnknown";

public const CFStringRef kAXButtonRole = "AXButton";

public const CFStringRef kAXRadioButtonRole = "AXRadioButton";

public const CFStringRef kAXCheckBoxRole = "AXCheckBox";

public const CFStringRef kAXPopUpButtonRole = "AXPopUpButton";

public const CFStringRef kAXMenuButtonRole = "AXMenuButton";

public const CFStringRef kAXTabGroupRole = "AXTabGroup";

public const CFStringRef kAXTableRole = "AXTable";

public const CFStringRef kAXColumnRole = "AXColumn";

public const CFStringRef kAXRowRole = "AXRow";

public const CFStringRef kAXOutlineRole = "AXOutline";

public const CFStringRef kAXBrowserRole = "AXBrowser";

public const CFStringRef kAXScrollAreaRole = "AXScrollArea";

public const CFStringRef kAXScrollBarRole = "AXScrollBar";

public const CFStringRef kAXRadioGroupRole = "AXRadioGroup";

public const CFStringRef kAXListRole = "AXList";

public const CFStringRef kAXGroupRole = "AXGroup";

public const CFStringRef kAXValueIndicatorRole = "AXValueIndicator";

public const CFStringRef kAXComboBoxRole = "AXComboBox";

public const CFStringRef kAXSliderRole = "AXSlider";

public const CFStringRef kAXIncrementorRole = "AXIncrementor";

public const CFStringRef kAXBusyIndicatorRole = "AXBusyIndicator";

public const CFStringRef kAXProgressIndicatorRole = "AXProgressIndicator";

public const CFStringRef kAXRelevanceIndicatorRole = "AXRelevanceIndicator";

public const CFStringRef kAXToolbarRole = "AXToolbar";

public const CFStringRef kAXDisclosureTriangleRole = "AXDisclosureTriangle";

public const CFStringRef kAXTextFieldRole = "AXTextField";

public const CFStringRef kAXTextAreaRole = "AXTextArea";

public const CFStringRef kAXStaticTextRole = "AXStaticText";

public const CFStringRef kAXHeadingRole = "AXHeading";

public const CFStringRef kAXMenuBarRole = "AXMenuBar";

public const CFStringRef kAXMenuBarItemRole = "AXMenuBarItem";

public const CFStringRef kAXMenuRole = "AXMenu";

public const CFStringRef kAXMenuItemRole = "AXMenuItem";

public const CFStringRef kAXSplitGroupRole = "AXSplitGroup";

public const CFStringRef kAXSplitterRole = "AXSplitter";

public const CFStringRef kAXColorWellRole = "AXColorWell";

public const CFStringRef kAXTimeFieldRole = "AXTimeField";

public const CFStringRef kAXDateFieldRole = "AXDateField";

public const CFStringRef kAXHelpTagRole = "AXHelpTag";

public const CFStringRef kAXMatteRole = "AXMatte";

public const CFStringRef kAXDockItemRole = "AXDockItem";

public const CFStringRef kAXRulerRole = "AXRuler";

public const CFStringRef kAXRulerMarkerRole = "AXRulerMarker";

public const CFStringRef kAXGridRole = "AXGrid";

public const CFStringRef kAXLevelIndicatorRole = "AXLevelIndicator";

public const CFStringRef kAXCellRole = "AXCell";

public const CFStringRef kAXLayoutAreaRole = "AXLayoutArea";

public const CFStringRef kAXLayoutItemRole = "AXLayoutItem";

public const CFStringRef kAXHandleRole = "AXHandle";

public const CFStringRef kAXPopoverRole = "AXPopover";

public const CFStringRef kAXCloseButtonSubrole = "AXCloseButton";

public const CFStringRef kAXMinimizeButtonSubrole = "AXMinimizeButton";

public const CFStringRef kAXZoomButtonSubrole = "AXZoomButton";

public const CFStringRef kAXToolbarButtonSubrole = "AXToolbarButton";

public const CFStringRef kAXFullScreenButtonSubrole = "AXFullScreenButton";

public const CFStringRef kAXSecureTextFieldSubrole = "AXSecureTextField";

public const CFStringRef kAXTableRowSubrole = "AXTableRow";

public const CFStringRef kAXOutlineRowSubrole = "AXOutlineRow";

public const CFStringRef kAXUnknownSubrole = "AXUnknown";

public const CFStringRef kAXStandardWindowSubrole = "AXStandardWindow";

public const CFStringRef kAXDialogSubrole = "AXDialog";

public const CFStringRef kAXSystemDialogSubrole = "AXSystemDialog";

public const CFStringRef kAXFloatingWindowSubrole = "AXFloatingWindow";

public const CFStringRef kAXSystemFloatingWindowSubrole = "AXSystemFloatingWindow";

public const CFStringRef kAXDecorativeSubrole = "AXDecorative";

public const CFStringRef kAXIncrementArrowSubrole = "AXIncrementArrow";

public const CFStringRef kAXDecrementArrowSubrole = "AXDecrementArrow";

public const CFStringRef kAXIncrementPageSubrole = "AXIncrementPage";

public const CFStringRef kAXDecrementPageSubrole = "AXDecrementPage";

public const CFStringRef kAXSortButtonSubrole = "AXSortButton";

public const CFStringRef kAXSearchFieldSubrole = "AXSearchField";

public const CFStringRef kAXTimelineSubrole = "AXTimeline";

public const CFStringRef kAXRatingIndicatorSubrole = "AXRatingIndicator";

public const CFStringRef kAXContentListSubrole = "AXContentList";

public const CFStringRef kAXDefinitionListSubrole = "AXDefinitionList";

public const CFStringRef kAXDescriptionListSubrole = "AXDescriptionList";

public const CFStringRef kAXToggleSubrole = "AXToggle";

public const CFStringRef kAXSwitchSubrole = "AXSwitch";

public const CFStringRef kAXApplicationDockItemSubrole = "AXApplicationDockItem";

public const CFStringRef kAXDocumentDockItemSubrole = "AXDocumentDockItem";

public const CFStringRef kAXFolderDockItemSubrole = "AXFolderDockItem";

public const CFStringRef kAXMinimizedWindowDockItemSubrole = "AXMinimizedWindowDockItem";

public const CFStringRef kAXURLDockItemSubrole = "AXURLDockItem";

public const CFStringRef kAXDockExtraDockItemSubrole = "AXDockExtraDockItem";

public const CFStringRef kAXTrashDockItemSubrole = "AXTrashDockItem";

public const CFStringRef kAXSeparatorDockItemSubrole = "AXSeparatorDockItem";

public const CFStringRef kAXProcessSwitcherListSubrole = "AXProcessSwitcherList";

#endif
