// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from ApplicationServices.framework (HIServices_AXValue.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.ApplicationServices;

import MacOS.CoreFoundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "ApplicationServices")

public enum AXValueType : uint
{
    CGPoint = 1,
    CGSize = 2,
    CGRect = 3,
    CFRange = 4,
    AXError = 5,
    Illegal = 0,
}

public struct __AXValue;

[CFType("AXValueGetTypeID")]
public extern objc class AXValueRef : CFTypeRef { }

public extern "C" CFTypeID AXValueGetTypeID();

[ReturnsRetained]
public extern "C" AXValueRef? AXValueCreate(AXValueType theType, void* valuePtr);

public extern "C" AXValueType AXValueGetType(AXValueRef value);

public extern "C" Boolean AXValueGetValue(AXValueRef value, AXValueType theType, void* valuePtr);

#endif
