// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from ApplicationServices.framework (QD_Fonts.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.ApplicationServices;

import MacOS.System;

#if MACOS

#pragma comment(framework, "ApplicationServices")

[Pack(2)]
public struct FontRec
{
    public SInt16 fontType;
    public SInt16 firstChar;
    public SInt16 lastChar;
    public SInt16 widMax;
    public SInt16 kernMax;
    public SInt16 nDescent;
    public SInt16 fRectWidth;
    public SInt16 fRectHeight;
    public UInt16 owTLoc;
    public SInt16 ascent;
    public SInt16 descent;
    public SInt16 leading;
    public SInt16 rowWords;
}

public using FontRecPtr = FontRec*;

public using FontRecHdl = FontRecPtr*;

[Pack(2)]
public struct FMInput
{
    public short family;
    public short size;
    public Style face;
    public Boolean needBits;
    public short device;
    public Point numer;
    public Point denom;
}

[Pack(2)]
public struct FamRec
{
    public SInt16 ffFlags;
    public SInt16 ffFamID;
    public SInt16 ffFirstChar;
    public SInt16 ffLastChar;
    public SInt16 ffAscent;
    public SInt16 ffDescent;
    public SInt16 ffLeading;
    public SInt16 ffWidMax;
    public SInt32 ffWTabOff;
    public SInt32 ffKernOff;
    public SInt32 ffStylOff;
    public SInt16[9] ffProperty;
    public SInt16[2] ffIntl;
    public SInt16 ffVersion;
}

[Pack(2)]
public struct AsscEntry
{
    public SInt16 fontSize;
    public SInt16 fontStyle;
    public SInt16 fontID;
}

[Pack(2)]
public struct FontAssoc
{
    public SInt16 numAssoc;
}

[Pack(2)]
public struct StyleTable
{
    public SInt16 fontClass;
    public SInt32 offset;
    public SInt32 reserved;
    public byte[48] indexes;
}

[Pack(2)]
public struct NameTable
{
    public SInt16 stringCount;
    public Str255 baseFontName;
}

[Pack(2)]
public struct KernPair
{
    public byte kernFirst;
    public byte kernSecond;
    public SInt16 kernWidth;
}

[Pack(2)]
public struct KernEntry
{
    public SInt16 kernStyle;
    public SInt16 kernLength;
}

[Pack(2)]
public struct KernTable
{
    public SInt16 numKerns;
}

#endif
