// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AVFAudio.framework (AVAudioUnitReverb.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AVFAudio;

import Standard.ObjC;

#if MACOS

#pragma comment(framework, "AVFAudio")

public enum AVAudioUnitReverbPreset : long
{
    SmallRoom = 0,
    MediumRoom = 1,
    LargeRoom = 2,
    MediumHall = 3,
    LargeHall = 4,
    Plate = 5,
    MediumChamber = 6,
    LargeChamber = 7,
    Cathedral = 8,
    LargeRoom2 = 9,
    MediumHall2 = 10,
    MediumHall3 = 11,
    LargeHall2 = 12,
}

public extern objc class AVAudioUnitReverb : AVAudioUnitEffect
{
    [Selector("wetDryMix", "setWetDryMix:")] public float WetDryMix { get; set; }
    [Selector("loadFactoryPreset:")] public void LoadFactoryPreset(AVAudioUnitReverbPreset preset);
}

#endif
