// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AVFAudio.framework (AVAudioSessionTypes.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AVFAudio;

import MacOS.Foundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "AVFAudio")

public using AVAudioSessionPort = NSString;

public using AVAudioSessionCategory = NSString;

public using AVAudioSessionMode = NSString;

public extern "C" NSString? AVAudioSessionInterruptionWasSuspendedKey;

[Flags]
public enum AVAudioSessionActivationOptions : ulong
{
    AVAudioSessionActivationOptionNone = 0,
}

public enum AVAudioSessionPortOverride : ulong
{
    AVAudioSessionPortOverrideNone = 0,
}

public enum AVAudioSessionRouteChangeReason : ulong
{
    Unknown = 0,
    NewDeviceAvailable = 1,
    OldDeviceUnavailable = 2,
    CategoryChange = 3,
    Override = 4,
    WakeFromSleep = 6,
    NoSuitableRouteForCategory = 7,
    RouteConfigurationChange = 8,
}

[Flags]
public enum AVAudioSessionCategoryOptions : ulong
{
    MixWithOthers = 1,
    DuckOthers = 2,
}

public enum AVAudioSessionInterruptionType : ulong
{
    Began = 1,
    Ended = 0,
}

[Flags]
public enum AVAudioSessionInterruptionOptions : ulong
{
    AVAudioSessionInterruptionOptionShouldResume = 1,
}

public enum AVAudioSessionInterruptionReason : ulong
{
    Default = 0,
    AppWasSuspended = 1,
    BuiltInMicMuted = 2,
}

[Flags]
public enum AVAudioSessionSetActiveOptions : ulong
{
    AVAudioSessionSetActiveOptionNotifyOthersOnDeactivation = 1,
}

public enum AVAudioSessionSilenceSecondaryAudioHintType : ulong
{
    Begin = 1,
    End = 0,
}

public enum AVAudioSessionIOType : ulong
{
    NotSpecified = 0,
    Aggregated = 1,
}

public enum AVAudioSessionRouteSharingPolicy : ulong
{
    Default = 0,
    LongFormAudio = 1,
    Independent = 2,
}

public enum AVAudioSessionPromptStyle : ulong
{
    None = 1852796517,
    Short = 1936224884,
    Normal = 1852992876,
}

public enum AVAudioStereoOrientation : long
{
    None = 0,
    Portrait = 1,
    PortraitUpsideDown = 2,
    LandscapeRight = 3,
    LandscapeLeft = 4,
}

public enum AVAudioSessionRenderingMode : long
{
    NotApplicable = 0,
    MonoStereo = 1,
    Surround = 2,
    SpatialAudio = 3,
    DolbyAudio = 4,
    DolbyAtmos = 5,
}

public enum AVAudioSessionMicrophoneInjectionMode : long
{
    None = 0,
    SpokenAudio = 1,
}

#endif
