// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from VideoToolbox.framework (VTCompressionSession.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.VideoToolbox;

import MacOS.CoreFoundation;
import MacOS.CoreMedia;
import MacOS.CoreVideo;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "VideoToolbox")

public struct OpaqueVTCompressionSession;

[CFType("VTCompressionSessionGetTypeID")]
public extern objc class VTCompressionSessionRef : CFTypeRef { }

public delegate void VTCompressionOutputCallback(void* arg0, void* arg1, OSStatus arg2, VTEncodeInfoFlags arg3, opaqueCMSampleBuffer* arg4);

public extern "C" CFStringRef? kVTVideoEncoderSpecification_EncoderID;

public extern "C" OSStatus VTCompressionSessionCreate(CFAllocatorRef? allocator, int width, int height, CMVideoCodecType codecType, CFDictionaryRef? encoderSpecification, CFDictionaryRef? sourceImageBufferAttributes, CFAllocatorRef? compressedDataAllocator, VTCompressionOutputCallback outputCallback, void* outputCallbackRefCon, OpaqueVTCompressionSession** compressionSessionOut);

public extern "C" void VTCompressionSessionInvalidate(VTCompressionSessionRef session);

public extern "C" CFTypeID VTCompressionSessionGetTypeID();

public extern "C" CVPixelBufferPoolRef? VTCompressionSessionGetPixelBufferPool(VTCompressionSessionRef session);

public extern "C" OSStatus VTCompressionSessionPrepareToEncodeFrames(VTCompressionSessionRef session);

public extern "C" OSStatus VTCompressionSessionEncodeFrame(VTCompressionSessionRef session, CVImageBufferRef imageBuffer, CMTime presentationTimeStamp, CMTime duration, CFDictionaryRef? frameProperties, void* sourceFrameRefcon, VTEncodeInfoFlags* infoFlagsOut);

public objc closure void VTCompressionOutputHandler(OSStatus arg0, VTEncodeInfoFlags arg1, CMSampleBufferRef? arg2);

public extern "C" OSStatus VTCompressionSessionEncodeFrameWithOutputHandler(VTCompressionSessionRef session, CVImageBufferRef imageBuffer, CMTime presentationTimeStamp, CMTime duration, CFDictionaryRef? frameProperties, VTEncodeInfoFlags* infoFlagsOut, VTCompressionOutputHandler outputHandler);

public extern "C" OSStatus VTCompressionSessionCompleteFrames(VTCompressionSessionRef session, CMTime completeUntilPresentationTimeStamp);

public extern "C" Boolean VTIsStereoMVHEVCEncodeSupported();

public extern "C" OSStatus VTCompressionSessionEncodeMultiImageFrame(VTCompressionSessionRef session, CMTaggedBufferGroupRef taggedBufferGroup, CMTime presentationTimeStamp, CMTime duration, CFDictionaryRef? frameProperties, void* sourceFrameRefcon, VTEncodeInfoFlags* infoFlagsOut);

public extern "C" OSStatus VTCompressionSessionEncodeMultiImageFrameWithOutputHandler(VTCompressionSessionRef session, CMTaggedBufferGroupRef taggedBufferGroup, CMTime presentationTimeStamp, CMTime duration, CFDictionaryRef? frameProperties, VTEncodeInfoFlags* infoFlagsOut, VTCompressionOutputHandler outputHandler);

[Flags]
public enum VTCompressionSessionOptionFlags : uint
{
    kVTCompressionSessionBeginFinalPass = 1,
}

public extern "C" OSStatus VTCompressionSessionBeginPass(VTCompressionSessionRef session, VTCompressionSessionOptionFlags beginPassFlags, uint* reserved);

public extern "C" OSStatus VTCompressionSessionEndPass(VTCompressionSessionRef session, Boolean* furtherPassesRequestedOut, uint* reserved);

public extern "C" OSStatus VTCompressionSessionGetTimeRangesForNextPass(VTCompressionSessionRef session, CMItemCount* timeRangeCountOut, CMTimeRange** timeRangeArrayOut);

#endif
