// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreText.framework (CTFrame.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreText;

import MacOS.CoreFoundation;
import MacOS.CoreGraphics;

#if MACOS

#pragma comment(framework, "CoreText")

public struct __CTFrame;

public using CTFrameRef = __CTFrame*;

public extern "C" CFTypeID CTFrameGetTypeID();

public enum CTFrameProgression : uint
{
    TopToBottom = 0,
    RightToLeft = 1,
    LeftToRight = 2,
}

public extern "C" CFStringRef kCTFrameProgressionAttributeName;

public enum CTFramePathFillRule : uint
{
    EvenOdd = 0,
    WindingNumber = 1,
}

public extern "C" CFStringRef kCTFramePathFillRuleAttributeName;

public extern "C" CFStringRef kCTFramePathWidthAttributeName;

public extern "C" CFStringRef kCTFrameClippingPathsAttributeName;

public extern "C" CFStringRef kCTFramePathClippingPathAttributeName;

public extern "C" CFRange CTFrameGetStringRange(CTFrameRef frame);

public extern "C" CFRange CTFrameGetVisibleStringRange(CTFrameRef frame);

public extern "C" CGPathRef CTFrameGetPath(CTFrameRef frame);

public extern "C" CFDictionaryRef CTFrameGetFrameAttributes(CTFrameRef frame);

public extern "C" CFArrayRef CTFrameGetLines(CTFrameRef frame);

public extern "C" void CTFrameGetLineOrigins(CTFrameRef frame, CFRange range, CGPoint* origins);

public extern "C" void CTFrameDraw(CTFrameRef frame, CGContextRef context);

#endif
