// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreText.framework (CTLine.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreText;

import MacOS.CoreFoundation;
import MacOS.CoreGraphics;

#if MACOS

#pragma comment(framework, "CoreText")

public struct __CTLine;

public using CTLineRef = __CTLine*;

[Flags]
public enum CTLineBoundsOptions : ulong
{
    ExcludeTypographicLeading = 1,
    ExcludeTypographicShifts = 2,
    UseHangingPunctuation = 4,
    UseGlyphPathBounds = 8,
    UseOpticalBounds = 16,
    IncludeLanguageExtents = 32,
}

public enum CTLineTruncationType : uint
{
    Start = 0,
    End = 1,
    Middle = 2,
}

public extern "C" CFTypeID CTLineGetTypeID();

public extern "C" CTLineRef CTLineCreateWithAttributedString(CFAttributedStringRef attrString);

public extern "C" CTLineRef CTLineCreateTruncatedLine(CTLineRef line, double width, CTLineTruncationType truncationType, CTLineRef truncationToken);

public extern "C" CTLineRef CTLineCreateJustifiedLine(CTLineRef line, CGFloat justificationFactor, double justificationWidth);

public extern "C" CFIndex CTLineGetGlyphCount(CTLineRef line);

public extern "C" CFArrayRef CTLineGetGlyphRuns(CTLineRef line);

public extern "C" CFRange CTLineGetStringRange(CTLineRef line);

public extern "C" double CTLineGetPenOffsetForFlush(CTLineRef line, CGFloat flushFactor, double flushWidth);

public extern "C" void CTLineDraw(CTLineRef line, CGContextRef context);

public extern "C" double CTLineGetTypographicBounds(CTLineRef line, CGFloat* ascent, CGFloat* descent, CGFloat* leading);

public extern "C" CGRect CTLineGetBoundsWithOptions(CTLineRef line, CTLineBoundsOptions options);

public extern "C" double CTLineGetTrailingWhitespaceWidth(CTLineRef line);

public extern "C" CGRect CTLineGetImageBounds(CTLineRef line, CGContextRef context);

public extern "C" CFIndex CTLineGetStringIndexForPosition(CTLineRef line, CGPoint position);

public extern "C" CGFloat CTLineGetOffsetForStringIndex(CTLineRef line, CFIndex charIndex, CGFloat* secondaryOffset);

public objc closure void CTLineEnumerateCaretOffsetsBlock(double arg0, CFIndex arg1, bool arg2, bool* arg3);

public extern "C" void CTLineEnumerateCaretOffsets(CTLineRef line, CTLineEnumerateCaretOffsetsBlock block);

#endif
