// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreText.framework (SFNTLayoutTypes.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreText;

import MacOS.System;

#if MACOS

#pragma comment(framework, "CoreText")

public const int kAllTypographicFeaturesType = 0;
public const int kLigaturesType = 1;
public const int kCursiveConnectionType = 2;
public const int kLetterCaseType = 3;
public const int kVerticalSubstitutionType = 4;
public const int kLinguisticRearrangementType = 5;
public const int kNumberSpacingType = 6;
public const int kSmartSwashType = 8;
public const int kDiacriticsType = 9;
public const int kVerticalPositionType = 10;
public const int kFractionsType = 11;
public const int kOverlappingCharactersType = 13;
public const int kTypographicExtrasType = 14;
public const int kMathematicalExtrasType = 15;
public const int kOrnamentSetsType = 16;
public const int kCharacterAlternativesType = 17;
public const int kDesignComplexityType = 18;
public const int kStyleOptionsType = 19;
public const int kCharacterShapeType = 20;
public const int kNumberCaseType = 21;
public const int kTextSpacingType = 22;
public const int kTransliterationType = 23;
public const int kAnnotationType = 24;
public const int kKanaSpacingType = 25;
public const int kIdeographicSpacingType = 26;
public const int kUnicodeDecompositionType = 27;
public const int kRubyKanaType = 28;
public const int kCJKSymbolAlternativesType = 29;
public const int kIdeographicAlternativesType = 30;
public const int kCJKVerticalRomanPlacementType = 31;
public const int kItalicCJKRomanType = 32;
public const int kCaseSensitiveLayoutType = 33;
public const int kAlternateKanaType = 34;
public const int kStylisticAlternativesType = 35;
public const int kContextualAlternatesType = 36;
public const int kLowerCaseType = 37;
public const int kUpperCaseType = 38;
public const int kLanguageTagType = 39;
public const int kCJKRomanSpacingType = 103;
public const int kLastFeatureType = -1;

public const int kAllTypeFeaturesOnSelector = 0;
public const int kAllTypeFeaturesOffSelector = 1;

public const int kRequiredLigaturesOnSelector = 0;
public const int kRequiredLigaturesOffSelector = 1;
public const int kCommonLigaturesOnSelector = 2;
public const int kCommonLigaturesOffSelector = 3;
public const int kRareLigaturesOnSelector = 4;
public const int kRareLigaturesOffSelector = 5;
public const int kLogosOnSelector = 6;
public const int kLogosOffSelector = 7;
public const int kRebusPicturesOnSelector = 8;
public const int kRebusPicturesOffSelector = 9;
public const int kDiphthongLigaturesOnSelector = 10;
public const int kDiphthongLigaturesOffSelector = 11;
public const int kSquaredLigaturesOnSelector = 12;
public const int kSquaredLigaturesOffSelector = 13;
public const int kAbbrevSquaredLigaturesOnSelector = 14;
public const int kAbbrevSquaredLigaturesOffSelector = 15;
public const int kSymbolLigaturesOnSelector = 16;
public const int kSymbolLigaturesOffSelector = 17;
public const int kContextualLigaturesOnSelector = 18;
public const int kContextualLigaturesOffSelector = 19;
public const int kHistoricalLigaturesOnSelector = 20;
public const int kHistoricalLigaturesOffSelector = 21;

public const int kUnconnectedSelector = 0;
public const int kPartiallyConnectedSelector = 1;
public const int kCursiveSelector = 2;

public const int kUpperAndLowerCaseSelector = 0;
public const int kAllCapsSelector = 1;
public const int kAllLowerCaseSelector = 2;
public const int kSmallCapsSelector = 3;
public const int kInitialCapsSelector = 4;
public const int kInitialCapsAndSmallCapsSelector = 5;

public const int kSubstituteVerticalFormsOnSelector = 0;
public const int kSubstituteVerticalFormsOffSelector = 1;

public const int kLinguisticRearrangementOnSelector = 0;
public const int kLinguisticRearrangementOffSelector = 1;

public const int kMonospacedNumbersSelector = 0;
public const int kProportionalNumbersSelector = 1;
public const int kThirdWidthNumbersSelector = 2;
public const int kQuarterWidthNumbersSelector = 3;

public const int kWordInitialSwashesOnSelector = 0;
public const int kWordInitialSwashesOffSelector = 1;
public const int kWordFinalSwashesOnSelector = 2;
public const int kWordFinalSwashesOffSelector = 3;
public const int kLineInitialSwashesOnSelector = 4;
public const int kLineInitialSwashesOffSelector = 5;
public const int kLineFinalSwashesOnSelector = 6;
public const int kLineFinalSwashesOffSelector = 7;
public const int kNonFinalSwashesOnSelector = 8;
public const int kNonFinalSwashesOffSelector = 9;

public const int kShowDiacriticsSelector = 0;
public const int kHideDiacriticsSelector = 1;
public const int kDecomposeDiacriticsSelector = 2;

public const int kNormalPositionSelector = 0;
public const int kSuperiorsSelector = 1;
public const int kInferiorsSelector = 2;
public const int kOrdinalsSelector = 3;
public const int kScientificInferiorsSelector = 4;

public const int kNoFractionsSelector = 0;
public const int kVerticalFractionsSelector = 1;
public const int kDiagonalFractionsSelector = 2;

public const int kPreventOverlapOnSelector = 0;
public const int kPreventOverlapOffSelector = 1;

public const int kHyphensToEmDashOnSelector = 0;
public const int kHyphensToEmDashOffSelector = 1;
public const int kHyphenToEnDashOnSelector = 2;
public const int kHyphenToEnDashOffSelector = 3;
public const int kSlashedZeroOnSelector = 4;
public const int kSlashedZeroOffSelector = 5;
public const int kFormInterrobangOnSelector = 6;
public const int kFormInterrobangOffSelector = 7;
public const int kSmartQuotesOnSelector = 8;
public const int kSmartQuotesOffSelector = 9;
public const int kPeriodsToEllipsisOnSelector = 10;
public const int kPeriodsToEllipsisOffSelector = 11;

public const int kHyphenToMinusOnSelector = 0;
public const int kHyphenToMinusOffSelector = 1;
public const int kAsteriskToMultiplyOnSelector = 2;
public const int kAsteriskToMultiplyOffSelector = 3;
public const int kSlashToDivideOnSelector = 4;
public const int kSlashToDivideOffSelector = 5;
public const int kInequalityLigaturesOnSelector = 6;
public const int kInequalityLigaturesOffSelector = 7;
public const int kExponentsOnSelector = 8;
public const int kExponentsOffSelector = 9;
public const int kMathematicalGreekOnSelector = 10;
public const int kMathematicalGreekOffSelector = 11;

public const int kNoOrnamentsSelector = 0;
public const int kDingbatsSelector = 1;
public const int kPiCharactersSelector = 2;
public const int kFleuronsSelector = 3;
public const int kDecorativeBordersSelector = 4;
public const int kInternationalSymbolsSelector = 5;
public const int kMathSymbolsSelector = 6;

public const int kNoAlternatesSelector = 0;

public const int kDesignLevel1Selector = 0;
public const int kDesignLevel2Selector = 1;
public const int kDesignLevel3Selector = 2;
public const int kDesignLevel4Selector = 3;
public const int kDesignLevel5Selector = 4;

public const int kNoStyleOptionsSelector = 0;
public const int kDisplayTextSelector = 1;
public const int kEngravedTextSelector = 2;
public const int kIlluminatedCapsSelector = 3;
public const int kTitlingCapsSelector = 4;
public const int kTallCapsSelector = 5;

public const int kTraditionalCharactersSelector = 0;
public const int kSimplifiedCharactersSelector = 1;
public const int kJIS1978CharactersSelector = 2;
public const int kJIS1983CharactersSelector = 3;
public const int kJIS1990CharactersSelector = 4;
public const int kTraditionalAltOneSelector = 5;
public const int kTraditionalAltTwoSelector = 6;
public const int kTraditionalAltThreeSelector = 7;
public const int kTraditionalAltFourSelector = 8;
public const int kTraditionalAltFiveSelector = 9;
public const int kExpertCharactersSelector = 10;
public const int kJIS2004CharactersSelector = 11;
public const int kHojoCharactersSelector = 12;
public const int kNLCCharactersSelector = 13;
public const int kTraditionalNamesCharactersSelector = 14;

public const int kLowerCaseNumbersSelector = 0;
public const int kUpperCaseNumbersSelector = 1;

public const int kProportionalTextSelector = 0;
public const int kMonospacedTextSelector = 1;
public const int kHalfWidthTextSelector = 2;
public const int kThirdWidthTextSelector = 3;
public const int kQuarterWidthTextSelector = 4;
public const int kAltProportionalTextSelector = 5;
public const int kAltHalfWidthTextSelector = 6;

public const int kNoTransliterationSelector = 0;
public const int kHanjaToHangulSelector = 1;
public const int kHiraganaToKatakanaSelector = 2;
public const int kKatakanaToHiraganaSelector = 3;
public const int kKanaToRomanizationSelector = 4;
public const int kRomanizationToHiraganaSelector = 5;
public const int kRomanizationToKatakanaSelector = 6;
public const int kHanjaToHangulAltOneSelector = 7;
public const int kHanjaToHangulAltTwoSelector = 8;
public const int kHanjaToHangulAltThreeSelector = 9;

public const int kNoAnnotationSelector = 0;
public const int kBoxAnnotationSelector = 1;
public const int kRoundedBoxAnnotationSelector = 2;
public const int kCircleAnnotationSelector = 3;
public const int kInvertedCircleAnnotationSelector = 4;
public const int kParenthesisAnnotationSelector = 5;
public const int kPeriodAnnotationSelector = 6;
public const int kRomanNumeralAnnotationSelector = 7;
public const int kDiamondAnnotationSelector = 8;
public const int kInvertedBoxAnnotationSelector = 9;
public const int kInvertedRoundedBoxAnnotationSelector = 10;

public const int kFullWidthKanaSelector = 0;
public const int kProportionalKanaSelector = 1;

public const int kFullWidthIdeographsSelector = 0;
public const int kProportionalIdeographsSelector = 1;
public const int kHalfWidthIdeographsSelector = 2;

public const int kCanonicalCompositionOnSelector = 0;
public const int kCanonicalCompositionOffSelector = 1;
public const int kCompatibilityCompositionOnSelector = 2;
public const int kCompatibilityCompositionOffSelector = 3;
public const int kTranscodingCompositionOnSelector = 4;
public const int kTranscodingCompositionOffSelector = 5;

public const int kNoRubyKanaSelector = 0;
public const int kRubyKanaSelector = 1;
public const int kRubyKanaOnSelector = 2;
public const int kRubyKanaOffSelector = 3;

public const int kNoCJKSymbolAlternativesSelector = 0;
public const int kCJKSymbolAltOneSelector = 1;
public const int kCJKSymbolAltTwoSelector = 2;
public const int kCJKSymbolAltThreeSelector = 3;
public const int kCJKSymbolAltFourSelector = 4;
public const int kCJKSymbolAltFiveSelector = 5;

public const int kNoIdeographicAlternativesSelector = 0;
public const int kIdeographicAltOneSelector = 1;
public const int kIdeographicAltTwoSelector = 2;
public const int kIdeographicAltThreeSelector = 3;
public const int kIdeographicAltFourSelector = 4;
public const int kIdeographicAltFiveSelector = 5;

public const int kCJKVerticalRomanCenteredSelector = 0;
public const int kCJKVerticalRomanHBaselineSelector = 1;

public const int kNoCJKItalicRomanSelector = 0;
public const int kCJKItalicRomanSelector = 1;
public const int kCJKItalicRomanOnSelector = 2;
public const int kCJKItalicRomanOffSelector = 3;

public const int kCaseSensitiveLayoutOnSelector = 0;
public const int kCaseSensitiveLayoutOffSelector = 1;
public const int kCaseSensitiveSpacingOnSelector = 2;
public const int kCaseSensitiveSpacingOffSelector = 3;

public const int kAlternateHorizKanaOnSelector = 0;
public const int kAlternateHorizKanaOffSelector = 1;
public const int kAlternateVertKanaOnSelector = 2;
public const int kAlternateVertKanaOffSelector = 3;

public const int kNoStylisticAlternatesSelector = 0;
public const int kStylisticAltOneOnSelector = 2;
public const int kStylisticAltOneOffSelector = 3;
public const int kStylisticAltTwoOnSelector = 4;
public const int kStylisticAltTwoOffSelector = 5;
public const int kStylisticAltThreeOnSelector = 6;
public const int kStylisticAltThreeOffSelector = 7;
public const int kStylisticAltFourOnSelector = 8;
public const int kStylisticAltFourOffSelector = 9;
public const int kStylisticAltFiveOnSelector = 10;
public const int kStylisticAltFiveOffSelector = 11;
public const int kStylisticAltSixOnSelector = 12;
public const int kStylisticAltSixOffSelector = 13;
public const int kStylisticAltSevenOnSelector = 14;
public const int kStylisticAltSevenOffSelector = 15;
public const int kStylisticAltEightOnSelector = 16;
public const int kStylisticAltEightOffSelector = 17;
public const int kStylisticAltNineOnSelector = 18;
public const int kStylisticAltNineOffSelector = 19;
public const int kStylisticAltTenOnSelector = 20;
public const int kStylisticAltTenOffSelector = 21;
public const int kStylisticAltElevenOnSelector = 22;
public const int kStylisticAltElevenOffSelector = 23;
public const int kStylisticAltTwelveOnSelector = 24;
public const int kStylisticAltTwelveOffSelector = 25;
public const int kStylisticAltThirteenOnSelector = 26;
public const int kStylisticAltThirteenOffSelector = 27;
public const int kStylisticAltFourteenOnSelector = 28;
public const int kStylisticAltFourteenOffSelector = 29;
public const int kStylisticAltFifteenOnSelector = 30;
public const int kStylisticAltFifteenOffSelector = 31;
public const int kStylisticAltSixteenOnSelector = 32;
public const int kStylisticAltSixteenOffSelector = 33;
public const int kStylisticAltSeventeenOnSelector = 34;
public const int kStylisticAltSeventeenOffSelector = 35;
public const int kStylisticAltEighteenOnSelector = 36;
public const int kStylisticAltEighteenOffSelector = 37;
public const int kStylisticAltNineteenOnSelector = 38;
public const int kStylisticAltNineteenOffSelector = 39;
public const int kStylisticAltTwentyOnSelector = 40;
public const int kStylisticAltTwentyOffSelector = 41;

public const int kContextualAlternatesOnSelector = 0;
public const int kContextualAlternatesOffSelector = 1;
public const int kSwashAlternatesOnSelector = 2;
public const int kSwashAlternatesOffSelector = 3;
public const int kContextualSwashAlternatesOnSelector = 4;
public const int kContextualSwashAlternatesOffSelector = 5;

public const int kDefaultLowerCaseSelector = 0;
public const int kLowerCaseSmallCapsSelector = 1;
public const int kLowerCasePetiteCapsSelector = 2;

public const int kDefaultUpperCaseSelector = 0;
public const int kUpperCaseSmallCapsSelector = 1;
public const int kUpperCasePetiteCapsSelector = 2;

public const int kHalfWidthCJKRomanSelector = 0;
public const int kProportionalCJKRomanSelector = 1;
public const int kDefaultCJKRomanSelector = 2;
public const int kFullWidthCJKRomanSelector = 3;

public const int kSFNTLookupSimpleArray = 0;
public const int kSFNTLookupSegmentSingle = 2;
public const int kSFNTLookupSegmentArray = 4;
public const int kSFNTLookupSingleTable = 6;
public const int kSFNTLookupTrimmedArray = 8;
public const int kSFNTLookupVector = 10;

public using SFNTLookupTableFormat = UInt16;

public using SFNTLookupValue = UInt16;

public using SFNTLookupOffset = UInt16;

public using SFNTLookupKind = UInt32;

[Pack(2)]
public struct SFNTLookupBinarySearchHeader
{
    public UInt16 unitSize;
    public UInt16 nUnits;
    public UInt16 searchRange;
    public UInt16 entrySelector;
    public UInt16 rangeShift;
}

[Pack(2)]
public struct SFNTLookupArrayHeader
{
    public SFNTLookupValue[1] lookupValues;
}

[Pack(2)]
public struct SFNTLookupTrimmedArrayHeader
{
    public UInt16 firstGlyph;
    public UInt16 count;
    public SFNTLookupValue[1] valueArray;
}

[Pack(2)]
public struct SFNTLookupVectorHeader
{
    public UInt16 valueSize;
    public UInt16 firstGlyph;
    public UInt16 count;
    public UInt8[1] values;
}

[Pack(2)]
public struct SFNTLookupSegment
{
    public UInt16 lastGlyph;
    public UInt16 firstGlyph;
    public UInt16[1] value;
}

[Pack(2)]
public struct SFNTLookupSegmentHeader
{
    public SFNTLookupBinarySearchHeader binSearch;
    public SFNTLookupSegment[1] segments;
}

[Pack(2)]
public struct SFNTLookupSingle
{
    public UInt16 glyph;
    public UInt16[1] value;
}

[Pack(2)]
public struct SFNTLookupSingleHeader
{
    public SFNTLookupBinarySearchHeader binSearch;
    public SFNTLookupSingle[1] entries;
}

[Pack(2)]
public union SFNTLookupFormatSpecificHeader
{
    public SFNTLookupArrayHeader theArray;
    public SFNTLookupSegmentHeader segment;
    public SFNTLookupSingleHeader single;
    public SFNTLookupTrimmedArrayHeader trimmedArray;
    public SFNTLookupVectorHeader vector;
}

[Pack(2)]
public struct SFNTLookupTable
{
    public SFNTLookupTableFormat format;
    public SFNTLookupFormatSpecificHeader fsHeader;
}

public using SFNTLookupTablePtr = SFNTLookupTable*;

public using SFNTLookupTableHandle = SFNTLookupTablePtr*;

public const int kSTClassEndOfText = 0;
public const int kSTClassOutOfBounds = 1;
public const int kSTClassDeletedGlyph = 2;
public const int kSTClassEndOfLine = 3;
public const int kSTSetMark = 32768;
public const int kSTNoAdvance = 16384;
public const int kSTMarkEnd = 8192;
public const int kSTLigActionMask = 16383;
public const int kSTRearrVerbMask = 15;

public using STClass = UInt8;

public using STEntryIndex = UInt8;

[Pack(2)]
public struct STHeader
{
    public UInt8 filler;
    public STClass nClasses;
    public UInt16 classTableOffset;
    public UInt16 stateArrayOffset;
    public UInt16 entryTableOffset;
}

[Pack(2)]
public struct STClassTable
{
    public UInt16 firstGlyph;
    public UInt16 nGlyphs;
    public STClass[1] classes;
}

[Pack(2)]
public struct STEntryZero
{
    public UInt16 newState;
    public UInt16 flags;
}

[Pack(2)]
public struct STEntryOne
{
    public UInt16 newState;
    public UInt16 flags;
    public UInt16 offset1;
}

[Pack(2)]
public struct STEntryTwo
{
    public UInt16 newState;
    public UInt16 flags;
    public UInt16 offset1;
    public UInt16 offset2;
}

public const int kSTXHasLigAction = 8192;

public using STXClass = UInt16;

public using STXStateIndex = UInt16;

public using STXEntryIndex = UInt16;

[Pack(2)]
public struct STXHeader
{
    public UInt32 nClasses;
    public UInt32 classTableOffset;
    public UInt32 stateArrayOffset;
    public UInt32 entryTableOffset;
}

public using STXClassTable = SFNTLookupTable;

[Pack(2)]
public struct STXEntryZero
{
    public STXStateIndex newState;
    public UInt16 flags;
}

[Pack(2)]
public struct STXEntryOne
{
    public STXStateIndex newState;
    public UInt16 flags;
    public UInt16 index1;
}

[Pack(2)]
public struct STXEntryTwo
{
    public STXStateIndex newState;
    public UInt16 flags;
    public UInt16 index1;
    public UInt16 index2;
}

public const int kSTKCrossStreamReset = 8192;

public const int kLCARTag = 1818452338;
public const int kLCARCurrentVersion = 65536;
public const int kLCARLinearFormat = 0;
public const int kLCARCtlPointFormat = 1;

[Pack(2)]
public struct LcarCaretClassEntry
{
    public UInt16 count;
    public UInt16[1] partials;
}

[Pack(2)]
public struct LcarCaretTable
{
    public Fixed version;
    public UInt16 format;
    public SFNTLookupTable lookup;
}

public using LcarCaretTablePtr = LcarCaretTable*;

public const int kJUSTTag = 1786082164;
public const int kJUSTCurrentVersion = 65536;
public const int kJUSTStandardFormat = 0;
public const int kJUSTnoGlyphcode = 65535;
public const int kJUSTpcDecompositionAction = 0;
public const int kJUSTpcUnconditionalAddAction = 1;
public const int kJUSTpcConditionalAddAction = 2;
public const int kJUSTpcGlyphStretchAction = 3;
public const int kJUSTpcDuctilityAction = 4;
public const int kJUSTpcGlyphRepeatAddAction = 5;

public const int kJUSTKashidaPriority = 0;
public const int kJUSTSpacePriority = 1;
public const int kJUSTLetterPriority = 2;
public const int kJUSTNullPriority = 3;
public const int kJUSTPriorityCount = 4;

public const int kJUSTOverridePriority = 32768;
public const int kJUSTOverrideLimits = 16384;
public const int kJUSTOverrideUnlimited = 8192;
public const int kJUSTUnlimited = 4096;
public const int kJUSTPriorityMask = 3;

public using JustPCActionType = UInt16;

public using JustificationFlags = UInt16;

[Pack(2)]
public struct JustPCDecompositionAction
{
    public Fixed lowerLimit;
    public Fixed upperLimit;
    public UInt16 order;
    public UInt16 count;
    public UInt16[1] glyphs;
}

public using JustPCUnconditionalAddAction = UInt16;

[Pack(2)]
public struct JustPCConditionalAddAction
{
    public Fixed substThreshold;
    public UInt16 addGlyph;
    public UInt16 substGlyph;
}

[Pack(2)]
public struct JustPCDuctilityAction
{
    public UInt32 ductilityAxis;
    public Fixed minimumLimit;
    public Fixed noStretchValue;
    public Fixed maximumLimit;
}

[Pack(2)]
public struct JustPCGlyphRepeatAddAction
{
    public UInt16 flags;
    public UInt16 glyph;
}

[Pack(2)]
public struct JustPCActionSubrecord
{
    public UInt16 theClass;
    public JustPCActionType theType;
    public UInt32 length;
    public UInt32 data;
}

[Pack(2)]
public struct JustPCAction
{
    public UInt32 actionCount;
    public JustPCActionSubrecord[1] actions;
}

[Pack(2)]
public struct JustWidthDeltaEntry
{
    public UInt32 justClass;
    public Fixed beforeGrowLimit;
    public Fixed beforeShrinkLimit;
    public Fixed afterGrowLimit;
    public Fixed afterShrinkLimit;
    public JustificationFlags growFlags;
    public JustificationFlags shrinkFlags;
}

[Pack(2)]
public struct JustWidthDeltaGroup
{
    public UInt32 count;
    public JustWidthDeltaEntry[1] entries;
}

[Pack(2)]
public struct JustPostcompTable
{
    public SFNTLookupTable lookupTable;
}

[Pack(2)]
public struct JustDirectionTable
{
    public UInt16 justClass;
    public UInt16 widthDeltaClusters;
    public UInt16 postcomp;
    public SFNTLookupTable lookup;
}

[Pack(2)]
public struct JustTable
{
    public Fixed version;
    public UInt16 format;
    public UInt16 horizHeaderOffset;
    public UInt16 vertHeaderOffset;
}

public const int kOPBDTag = 1869636196;
public const int kOPBDCurrentVersion = 65536;
public const int kOPBDDistanceFormat = 0;
public const int kOPBDControlPointFormat = 1;

public using OpbdTableFormat = UInt16;

[Pack(2)]
public struct OpbdSideValues
{
    public SInt16 leftSideShift;
    public SInt16 topSideShift;
    public SInt16 rightSideShift;
    public SInt16 bottomSideShift;
}

[Pack(2)]
public struct OpbdTable
{
    public Fixed version;
    public OpbdTableFormat format;
    public SFNTLookupTable lookupTable;
}

public const int kMORTTag = 1836020340;
public const int kMORTCurrentVersion = 65536;
public const int kMORTCoverVertical = 32768;
public const int kMORTCoverDescending = 16384;
public const int kMORTCoverIgnoreVertical = 8192;
public const int kMORTCoverTypeMask = 15;
public const int kMORTRearrangementType = 0;
public const int kMORTContextualType = 1;
public const int kMORTLigatureType = 2;
public const int kMORTSwashType = 4;
public const int kMORTInsertionType = 5;
public const int kMORTLigLastAction = -2147483648;
public const int kMORTLigStoreLigature = 1073741824;
public const int kMORTLigFormOffsetMask = 1073741823;
public const int kMORTLigFormOffsetShift = 2;
public const int kMORTraNoAction = 0;
public const int kMORTraxA = 1;
public const int kMORTraDx = 2;
public const int kMORTraDxA = 3;
public const int kMORTraxAB = 4;
public const int kMORTraxBA = 5;
public const int kMORTraCDx = 6;
public const int kMORTraDCx = 7;
public const int kMORTraCDxA = 8;
public const int kMORTraDCxA = 9;
public const int kMORTraDxAB = 10;
public const int kMORTraDxBA = 11;
public const int kMORTraCDxAB = 12;
public const int kMORTraCDxBA = 13;
public const int kMORTraDCxAB = 14;
public const int kMORTraDCxBA = 15;
public const int kMORTDoInsertionsBefore = 128;
public const int kMORTIsSplitVowelPiece = 64;
public const int kMORTInsertionsCountMask = 63;
public const int kMORTCurrInsertKashidaLike = 8192;
public const int kMORTMarkInsertKashidaLike = 4096;
public const int kMORTCurrInsertBefore = 2048;
public const int kMORTMarkInsertBefore = 1024;
public const int kMORTMarkJustTableCountMask = 16256;
public const int kMORTMarkJustTableCountShift = 7;
public const int kMORTCurrJustTableCountMask = 127;
public const int kMORTCurrJustTableCountShift = 0;
public const int kMORTCurrInsertCountMask = 992;
public const int kMORTCurrInsertCountShift = 5;
public const int kMORTMarkInsertCountMask = 31;
public const int kMORTMarkInsertCountShift = 0;

public using MortSubtableMaskFlags = UInt32;

public using MortLigatureActionEntry = UInt32;

[Pack(2)]
public struct MortRearrangementSubtable
{
    public STHeader header;
}

[Pack(2)]
public struct MortContextualSubtable
{
    public STHeader header;
    public UInt16 substitutionTableOffset;
}

[Pack(2)]
public struct MortLigatureSubtable
{
    public STHeader header;
    public UInt16 ligatureActionTableOffset;
    public UInt16 componentTableOffset;
    public UInt16 ligatureTableOffset;
}

[Pack(2)]
public struct MortSwashSubtable
{
    public SFNTLookupTable lookup;
}

[Pack(2)]
public struct MortInsertionSubtable
{
    public STHeader header;
}

[Pack(2)]
public union MortSpecificSubtable
{
    public MortRearrangementSubtable rearrangement;
    public MortContextualSubtable contextual;
    public MortLigatureSubtable ligature;
    public MortSwashSubtable swash;
    public MortInsertionSubtable insertion;
}

[Pack(2)]
public struct MortSubtable
{
    public UInt16 length;
    public UInt16 coverage;
    public MortSubtableMaskFlags flags;
    public MortSpecificSubtable u;
}

[Pack(2)]
public struct MortFeatureEntry
{
    public UInt16 featureType;
    public UInt16 featureSelector;
    public MortSubtableMaskFlags enableFlags;
    public MortSubtableMaskFlags disableFlags;
}

[Pack(2)]
public struct MortChain
{
    public MortSubtableMaskFlags defaultFlags;
    public UInt32 length;
    public UInt16 nFeatures;
    public UInt16 nSubtables;
    public MortFeatureEntry[1] featureEntries;
}

[Pack(2)]
public struct MortTable
{
    public Fixed version;
    public UInt32 nChains;
    public MortChain[1] chains;
}

public const int kMORXTag = 1836020344;
public const int kMORXCurrentVersion = 131072;
public const int kMORXCoverVertical = -2147483648;
public const int kMORXCoverDescending = 1073741824;
public const int kMORXCoverIgnoreVertical = 536870912;
public const int kMORXCoverLogicalOrder = 268435456;
public const int kMORXCoverTypeMask = 255;

[Pack(2)]
public struct MorxRearrangementSubtable
{
    public STXHeader header;
}

[Pack(2)]
public struct MorxContextualSubtable
{
    public STXHeader header;
    public UInt32 substitutionTableOffset;
}

[Pack(2)]
public struct MorxLigatureSubtable
{
    public STXHeader header;
    public UInt32 ligatureActionTableOffset;
    public UInt32 componentTableOffset;
    public UInt32 ligatureTableOffset;
}

[Pack(2)]
public struct MorxInsertionSubtable
{
    public STXHeader header;
    public UInt32 insertionGlyphTableOffset;
}

[Pack(2)]
public union MorxSpecificSubtable
{
    public MorxRearrangementSubtable rearrangement;
    public MorxContextualSubtable contextual;
    public MorxLigatureSubtable ligature;
    public MortSwashSubtable swash;
    public MorxInsertionSubtable insertion;
}

[Pack(2)]
public struct MorxSubtable
{
    public UInt32 length;
    public UInt32 coverage;
    public MortSubtableMaskFlags flags;
    public MorxSpecificSubtable u;
}

[Pack(2)]
public struct MorxChain
{
    public MortSubtableMaskFlags defaultFlags;
    public UInt32 length;
    public UInt32 nFeatures;
    public UInt32 nSubtables;
    public MortFeatureEntry[1] featureEntries;
}

[Pack(2)]
public struct MorxTable
{
    public Fixed version;
    public UInt32 nChains;
    public MorxChain[1] chains;
}

public const int kPROPTag = 1886547824;
public const int kPROPCurrentVersion = 196608;
public const int kPROPPairOffsetShift = 8;
public const int kPROPPairOffsetSign = 7;
public const int kPROPIsFloaterMask = 32768;
public const int kPROPCanHangLTMask = 16384;
public const int kPROPCanHangRBMask = 8192;
public const int kPROPUseRLPairMask = 4096;
public const int kPROPPairOffsetMask = 3840;
public const int kPROPRightConnectMask = 128;
public const int kPROPZeroReserved = 96;
public const int kPROPDirectionMask = 31;

public const int kPROPLDirectionClass = 0;
public const int kPROPRDirectionClass = 1;
public const int kPROPALDirectionClass = 2;
public const int kPROPENDirectionClass = 3;
public const int kPROPESDirectionClass = 4;
public const int kPROPETDirectionClass = 5;
public const int kPROPANDirectionClass = 6;
public const int kPROPCSDirectionClass = 7;
public const int kPROPPSDirectionClass = 8;
public const int kPROPSDirectionClass = 9;
public const int kPROPWSDirectionClass = 10;
public const int kPROPONDirectionClass = 11;
public const int kPROPSENDirectionClass = 12;
public const int kPROPLREDirectionClass = 13;
public const int kPROPLRODirectionClass = 14;
public const int kPROPRLEDirectionClass = 15;
public const int kPROPRLODirectionClass = 16;
public const int kPROPPDFDirectionClass = 17;
public const int kPROPNSMDirectionClass = 18;
public const int kPROPBNDirectionClass = 19;
public const int kPROPNumDirectionClasses = 20;

public using PropCharProperties = UInt16;

[Pack(2)]
public struct PropTable
{
    public Fixed version;
    public UInt16 format;
    public PropCharProperties defaultProps;
    public SFNTLookupTable lookup;
}

[Pack(2)]
public struct PropLookupSegment
{
    public UInt16 lastGlyph;
    public UInt16 firstGlyph;
    public UInt16 value;
}

[Pack(2)]
public struct PropLookupSingle
{
    public UInt16 glyph;
    public PropCharProperties props;
}

public const int kTRAKTag = 1953653099;
public const int kTRAKCurrentVersion = 65536;
public const int kTRAKUniformFormat = 0;

public using TrakValue = SInt16;

[Pack(2)]
public struct TrakTableEntry
{
    public Fixed track;
    public UInt16 nameTableIndex;
    public UInt16 sizesOffset;
}

[Pack(2)]
public struct TrakTableData
{
    public UInt16 nTracks;
    public UInt16 nSizes;
    public UInt32 sizeTableOffset;
    public TrakTableEntry[1] trakTable;
}

[Pack(2)]
public struct TrakTable
{
    public Fixed version;
    public UInt16 format;
    public UInt16 horizOffset;
    public UInt16 vertOffset;
}

public const int kKERNTag = 1801810542;
public const int kKERNCurrentVersion = 65536;
public const int kKERNVertical = 32768;
public const int kKERNResetCrossStream = 32768;
public const int kKERNCrossStream = 16384;
public const int kKERNVariation = 8192;
public const int kKERNUnusedBits = 7936;
public const int kKERNFormatMask = 255;

public const int kKERNOrderedList = 0;
public const int kKERNStateTable = 1;
public const int kKERNSimpleArray = 2;
public const int kKERNIndexArray = 3;

public const int kKERNLineStart = 1;
public const int kKERNLineEndKerning = 2;
public const int kKERNNoCrossKerning = 4;
public const int kKERNNotesRequested = 8;
public const int kKERNNoStakeNote = 1;
public const int kKERNCrossStreamResetNote = 2;
public const int kKERNNotApplied = 1;

public using KernTableFormat = UInt8;

public using KernSubtableInfo = UInt16;

public using KernKerningValue = SInt16;

public using KernArrayOffset = UInt16;

[Pack(2)]
public struct KernVersion0Header
{
    public UInt16 version;
    public UInt16 nTables;
    public UInt16[1] firstSubtable;
}

[Pack(2)]
public struct KernTableHeader
{
    public Fixed version;
    public SInt32 nTables;
    public UInt16[1] firstSubtable;
}

public using KernTableHeaderPtr = KernTableHeader*;

public using KernTableHeaderHandle = KernTableHeaderPtr*;

[Pack(2)]
public struct KernKerningPair
{
    public UInt16 left;
    public UInt16 right;
}

[Pack(2)]
public struct KernOrderedListEntry
{
    public KernKerningPair pair;
    public KernKerningValue value;
}

public using KernOrderedListEntryPtr = KernOrderedListEntry*;

[Pack(2)]
public struct KernOrderedListHeader
{
    public UInt16 nPairs;
    public UInt16 searchRange;
    public UInt16 entrySelector;
    public UInt16 rangeShift;
    public UInt16[1] table;
}

[Pack(2)]
public struct KernStateHeader
{
    public STHeader header;
    public UInt16 valueTable;
    public UInt8[1] firstTable;
}

[Pack(2)]
public struct KernStateEntry
{
    public UInt16 newState;
    public UInt16 flags;
}

[Pack(2)]
public struct KernOffsetTable
{
    public UInt16 firstGlyph;
    public UInt16 nGlyphs;
    public KernArrayOffset[1] offsetTable;
}

public using KernOffsetTablePtr = KernOffsetTable*;

[Pack(2)]
public struct KernSimpleArrayHeader
{
    public UInt16 rowWidth;
    public UInt16 leftOffsetTable;
    public UInt16 rightOffsetTable;
    public KernArrayOffset theArray;
    public UInt16[1] firstTable;
}

[Pack(2)]
public struct KernIndexArrayHeader
{
    public UInt16 glyphCount;
    public UInt8 kernValueCount;
    public UInt8 leftClassCount;
    public UInt8 rightClassCount;
    public UInt8 flags;
    public SInt16[1] kernValue;
    public UInt8[1] leftClass;
    public UInt8[1] rightClass;
    public UInt8[1] kernIndex;
}

[Pack(2)]
public union KernFormatSpecificHeader
{
    public KernOrderedListHeader orderedList;
    public KernStateHeader stateTable;
    public KernSimpleArrayHeader simpleArray;
    public KernIndexArrayHeader indexArray;
}

[Pack(2)]
public struct KernVersion0SubtableHeader
{
    public UInt16 version;
    public UInt16 length;
    public KernSubtableInfo stInfo;
    public KernFormatSpecificHeader fsHeader;
}

[Pack(2)]
public struct KernSubtableHeader
{
    public SInt32 length;
    public KernSubtableInfo stInfo;
    public SInt16 tupleIndex;
    public KernFormatSpecificHeader fsHeader;
}

public using KernSubtableHeaderPtr = KernSubtableHeader*;

public const int kKERXTag = 1801810552;
public const int kKERXCurrentVersion = 131072;
public const int kKERXVertical = -2147483648;
public const int kKERXResetCrossStream = 32768;
public const int kKERXCrossStream = 1073741824;
public const int kKERXVariation = 536870912;
public const int kKERXDescending = 268435456;
public const int kKERXUnusedBits = 268435200;
public const int kKERXFormatMask = 255;

public const int kKERXOrderedList = 0;
public const int kKERXStateTable = 1;
public const int kKERXSimpleArray = 2;
public const int kKERXControlPoint = 4;
public const int kKERXIndexArray = 6;

public const int kKERXLineStart = 1;
public const int kKERXLineEndKerning = 2;
public const int kKERXNoCrossKerning = 4;
public const int kKERXNotesRequested = 8;
public const int kKERXNoStakeNote = 1;
public const int kKERXCrossStreamResetNote = 2;
public const int kKERXNotApplied = 1;

public const uint kKERXActionTypeMask = 3221225472u;
public const uint kKERXActionTypeControlPoints = 0;
public const uint kKERXActionTypeAnchorPoints = 1073741824;
public const uint kKERXActionTypeCoordinates = 2147483648u;
public const uint kKERXUnusedFlags = 1056964608;
public const uint kKERXActionOffsetMask = 16777215;

public const int kKERXValuesAreLong = 1;

public using KerxSubtableCoverage = UInt32;

public using KerxArrayOffset = UInt32;

[Pack(2)]
public struct KerxTableHeader
{
    public Fixed version;
    public UInt32 nTables;
    public UInt32[1] firstSubtable;
}

public using KerxTableHeaderPtr = KerxTableHeader*;

public using KerxTableHeaderHandle = KerxTableHeaderPtr*;

[Pack(2)]
public struct KerxKerningPair
{
    public UInt16 left;
    public UInt16 right;
}

[Pack(2)]
public struct KerxOrderedListEntry
{
    public KerxKerningPair pair;
    public KernKerningValue value;
}

public using KerxOrderedListEntryPtr = KerxOrderedListEntry*;

[Pack(2)]
public struct KerxOrderedListHeader
{
    public UInt32 nPairs;
    public UInt32 searchRange;
    public UInt32 entrySelector;
    public UInt32 rangeShift;
    public UInt32[1] table;
}

[Pack(2)]
public struct KerxStateHeader
{
    public STXHeader header;
    public UInt32 valueTable;
    public UInt8[1] firstTable;
}

[Pack(2)]
public struct KerxStateEntry
{
    public UInt16 newState;
    public UInt16 flags;
    public UInt16 valueIndex;
}

[Pack(2)]
public struct KerxControlPointHeader
{
    public STXHeader header;
    public UInt32 flags;
    public UInt8[1] firstTable;
}

[Pack(2)]
public struct KerxControlPointEntry
{
    public UInt16 newState;
    public UInt16 flags;
    public UInt16 actionIndex;
}

[Pack(2)]
public struct KerxControlPointAction
{
    public UInt16 markControlPoint;
    public UInt16 currControlPoint;
}

[Pack(2)]
public struct KerxAnchorPointAction
{
    public UInt16 markAnchorPoint;
    public UInt16 currAnchorPoint;
}

[Pack(2)]
public struct KerxCoordinateAction
{
    public UInt16 markX;
    public UInt16 markY;
    public UInt16 currX;
    public UInt16 currY;
}

[Pack(2)]
public struct KerxSimpleArrayHeader
{
    public UInt32 rowWidth;
    public UInt32 leftOffsetTable;
    public UInt32 rightOffsetTable;
    public KerxArrayOffset theArray;
    public UInt32[1] firstTable;
}

[Pack(2)]
public struct KerxIndexArrayHeader
{
    public UInt32 flags;
    public UInt16 rowCount;
    public UInt16 columnCount;
    public UInt32 rowIndexTableOffset;
    public UInt32 columnIndexTableOffset;
    public UInt32 kerningArrayOffset;
    public UInt32 kerningVectorOffset;
}

[Pack(2)]
public union KerxFormatSpecificHeader
{
    public KerxOrderedListHeader orderedList;
    public KerxStateHeader stateTable;
    public KerxSimpleArrayHeader simpleArray;
    public KerxIndexArrayHeader indexArray;
    public KerxControlPointHeader controlPoint;
}

[Pack(2)]
public struct KerxSubtableHeader
{
    public UInt32 length;
    public KerxSubtableCoverage stInfo;
    public UInt32 tupleCount;
    public KerxFormatSpecificHeader fsHeader;
}

public using KerxSubtableHeaderPtr = KerxSubtableHeader*;

public const int kBSLNTag = 1651731566;
public const int kBSLNCurrentVersion = 65536;
public const int kBSLNDistanceFormatNoMap = 0;
public const int kBSLNDistanceFormatWithMap = 1;
public const int kBSLNControlPointFormatNoMap = 2;
public const int kBSLNControlPointFormatWithMap = 3;

public const int kBSLNRomanBaseline = 0;
public const int kBSLNIdeographicCenterBaseline = 1;
public const int kBSLNIdeographicLowBaseline = 2;
public const int kBSLNHangingBaseline = 3;
public const int kBSLNMathBaseline = 4;
public const int kBSLNIdeographicHighBaseline = 5;
public const int kBSLNLastBaseline = 31;
public const int kBSLNNumBaselineClasses = 32;
public const int kBSLNNoBaseline = 255;
public const int kBSLNNoBaselineOverride = 255;

public using BslnBaselineClass = UInt32;

public using BslnBaselineRecord = Fixed[32];

[Pack(2)]
public struct BslnFormat0Part
{
    public SInt16[32] deltas;
}

[Pack(2)]
public struct BslnFormat1Part
{
    public SInt16[32] deltas;
    public SFNTLookupTable mappingData;
}

[Pack(2)]
public struct BslnFormat2Part
{
    public UInt16 stdGlyph;
    public SInt16[32] ctlPoints;
}

[Pack(2)]
public struct BslnFormat3Part
{
    public UInt16 stdGlyph;
    public SInt16[32] ctlPoints;
    public SFNTLookupTable mappingData;
}

[Pack(2)]
public union BslnFormatUnion
{
    public BslnFormat0Part fmt0Part;
    public BslnFormat1Part fmt1Part;
    public BslnFormat2Part fmt2Part;
    public BslnFormat3Part fmt3Part;
}

public using BslnTableFormat = UInt16;

[Pack(2)]
public struct BslnTable
{
    public Fixed version;
    public BslnTableFormat format;
    public UInt16 defaultBaseline;
    public BslnFormatUnion parts;
}

public using BslnTablePtr = BslnTable*;

[Pack(2)]
public struct ALMXHeader
{
    public Fixed Version;
    public UInt16 Flags;
    public UInt16 NMasters;
    public UInt16 FirstGlyph;
    public UInt16 LastGlyph;
    public SFNTLookupTable lookup;
}

[Pack(2)]
public struct ALMXGlyphEntry
{
    public SInt16 GlyphIndexOffset;
    public SInt16 HorizontalAdvance;
    public SInt16 XOffsetToHOrigin;
    public SInt16 VerticalAdvance;
    public SInt16 YOffsetToVOrigin;
}

[Pack(2)]
public struct ROTAHeader
{
    public Fixed Version;
    public UInt16 Flags;
    public UInt16 NMasters;
    public UInt16 FirstGlyph;
    public UInt16 LastGlyph;
    public SFNTLookupTable lookup;
}

[Pack(2)]
public struct ROTAGlyphEntry
{
    public SInt16 GlyphIndexOffset;
    public SInt16 HBaselineOffset;
    public SInt16 VBaselineOffset;
}

public const int kANKRCurrentVersion = 0;

[Pack(2)]
public struct AnchorPoint
{
    public SInt16 x;
    public SInt16 y;
}

[Pack(2)]
public struct AnchorPointTable
{
    public UInt32 nPoints;
    public AnchorPoint[1] points;
}

[Pack(2)]
public struct AnkrTable
{
    public UInt16 version;
    public UInt16 flags;
    public UInt32 lookupTableOffset;
    public UInt32 anchorPointTableOffset;
}

public const int kLTAGCurrentVersion = 1;

[Pack(2)]
public struct LtagStringRange
{
    public UInt16 offset;
    public UInt16 length;
}

[Pack(2)]
public struct LtagTable
{
    public UInt32 version;
    public UInt32 flags;
    public UInt32 numTags;
    public LtagStringRange[1] tagRange;
}

#endif
