// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Cinematic.framework (CNObjectTracker.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Cinematic;

import MacOS.CoreFoundation;
import MacOS.CoreMedia;
import MacOS.CoreVideo;
import MacOS.Foundation;
import MacOS.Metal;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Cinematic")

public extern objc class CNBoundsPrediction : NSObject, NSCopying, NSMutableCopying
{
    [Selector("normalizedBounds", "setNormalizedBounds:")] public CGRect NormalizedBounds { get; set; }
    [Selector("confidence", "setConfidence:")] public float Confidence { get; set; }
}

public extern objc class CNObjectTracker : NSObject
{
    [Selector("isSupported")] public static bool IsSupported { get; }
    [Selector("initWithCommandQueue:")] public Self InitWithCommandQueue(MTLCommandQueue commandQueue);
    [Selector("findObjectAtPoint:sourceImage:")] public CNBoundsPrediction? FindObjectAtPointSourceImage(CGPoint point, CVPixelBufferRef sourceImage);
    [Selector("startTrackingAt:within:sourceImage:sourceDisparity:")] public bool StartTrackingAtWithinSourceImageSourceDisparity(CMTime time, CGRect normalizedBounds, CVPixelBufferRef sourceImage, CVPixelBufferRef sourceDisparity);
    [Selector("continueTrackingAt:sourceImage:sourceDisparity:")] public CNBoundsPrediction? ContinueTrackingAtSourceImageSourceDisparity(CMTime time, CVPixelBufferRef sourceImage, CVPixelBufferRef sourceDisparity);
    [Selector("finishDetectionTrack")] public CNDetectionTrack FinishDetectionTrack();
    [Selector("resetDetectionTrack")] public void ResetDetectionTrack();
}

#endif
