// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreServices.framework (Metadata_MDQuery.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreServices;

import MacOS.CoreFoundation;
import MacOS.System;

#if MACOS

#pragma comment(framework, "CoreServices")

public struct __MDQuery;

public using MDQueryRef = __MDQuery*;

public enum MDQueryOptionFlags : int
{
    Synchronous = 1,
    WantsUpdates = 4,
    AllowFSTranslation = 8,
}

public extern "C" CFTypeID MDQueryGetTypeID();

public extern "C" MDQueryRef MDQueryCreate(CFAllocatorRef allocator, CFStringRef queryString, CFArrayRef valueListAttrs, CFArrayRef sortingAttrs);

public extern "C" MDQueryRef MDQueryCreateSubset(CFAllocatorRef allocator, MDQueryRef query, CFStringRef queryString, CFArrayRef valueListAttrs, CFArrayRef sortingAttrs);

public extern "C" MDQueryRef MDQueryCreateForItems(CFAllocatorRef allocator, CFStringRef queryString, CFArrayRef valueListAttrs, CFArrayRef sortingAttrs, CFArrayRef items);

public extern "C" CFStringRef MDQueryCopyQueryString(MDQueryRef query);

public extern "C" CFArrayRef MDQueryCopyValueListAttributes(MDQueryRef query);

public extern "C" CFArrayRef MDQueryCopySortingAttributes(MDQueryRef query);

public struct MDQueryBatchingParams
{
    public nuint first_max_num;
    public nuint first_max_ms;
    public nuint progress_max_num;
    public nuint progress_max_ms;
    public nuint update_max_num;
    public nuint update_max_ms;
}

public extern "C" MDQueryBatchingParams MDQueryGetBatchingParameters(MDQueryRef query);

public extern "C" void MDQuerySetBatchingParameters(MDQueryRef query, MDQueryBatchingParams params);

public delegate void* MDQueryCreateResultFunction(MDQueryRef arg0, MDItemRef arg1, void* arg2);

public extern "C" void MDQuerySetCreateResultFunction(MDQueryRef query, MDQueryCreateResultFunction func, void* context, CFArrayCallBacks* cb);

public delegate void* MDQueryCreateValueFunction(MDQueryRef arg0, CFStringRef arg1, CFTypeRef arg2, void* arg3);

public extern "C" void MDQuerySetCreateValueFunction(MDQueryRef query, MDQueryCreateValueFunction func, void* context, CFArrayCallBacks* cb);

public extern "C" Boolean MDQueryExecute(MDQueryRef query, CFOptionFlags optionFlags);

public extern "C" void MDQueryStop(MDQueryRef query);

public extern "C" void MDQueryDisableUpdates(MDQueryRef query);

public extern "C" void MDQueryEnableUpdates(MDQueryRef query);

public extern "C" Boolean MDQueryIsGatheringComplete(MDQueryRef query);

public extern "C" CFIndex MDQueryGetResultCount(MDQueryRef query);

public extern "C" void* MDQueryGetResultAtIndex(MDQueryRef query, CFIndex idx);

public extern "C" CFIndex MDQueryGetIndexOfResult(MDQueryRef query, void* result);

public extern "C" void* MDQueryGetAttributeValueOfResultAtIndex(MDQueryRef query, CFStringRef name, CFIndex idx);

public extern "C" CFArrayRef MDQueryCopyValuesOfAttribute(MDQueryRef query, CFStringRef name);

public extern "C" CFIndex MDQueryGetCountOfResultsWithAttributeValue(MDQueryRef query, CFStringRef name, CFTypeRef value);

public extern "C" Boolean MDQuerySetSortOrder(MDQueryRef query, CFArrayRef sortingAttrs);

public enum MDQuerySortOptionFlags : int
{
    kMDQueryReverseSortOrderFlag = 1,
}

public extern "C" Boolean MDQuerySetSortOptionFlagsForAttribute(MDQueryRef query, CFStringRef fieldName, uint flags);

public extern "C" uint MDQueryGetSortOptionFlagsForAttribute(MDQueryRef query, CFStringRef fieldName);

public delegate CFComparisonResult MDQuerySortComparatorFunction(CFTypeRef* arg0, CFTypeRef* arg1, void* arg2);

public extern "C" void MDQuerySetSortComparator(MDQueryRef query, MDQuerySortComparatorFunction comparator, void* context);

public objc closure CFComparisonResult MDQuerySetSortComparatorBlockComparatorBlock(CFTypeRef* arg0, CFTypeRef* arg1);

public extern "C" void MDQuerySetSortComparatorBlock(MDQueryRef query, MDQuerySetSortComparatorBlockComparatorBlock comparator);

public extern "C" CFStringRef kMDQueryProgressNotification;

public extern "C" CFStringRef kMDQueryDidFinishNotification;

public extern "C" CFStringRef kMDQueryDidUpdateNotification;

public extern "C" CFStringRef kMDQueryUpdateAddedItems;

public extern "C" CFStringRef kMDQueryUpdateChangedItems;

public extern "C" CFStringRef kMDQueryUpdateRemovedItems;

public extern "C" CFStringRef kMDQueryResultContentRelevance;

public extern "C" void MDQuerySetSearchScope(MDQueryRef query, CFArrayRef scopeDirectories, OptionBits scopeOptions);

public extern "C" CFStringRef kMDQueryScopeHome;

public extern "C" CFStringRef kMDQueryScopeComputer;

public extern "C" CFStringRef kMDQueryScopeNetwork;

public extern "C" CFStringRef kMDQueryScopeAllIndexed;

public extern "C" CFStringRef kMDQueryScopeComputerIndexed;

public extern "C" CFStringRef kMDQueryScopeNetworkIndexed;

public extern "C" void MDQuerySetMaxCount(MDQueryRef query, CFIndex size);

#endif
