// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Foundation.framework (NSHTTPCookieStorage.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Foundation;

import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Foundation")

public enum NSHTTPCookieAcceptPolicy : ulong
{
    Always = 0,
    Never = 1,
    OnlyFromMainDocumentDomain = 2,
}

public extern objc class NSHTTPCookieStorage : NSObject
{
    [Selector("sharedHTTPCookieStorage")]
    public static NSHTTPCookieStorage SharedHTTPCookieStorage { get; }
    [Selector("cookies")]
    public NSArray? Cookies { get; }
    [Selector("cookieAcceptPolicy", "setCookieAcceptPolicy:")]
    public NSHTTPCookieAcceptPolicy CookieAcceptPolicy { get; set; }
    [Selector("sharedCookieStorageForGroupContainerIdentifier:")]
    public static NSHTTPCookieStorage SharedCookieStorageForGroupContainerIdentifier(NSString identifier);
    [Selector("setCookie:")]
    public void SetCookie(NSHTTPCookie cookie);
    [Selector("deleteCookie:")]
    public void DeleteCookie(NSHTTPCookie cookie);
    [Selector("removeCookiesSinceDate:")]
    public void RemoveCookiesSinceDate(NSDate date);
    [Selector("cookiesForURL:")]
    public NSArray? CookiesForURL(NSURL URL);
    [Selector("setCookies:forURL:mainDocumentURL:")]
    public void SetCookiesForURLMainDocumentURL(NSArray cookies, NSURL? URL, NSURL? mainDocumentURL);
    [Selector("sortedCookiesUsingDescriptors:")]
    public NSArray SortedCookiesUsingDescriptors(NSArray sortOrder);
}

public objc closure void NSHTTPCookieStorageGetCookiesForTaskCompletionHandlerCompletionHandlerBlock(NSArray? arg0);

/// NSURLSessionTaskAdditions, a category of NSHTTPCookieStorage.
public extern objc class NSHTTPCookieStorage
{
    [Selector("storeCookies:forTask:")]
    public void StoreCookiesForTask(NSArray cookies, NSURLSessionTask task);
    [Selector("getCookiesForTask:completionHandler:")]
    public void GetCookiesForTaskCompletionHandler(NSURLSessionTask task, NSHTTPCookieStorageGetCookiesForTaskCompletionHandlerCompletionHandlerBlock completionHandler);
}

/// Deprecated in macOS 10.11.
public extern "C" NSNotificationName NSHTTPCookieManagerAcceptPolicyChangedNotification;

public extern "C" NSNotificationName NSHTTPCookieManagerCookiesChangedNotification;

#endif
