// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Foundation.framework (NSIndexSet.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Foundation;

import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Foundation")

public objc closure void NSIndexSetEnumerateIndexesUsingBlockBlock(NSUInteger arg0, bool* arg1);

public objc closure void NSIndexSetEnumerateIndexesWithOptionsUsingBlockBlock(NSUInteger arg0, bool* arg1);

public objc closure void NSIndexSetEnumerateIndexesInRangeOptionsUsingBlockBlock(NSUInteger arg0, bool* arg1);

public objc closure bool NSIndexSetIndexPassingTestPredicateBlock(NSUInteger arg0, bool* arg1);

public objc closure bool NSIndexSetIndexWithOptionsPassingTestPredicateBlock(NSUInteger arg0, bool* arg1);

public objc closure bool NSIndexSetIndexInRangeOptionsPassingTestPredicateBlock(NSUInteger arg0, bool* arg1);

public objc closure bool NSIndexSetIndexesPassingTestPredicateBlock(NSUInteger arg0, bool* arg1);

public objc closure bool NSIndexSetIndexesWithOptionsPassingTestPredicateBlock(NSUInteger arg0, bool* arg1);

public objc closure bool NSIndexSetIndexesInRangeOptionsPassingTestPredicateBlock(NSUInteger arg0, bool* arg1);

public objc closure void NSIndexSetEnumerateRangesUsingBlockBlock(NSRange arg0, bool* arg1);

public objc closure void NSIndexSetEnumerateRangesWithOptionsUsingBlockBlock(NSRange arg0, bool* arg1);

public objc closure void NSIndexSetEnumerateRangesInRangeOptionsUsingBlockBlock(NSRange arg0, bool* arg1);

public extern objc class NSIndexSet : NSObject, NSCopying, NSMutableCopying, NSSecureCoding
{
    [Selector("count")]
    public NSUInteger Count { get; }
    [Selector("firstIndex")]
    public NSUInteger FirstIndex { get; }
    [Selector("lastIndex")]
    public NSUInteger LastIndex { get; }
    [Selector("indexSet")]
    public static Self IndexSet();
    [Selector("indexSetWithIndex:")]
    public static Self IndexSetWithIndex(NSUInteger value);
    [Selector("indexSetWithIndexesInRange:")]
    public static Self IndexSetWithIndexesInRange(NSRange range);
    [Selector("initWithIndexesInRange:")]
    public Self InitWithIndexesInRange(NSRange range);
    [Selector("initWithIndexSet:")]
    public Self InitWithIndexSet(NSIndexSet indexSet);
    [Selector("initWithIndex:")]
    public Self InitWithIndex(NSUInteger value);
    [Selector("isEqualToIndexSet:")]
    public bool IsEqualToIndexSet(NSIndexSet indexSet);
    [Selector("indexGreaterThanIndex:")]
    public NSUInteger IndexGreaterThanIndex(NSUInteger value);
    [Selector("indexLessThanIndex:")]
    public NSUInteger IndexLessThanIndex(NSUInteger value);
    [Selector("indexGreaterThanOrEqualToIndex:")]
    public NSUInteger IndexGreaterThanOrEqualToIndex(NSUInteger value);
    [Selector("indexLessThanOrEqualToIndex:")]
    public NSUInteger IndexLessThanOrEqualToIndex(NSUInteger value);
    [Selector("getIndexes:maxCount:inIndexRange:")]
    public NSUInteger GetIndexesMaxCountInIndexRange(NSUInteger* indexBuffer, NSUInteger bufferSize, NSRangePointer range);
    [Selector("countOfIndexesInRange:")]
    public NSUInteger CountOfIndexesInRange(NSRange range);
    [Selector("containsIndex:")]
    public bool ContainsIndex(NSUInteger value);
    [Selector("containsIndexesInRange:")]
    public bool ContainsIndexesInRange(NSRange range);
    [Selector("containsIndexes:")]
    public bool ContainsIndexes(NSIndexSet indexSet);
    [Selector("intersectsIndexesInRange:")]
    public bool IntersectsIndexesInRange(NSRange range);
    [Selector("enumerateIndexesUsingBlock:")]
    public void EnumerateIndexesUsingBlock(NSIndexSetEnumerateIndexesUsingBlockBlock block);
    [Selector("enumerateIndexesWithOptions:usingBlock:")]
    public void EnumerateIndexesWithOptionsUsingBlock(NSEnumerationOptions opts, NSIndexSetEnumerateIndexesWithOptionsUsingBlockBlock block);
    [Selector("enumerateIndexesInRange:options:usingBlock:")]
    public void EnumerateIndexesInRangeOptionsUsingBlock(NSRange range, NSEnumerationOptions opts, NSIndexSetEnumerateIndexesInRangeOptionsUsingBlockBlock block);
    [Selector("indexPassingTest:")]
    public NSUInteger IndexPassingTest(NSIndexSetIndexPassingTestPredicateBlock predicate);
    [Selector("indexWithOptions:passingTest:")]
    public NSUInteger IndexWithOptionsPassingTest(NSEnumerationOptions opts, NSIndexSetIndexWithOptionsPassingTestPredicateBlock predicate);
    [Selector("indexInRange:options:passingTest:")]
    public NSUInteger IndexInRangeOptionsPassingTest(NSRange range, NSEnumerationOptions opts, NSIndexSetIndexInRangeOptionsPassingTestPredicateBlock predicate);
    [Selector("indexesPassingTest:")]
    public NSIndexSet IndexesPassingTest(NSIndexSetIndexesPassingTestPredicateBlock predicate);
    [Selector("indexesWithOptions:passingTest:")]
    public NSIndexSet IndexesWithOptionsPassingTest(NSEnumerationOptions opts, NSIndexSetIndexesWithOptionsPassingTestPredicateBlock predicate);
    [Selector("indexesInRange:options:passingTest:")]
    public NSIndexSet IndexesInRangeOptionsPassingTest(NSRange range, NSEnumerationOptions opts, NSIndexSetIndexesInRangeOptionsPassingTestPredicateBlock predicate);
    [Selector("enumerateRangesUsingBlock:")]
    public void EnumerateRangesUsingBlock(NSIndexSetEnumerateRangesUsingBlockBlock block);
    [Selector("enumerateRangesWithOptions:usingBlock:")]
    public void EnumerateRangesWithOptionsUsingBlock(NSEnumerationOptions opts, NSIndexSetEnumerateRangesWithOptionsUsingBlockBlock block);
    [Selector("enumerateRangesInRange:options:usingBlock:")]
    public void EnumerateRangesInRangeOptionsUsingBlock(NSRange range, NSEnumerationOptions opts, NSIndexSetEnumerateRangesInRangeOptionsUsingBlockBlock block);
}

public extern objc class NSMutableIndexSet : NSIndexSet
{
    [Selector("addIndexes:")]
    public void AddIndexes(NSIndexSet indexSet);
    [Selector("removeIndexes:")]
    public void RemoveIndexes(NSIndexSet indexSet);
    [Selector("removeAllIndexes")]
    public void RemoveAllIndexes();
    [Selector("addIndex:")]
    public void AddIndex(NSUInteger value);
    [Selector("removeIndex:")]
    public void RemoveIndex(NSUInteger value);
    [Selector("addIndexesInRange:")]
    public void AddIndexesInRange(NSRange range);
    [Selector("removeIndexesInRange:")]
    public void RemoveIndexesInRange(NSRange range);
    [Selector("shiftIndexesStartingAtIndex:by:")]
    public void ShiftIndexesStartingAtIndexBy(NSUInteger index, NSInteger delta);
}

#endif
