// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Foundation.framework (NSJSONSerialization.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Foundation;

import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Foundation")

[Flags]
public enum NSJSONReadingOptions : ulong
{
    MutableContainers = 1,
    MutableLeaves = 2,
    FragmentsAllowed = 4,
    JSON5Allowed = 8,
    TopLevelDictionaryAssumed = 16,
    AllowFragments = 4,
}

[Flags]
public enum NSJSONWritingOptions : ulong
{
    PrettyPrinted = 1,
    SortedKeys = 2,
    FragmentsAllowed = 4,
    WithoutEscapingSlashes = 8,
}

public extern objc class NSJSONSerialization : NSObject
{
    [Selector("isValidJSONObject:")] public static bool IsValidJSONObject(AnyObject obj);
    [Selector("dataWithJSONObject:options:error:")] public static NSData? DataWithJSONObjectOptionsError(AnyObject obj, NSJSONWritingOptions opt, out NSError? error);
    [Selector("JSONObjectWithData:options:error:")] public static AnyObject? JSONObjectWithDataOptionsError(NSData data, NSJSONReadingOptions opt, out NSError? error);
    [Selector("writeJSONObject:toStream:options:error:")] public static NSInteger WriteJSONObjectToStreamOptionsError(AnyObject obj, NSOutputStream stream, NSJSONWritingOptions opt, out NSError? error);
    [Selector("JSONObjectWithStream:options:error:")] public static AnyObject? JSONObjectWithStreamOptionsError(NSInputStream stream, NSJSONReadingOptions opt, out NSError? error);
}

#endif
