// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AVFoundation.framework (AVMediaSelectionGroup.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AVFoundation;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "AVFoundation")

public extern objc class AVMediaSelectionGroup : NSObject, NSCopying
{
    [Selector("options")] public NSArray Options { get; }
    [Selector("defaultOption")] public AVMediaSelectionOption? DefaultOption { get; }
    [Selector("allowsEmptySelection")] public bool AllowsEmptySelection { get; }
    [Selector("mediaSelectionOptionWithPropertyList:")] public AVMediaSelectionOption? MediaSelectionOptionWithPropertyList(AnyObject plist);
}

/// AVMediaSelectionOptionFiltering, a category of AVMediaSelectionGroup.
public extern objc class AVMediaSelectionGroup
{
    [Selector("playableMediaSelectionOptionsFromArray:")] public static NSArray PlayableMediaSelectionOptionsFromArray(NSArray mediaSelectionOptions);
    [Selector("mediaSelectionOptionsFromArray:filteredAndSortedAccordingToPreferredLanguages:")] public static NSArray MediaSelectionOptionsFromArrayFilteredAndSortedAccordingToPreferredLanguages(NSArray mediaSelectionOptions, NSArray preferredLanguages);
    [Selector("mediaSelectionOptionsFromArray:withLocale:")] public static NSArray MediaSelectionOptionsFromArrayWithLocale(NSArray mediaSelectionOptions, NSLocale locale);
    [Selector("mediaSelectionOptionsFromArray:withMediaCharacteristics:")] public static NSArray MediaSelectionOptionsFromArrayWithMediaCharacteristics(NSArray mediaSelectionOptions, NSArray mediaCharacteristics);
    [Selector("mediaSelectionOptionsFromArray:withoutMediaCharacteristics:")] public static NSArray MediaSelectionOptionsFromArrayWithoutMediaCharacteristics(NSArray mediaSelectionOptions, NSArray mediaCharacteristics);
}

public extern objc class AVMediaSelectionOption : NSObject, NSCopying
{
    [Selector("mediaType")] public AVMediaType MediaType { get; }
    [Selector("mediaSubTypes")] public NSArray MediaSubTypes { get; }
    [Selector("isPlayable")] public bool Playable { get; }
    [Selector("extendedLanguageTag")] public NSString? ExtendedLanguageTag { get; }
    [Selector("locale")] public NSLocale? Locale { get; }
    [Selector("commonMetadata")] public NSArray CommonMetadata { get; }
    [Selector("availableMetadataFormats")] public NSArray AvailableMetadataFormats { get; }
    [Selector("displayName")] public NSString DisplayName { get; }
    [Selector("hasMediaCharacteristic:")] public bool HasMediaCharacteristic(AVMediaCharacteristic mediaCharacteristic);
    [Selector("metadataForFormat:")] public NSArray MetadataForFormat(NSString format);
    [Selector("associatedMediaSelectionOptionInMediaSelectionGroup:")] public AVMediaSelectionOption? AssociatedMediaSelectionOptionInMediaSelectionGroup(AVMediaSelectionGroup mediaSelectionGroup);
    [Selector("propertyList")] public AnyObject PropertyList();
    [Selector("displayNameWithLocale:")] public NSString DisplayNameWithLocale(NSLocale locale);
}

/// AVMediaSelectionGroupCustomMediaSelectionScheme, a category of AVMediaSelectionGroup.
public extern objc class AVMediaSelectionGroup
{
    /// macOS 26.0 and later.
    [Selector("customMediaSelectionScheme")] public AVCustomMediaSelectionScheme? CustomMediaSelectionScheme { get; }
}

/// macOS 26.0 and later.
public extern objc class AVCustomMediaSelectionScheme : NSObject, NSCopying
{
    [Selector("shouldOfferLanguageSelection")] public bool ShouldOfferLanguageSelection { get; }
    [Selector("availableLanguages")] public NSArray AvailableLanguages { get; }
    [Selector("selectors")] public NSArray Selectors { get; }
    [Selector("mediaPresentationSettingsForSelector:complementaryToLanguage:settings:")] public NSArray MediaPresentationSettingsForSelectorComplementaryToLanguageSettings(AVMediaPresentationSelector selector, NSString? language, NSArray settings);
}

/// macOS 26.0 and later.
public extern objc class AVMediaPresentationSelector : NSObject, NSCopying
{
    [Selector("identifier")] public NSString Identifier { get; }
    [Selector("settings")] public NSArray Settings { get; }
    [Selector("displayNameForLocaleIdentifier:")] public NSString DisplayNameForLocaleIdentifier(NSString localeIdentifier);
}

/// macOS 26.0 and later.
public extern objc class AVMediaPresentationSetting : NSObject, NSCopying
{
    [Selector("mediaCharacteristic")] public AVMediaCharacteristic MediaCharacteristic { get; }
    [Selector("displayNameForLocaleIdentifier:")] public NSString DisplayNameForLocaleIdentifier(NSString localeIdentifier);
}

#endif
