// Generated by tools/Stainless.Bindgen: what clang says each declaration OSLog's
// headers bound is. Do not edit; regenerate with tools/bindgen.sh.

#import <OSLog/OSLog.h>
#import <OSLog/Entry.h>
#import <OSLog/EntryActivity.h>
#import <OSLog/EntryBoundary.h>
#import <OSLog/EntryLog.h>
#import <OSLog/EntrySignpost.h>
#import <OSLog/Enumerator.h>
#import <OSLog/MessageComponent.h>
#import <OSLog/OSLog.h>
#import <OSLog/Position.h>
#import <OSLog/Store.h>

const long long sl_layout_132[] = {
    (long long)(OSLogEntryStoreCategoryUndefined),
    (long long)(OSLogEntryStoreCategoryMetadata),
    (long long)(OSLogEntryStoreCategoryShortTerm),
    (long long)(OSLogEntryStoreCategoryLongTermAuto),
    (long long)(OSLogEntryStoreCategoryLongTerm1),
    (long long)(OSLogEntryStoreCategoryLongTerm3),
    (long long)(OSLogEntryStoreCategoryLongTerm7),
    (long long)(OSLogEntryStoreCategoryLongTerm14),
    (long long)(OSLogEntryStoreCategoryLongTerm30),
    (long long)(OSLogEntryLogLevelUndefined),
    (long long)(OSLogEntryLogLevelDebug),
    (long long)(OSLogEntryLogLevelInfo),
    (long long)(OSLogEntryLogLevelNotice),
    (long long)(OSLogEntryLogLevelError),
    (long long)(OSLogEntryLogLevelFault),
    (long long)(OSLogEntrySignpostTypeUndefined),
    (long long)(OSLogEntrySignpostTypeIntervalBegin),
    (long long)(OSLogEntrySignpostTypeIntervalEnd),
    (long long)(OSLogEntrySignpostTypeEvent),
    (long long)(OSLogEnumeratorReverse),
    (long long)(OSLogMessageComponentArgumentCategoryUndefined),
    (long long)(OSLogMessageComponentArgumentCategoryData),
    (long long)(OSLogMessageComponentArgumentCategoryDouble),
    (long long)(OSLogMessageComponentArgumentCategoryInt64),
    (long long)(OSLogMessageComponentArgumentCategoryString),
    (long long)(OSLogMessageComponentArgumentCategoryUInt64),
    (long long)(OSLogStoreSystem),
    (long long)(OSLogStoreCurrentProcessIdentifier),
};
