// Generated by tools/Stainless.Bindgen: what clang says each declaration InputMethodKit's
// headers bound is. Do not edit; regenerate with tools/bindgen.sh.

#import <InputMethodKit/InputMethodKit.h>
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Headers/IMKCandidates.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Headers/IMKInputController.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Headers/IMKServer.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/InputMethodKit.framework/Headers/InputMethodKit.h"

const long long sl_layout_104[] = {
    (long long)(kIMKSingleColumnScrollingCandidatePanel),
    (long long)(kIMKScrollingGridCandidatePanel),
    (long long)(kIMKSingleRowSteppingCandidatePanel),
    (long long)(kIMKMain),
    (long long)(kIMKAnnotation),
    (long long)(kIMKSubList),
    (long long)(kIMKLocateCandidatesAboveHint),
    (long long)(kIMKLocateCandidatesBelowHint),
    (long long)(kIMKLocateCandidatesLeftHint),
    (long long)(kIMKLocateCandidatesRightHint),
};
