// Generated by tools/Stainless.Bindgen: what clang says each declaration IntentsUI's
// headers bound is. Do not edit; regenerate with tools/bindgen.sh.

#import <IntentsUI/IntentsUI.h>
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IntentsUI.framework/Headers/INImage+IntentsUI.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IntentsUI.framework/Headers/INUIAddVoiceShortcutButton.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IntentsUI.framework/Headers/INUIAddVoiceShortcutViewController.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IntentsUI.framework/Headers/INUIEditVoiceShortcutViewController.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IntentsUI.framework/Headers/IntentsUI.h"

const long long sl_layout_108[] = {
    (long long)(INUIAddVoiceShortcutButtonStyleWhite),
    (long long)(INUIAddVoiceShortcutButtonStyleWhiteOutline),
    (long long)(INUIAddVoiceShortcutButtonStyleBlack),
    (long long)(INUIAddVoiceShortcutButtonStyleBlackOutline),
    (long long)(INUIAddVoiceShortcutButtonStyleAutomatic),
    (long long)(INUIAddVoiceShortcutButtonStyleAutomaticOutline),
};
