// Generated by tools/Stainless.Bindgen: what clang says each declaration JavaScriptCore's
// headers bound is. Do not edit; regenerate with tools/bindgen.sh.

#import <JavaScriptCore/JavaScriptCore.h>
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSBase.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSContext.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSContextRef.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSExport.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSManagedValue.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSObjectRef.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSStringRef.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSStringRefCF.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSTypedArray.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSValue.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSValueRef.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JSVirtualMachine.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JavaScript.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/JavaScriptCore.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/JavaScriptCore.framework/Headers/WebKitAvailability.h"

const long long sl_layout_110[] = {
    (long long)(kJSTypeUndefined),
    (long long)(kJSTypeNull),
    (long long)(kJSTypeBoolean),
    (long long)(kJSTypeNumber),
    (long long)(kJSTypeString),
    (long long)(kJSTypeObject),
    (long long)(kJSTypeSymbol),
    (long long)(kJSTypeBigInt),
    (long long)(kJSTypedArrayTypeInt8Array),
    (long long)(kJSTypedArrayTypeInt16Array),
    (long long)(kJSTypedArrayTypeInt32Array),
    (long long)(kJSTypedArrayTypeUint8Array),
    (long long)(kJSTypedArrayTypeUint8ClampedArray),
    (long long)(kJSTypedArrayTypeUint16Array),
    (long long)(kJSTypedArrayTypeUint32Array),
    (long long)(kJSTypedArrayTypeFloat32Array),
    (long long)(kJSTypedArrayTypeFloat64Array),
    (long long)(kJSTypedArrayTypeArrayBuffer),
    (long long)(kJSTypedArrayTypeNone),
    (long long)(kJSTypedArrayTypeBigInt64Array),
    (long long)(kJSTypedArrayTypeBigUint64Array),
    (long long)(kJSRelationConditionUndefined),
    (long long)(kJSRelationConditionEqual),
    (long long)(kJSRelationConditionGreaterThan),
    (long long)(kJSRelationConditionLessThan),
    (long long)(kJSPropertyAttributeNone),
    (long long)(kJSPropertyAttributeReadOnly),
    (long long)(kJSPropertyAttributeDontEnum),
    (long long)(kJSPropertyAttributeDontDelete),
    (long long)(kJSClassAttributeNone),
    (long long)(kJSClassAttributeNoAutomaticPrototype),
    (long long)(sizeof(JSStaticValue)),
    (long long)(_Alignof(JSStaticValue)),
    (long long)(__builtin_offsetof(JSStaticValue, name)),
    (long long)(__builtin_offsetof(JSStaticValue, getProperty)),
    (long long)(__builtin_offsetof(JSStaticValue, setProperty)),
    (long long)(__builtin_offsetof(JSStaticValue, attributes)),
    (long long)(sizeof(JSStaticFunction)),
    (long long)(_Alignof(JSStaticFunction)),
    (long long)(__builtin_offsetof(JSStaticFunction, name)),
    (long long)(__builtin_offsetof(JSStaticFunction, callAsFunction)),
    (long long)(__builtin_offsetof(JSStaticFunction, attributes)),
    (long long)(sizeof(JSClassDefinition)),
    (long long)(_Alignof(JSClassDefinition)),
    (long long)(__builtin_offsetof(JSClassDefinition, version)),
    (long long)(__builtin_offsetof(JSClassDefinition, attributes)),
    (long long)(__builtin_offsetof(JSClassDefinition, className)),
    (long long)(__builtin_offsetof(JSClassDefinition, parentClass)),
    (long long)(__builtin_offsetof(JSClassDefinition, staticValues)),
    (long long)(__builtin_offsetof(JSClassDefinition, staticFunctions)),
    (long long)(__builtin_offsetof(JSClassDefinition, initialize)),
    (long long)(__builtin_offsetof(JSClassDefinition, finalize)),
    (long long)(__builtin_offsetof(JSClassDefinition, hasProperty)),
    (long long)(__builtin_offsetof(JSClassDefinition, getProperty)),
    (long long)(__builtin_offsetof(JSClassDefinition, setProperty)),
    (long long)(__builtin_offsetof(JSClassDefinition, deleteProperty)),
    (long long)(__builtin_offsetof(JSClassDefinition, getPropertyNames)),
    (long long)(__builtin_offsetof(JSClassDefinition, callAsFunction)),
    (long long)(__builtin_offsetof(JSClassDefinition, callAsConstructor)),
    (long long)(__builtin_offsetof(JSClassDefinition, hasInstance)),
    (long long)(__builtin_offsetof(JSClassDefinition, convertToType)),
    (long long)((JSC_OBJC_API_ENABLED)),
};
