// Generated by tools/Stainless.Bindgen: what clang says each declaration QuickLookThumbnailing's
// headers bound is. Do not edit; regenerate with tools/bindgen.sh.

#import <QuickLookThumbnailing/QuickLookThumbnailing.h>
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QLThumbnailErrors.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QLThumbnailGenerationRequest.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QLThumbnailGenerator.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QLThumbnailProvider.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QLThumbnailReply.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QLThumbnailRepresentation.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QLThumbnailRequest.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QLThumbnailingBase.h"
#import "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/QuickLookThumbnailing.framework/Headers/QuickLookThumbnailing.h"

const long long sl_layout_144[] = {
    (long long)(QLThumbnailRepresentationTypeIcon),
    (long long)(QLThumbnailRepresentationTypeLowQualityThumbnail),
    (long long)(QLThumbnailRepresentationTypeThumbnail),
    (long long)(QLThumbnailGenerationRequestRepresentationTypeIcon),
    (long long)(QLThumbnailGenerationRequestRepresentationTypeLowQualityThumbnail),
    (long long)(QLThumbnailGenerationRequestRepresentationTypeThumbnail),
    (long long)(QLThumbnailGenerationRequestRepresentationTypeAll),
    (long long)(QLThumbnailErrorGenerationFailed),
    (long long)(QLThumbnailErrorSavingToURLFailed),
    (long long)(QLThumbnailErrorNoCachedThumbnail),
    (long long)(QLThumbnailErrorNoCloudThumbnail),
    (long long)(QLThumbnailErrorRequestInvalid),
    (long long)(QLThumbnailErrorRequestCancelled),
};
