// Generated by tools/Stainless.Bindgen: what clang says each declaration AudioUnit's
// headers bound is. Do not edit; regenerate with tools/bindgen.sh.

#import <AudioUnit/AudioUnit.h>
#import <AudioUnit/AUAudioUnit.h>
#import <AudioUnit/AUAudioUnitImplementation.h>
#import <AudioUnit/AUCocoaUIView.h>
#import <AudioUnit/AUComponent.h>
#import <AudioUnit/AUParameters.h>
#import <AudioUnit/AudioCodec.h>
#import <AudioUnit/AudioComponent.h>
#import <AudioUnit/AudioOutputUnit.h>
#import <AudioUnit/AudioUnit.h>
#import <AudioUnit/AudioUnitCarbonView.h>
#import <AudioUnit/AudioUnitParameters.h>
#import <AudioUnit/AudioUnitProperties.h>
#import <AudioUnit/MusicDevice.h>

const long long sl_layout_20[] = {
    (long long)((AUDIO_UNIT_VERSION)),
};
