// Generated by tools/Stainless.Bindgen: what clang says each declaration ServiceManagement's
// headers bound is. Do not edit; regenerate with tools/bindgen.sh.

#import <ServiceManagement/ServiceManagement.h>
#import <ServiceManagement/SMAppService.h>
#import <ServiceManagement/SMErrors.h>
#import <ServiceManagement/SMLoginItem.h>
#import <ServiceManagement/ServiceManagement.h>

const long long sl_layout_153[] = {
    (long long)(kSMErrorInternalFailure),
    (long long)(kSMErrorInvalidSignature),
    (long long)(kSMErrorAuthorizationFailure),
    (long long)(kSMErrorToolNotValid),
    (long long)(kSMErrorJobNotFound),
    (long long)(kSMErrorServiceUnavailable),
    (long long)(kSMErrorJobPlistNotFound),
    (long long)(kSMErrorJobMustBeEnabled),
    (long long)(kSMErrorInvalidPlist),
    (long long)(kSMErrorLaunchDeniedByUser),
    (long long)(kSMErrorAlreadyRegistered),
    (long long)(SMAppServiceStatusNotRegistered),
    (long long)(SMAppServiceStatusEnabled),
    (long long)(SMAppServiceStatusRequiresApproval),
    (long long)(SMAppServiceStatusNotFound),
};
