// Generated by tools/Stainless.Bindgen: what clang says each declaration NearbyInteraction's
// headers bound is. Do not edit; regenerate with tools/bindgen.sh.

#import <NearbyInteraction/NearbyInteraction.h>
#import <NearbyInteraction/NIAlgorithmConvergenceStatusReason.h>
#import <NearbyInteraction/NIConfiguration.h>
#import <NearbyInteraction/NIDLTDOAMeasurement.h>
#import <NearbyInteraction/NIDeviceCapability.h>
#import <NearbyInteraction/NIError.h>
#import <NearbyInteraction/NIExport.h>
#import <NearbyInteraction/NINearbyObject.h>
#import <NearbyInteraction/NISession.h>
#import <NearbyInteraction/NearbyInteraction.h>

const long long sl_layout_127[] = {
    (long long)(NIErrorCodeUnsupportedPlatform),
    (long long)(NIErrorCodeInvalidConfiguration),
    (long long)(NIErrorCodeSessionFailed),
    (long long)(NIErrorCodeResourceUsageTimeout),
    (long long)(NIErrorCodeActiveSessionsLimitExceeded),
    (long long)(NIErrorCodeUserDidNotAllow),
    (long long)(NIErrorCodeIncompatiblePeerDevice),
    (long long)(NIErrorCodeActiveExtendedDistanceSessionsLimitExceeded),
    (long long)(NINearbyObjectVerticalDirectionEstimateUnknown),
    (long long)(NINearbyObjectVerticalDirectionEstimateSame),
    (long long)(NINearbyObjectVerticalDirectionEstimateAbove),
    (long long)(NINearbyObjectVerticalDirectionEstimateBelow),
    (long long)(NINearbyObjectVerticalDirectionEstimateAboveOrBelow),
    (long long)(NIDLTDOACoordinatesTypeGeodetic),
    (long long)(NIDLTDOACoordinatesTypeRelative),
    (long long)(NIDLTDOAMeasurementTypePoll),
    (long long)(NIDLTDOAMeasurementTypeResponse),
    (long long)(NIDLTDOAMeasurementTypeFinal),
    (long long)(NINearbyObjectRemovalReasonTimeout),
    (long long)(NINearbyObjectRemovalReasonPeerEnded),
    (long long)(NIAlgorithmConvergenceStatusUnknown),
    (long long)(NIAlgorithmConvergenceStatusNotConverged),
    (long long)(NIAlgorithmConvergenceStatusConverged),
};
