// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Security.framework (CipherSuite.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Security;

#if MACOS

#pragma comment(framework, "Security")

#if ARM64
public using SSLCipherSuite = ushort;
#else
public using SSLCipherSuite = uint;
#endif

#if ARM64
public const ushort SSL_NULL_WITH_NULL_NULL = 0;
public const ushort SSL_RSA_WITH_NULL_MD5 = 1;
public const ushort SSL_RSA_WITH_NULL_SHA = 2;
public const ushort SSL_RSA_EXPORT_WITH_RC4_40_MD5 = 3;
public const ushort SSL_RSA_WITH_RC4_128_MD5 = 4;
public const ushort SSL_RSA_WITH_RC4_128_SHA = 5;
public const ushort SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5 = 6;
public const ushort SSL_RSA_WITH_IDEA_CBC_SHA = 7;
public const ushort SSL_RSA_EXPORT_WITH_DES40_CBC_SHA = 8;
public const ushort SSL_RSA_WITH_DES_CBC_SHA = 9;
public const ushort SSL_RSA_WITH_3DES_EDE_CBC_SHA = 10;
public const ushort SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA = 11;
public const ushort SSL_DH_DSS_WITH_DES_CBC_SHA = 12;
public const ushort SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA = 13;
public const ushort SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA = 14;
public const ushort SSL_DH_RSA_WITH_DES_CBC_SHA = 15;
public const ushort SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA = 16;
public const ushort SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = 17;
public const ushort SSL_DHE_DSS_WITH_DES_CBC_SHA = 18;
public const ushort SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 19;
public const ushort SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = 20;
public const ushort SSL_DHE_RSA_WITH_DES_CBC_SHA = 21;
public const ushort SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 22;
public const ushort SSL_DH_anon_EXPORT_WITH_RC4_40_MD5 = 23;
public const ushort SSL_DH_anon_WITH_RC4_128_MD5 = 24;
public const ushort SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA = 25;
public const ushort SSL_DH_anon_WITH_DES_CBC_SHA = 26;
public const ushort SSL_DH_anon_WITH_3DES_EDE_CBC_SHA = 27;
public const ushort SSL_FORTEZZA_DMS_WITH_NULL_SHA = 28;
public const ushort SSL_FORTEZZA_DMS_WITH_FORTEZZA_CBC_SHA = 29;
public const ushort TLS_RSA_WITH_AES_128_CBC_SHA = 47;
public const ushort TLS_DH_DSS_WITH_AES_128_CBC_SHA = 48;
public const ushort TLS_DH_RSA_WITH_AES_128_CBC_SHA = 49;
public const ushort TLS_DHE_DSS_WITH_AES_128_CBC_SHA = 50;
public const ushort TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 51;
public const ushort TLS_DH_anon_WITH_AES_128_CBC_SHA = 52;
public const ushort TLS_RSA_WITH_AES_256_CBC_SHA = 53;
public const ushort TLS_DH_DSS_WITH_AES_256_CBC_SHA = 54;
public const ushort TLS_DH_RSA_WITH_AES_256_CBC_SHA = 55;
public const ushort TLS_DHE_DSS_WITH_AES_256_CBC_SHA = 56;
public const ushort TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 57;
public const ushort TLS_DH_anon_WITH_AES_256_CBC_SHA = 58;
public const ushort TLS_ECDH_ECDSA_WITH_NULL_SHA = 49153;
public const ushort TLS_ECDH_ECDSA_WITH_RC4_128_SHA = 49154;
public const ushort TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = 49155;
public const ushort TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = 49156;
public const ushort TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = 49157;
public const ushort TLS_ECDHE_ECDSA_WITH_NULL_SHA = 49158;
public const ushort TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = 49159;
public const ushort TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = 49160;
public const ushort TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 49161;
public const ushort TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 49162;
public const ushort TLS_ECDH_RSA_WITH_NULL_SHA = 49163;
public const ushort TLS_ECDH_RSA_WITH_RC4_128_SHA = 49164;
public const ushort TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = 49165;
public const ushort TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = 49166;
public const ushort TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = 49167;
public const ushort TLS_ECDHE_RSA_WITH_NULL_SHA = 49168;
public const ushort TLS_ECDHE_RSA_WITH_RC4_128_SHA = 49169;
public const ushort TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = 49170;
public const ushort TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 49171;
public const ushort TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 49172;
public const ushort TLS_ECDH_anon_WITH_NULL_SHA = 49173;
public const ushort TLS_ECDH_anon_WITH_RC4_128_SHA = 49174;
public const ushort TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA = 49175;
public const ushort TLS_ECDH_anon_WITH_AES_128_CBC_SHA = 49176;
public const ushort TLS_ECDH_anon_WITH_AES_256_CBC_SHA = 49177;
public const ushort TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA = 49205;
public const ushort TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA = 49206;
public const ushort TLS_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52395;
public const ushort TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52396;
public const ushort TLS_NULL_WITH_NULL_NULL = 0;
public const ushort TLS_RSA_WITH_NULL_MD5 = 1;
public const ushort TLS_RSA_WITH_NULL_SHA = 2;
public const ushort TLS_RSA_WITH_RC4_128_MD5 = 4;
public const ushort TLS_RSA_WITH_RC4_128_SHA = 5;
public const ushort TLS_RSA_WITH_3DES_EDE_CBC_SHA = 10;
public const ushort TLS_RSA_WITH_NULL_SHA256 = 59;
public const ushort TLS_RSA_WITH_AES_128_CBC_SHA256 = 60;
public const ushort TLS_RSA_WITH_AES_256_CBC_SHA256 = 61;
public const ushort TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA = 13;
public const ushort TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA = 16;
public const ushort TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 19;
public const ushort TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 22;
public const ushort TLS_DH_DSS_WITH_AES_128_CBC_SHA256 = 62;
public const ushort TLS_DH_RSA_WITH_AES_128_CBC_SHA256 = 63;
public const ushort TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = 64;
public const ushort TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 103;
public const ushort TLS_DH_DSS_WITH_AES_256_CBC_SHA256 = 104;
public const ushort TLS_DH_RSA_WITH_AES_256_CBC_SHA256 = 105;
public const ushort TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = 106;
public const ushort TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 107;
public const ushort TLS_DH_anon_WITH_RC4_128_MD5 = 24;
public const ushort TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = 27;
public const ushort TLS_DH_anon_WITH_AES_128_CBC_SHA256 = 108;
public const ushort TLS_DH_anon_WITH_AES_256_CBC_SHA256 = 109;
public const ushort TLS_PSK_WITH_RC4_128_SHA = 138;
public const ushort TLS_PSK_WITH_3DES_EDE_CBC_SHA = 139;
public const ushort TLS_PSK_WITH_AES_128_CBC_SHA = 140;
public const ushort TLS_PSK_WITH_AES_256_CBC_SHA = 141;
public const ushort TLS_DHE_PSK_WITH_RC4_128_SHA = 142;
public const ushort TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA = 143;
public const ushort TLS_DHE_PSK_WITH_AES_128_CBC_SHA = 144;
public const ushort TLS_DHE_PSK_WITH_AES_256_CBC_SHA = 145;
public const ushort TLS_RSA_PSK_WITH_RC4_128_SHA = 146;
public const ushort TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA = 147;
public const ushort TLS_RSA_PSK_WITH_AES_128_CBC_SHA = 148;
public const ushort TLS_RSA_PSK_WITH_AES_256_CBC_SHA = 149;
public const ushort TLS_PSK_WITH_NULL_SHA = 44;
public const ushort TLS_DHE_PSK_WITH_NULL_SHA = 45;
public const ushort TLS_RSA_PSK_WITH_NULL_SHA = 46;
public const ushort TLS_RSA_WITH_AES_128_GCM_SHA256 = 156;
public const ushort TLS_RSA_WITH_AES_256_GCM_SHA384 = 157;
public const ushort TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = 158;
public const ushort TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 159;
public const ushort TLS_DH_RSA_WITH_AES_128_GCM_SHA256 = 160;
public const ushort TLS_DH_RSA_WITH_AES_256_GCM_SHA384 = 161;
public const ushort TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = 162;
public const ushort TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = 163;
public const ushort TLS_DH_DSS_WITH_AES_128_GCM_SHA256 = 164;
public const ushort TLS_DH_DSS_WITH_AES_256_GCM_SHA384 = 165;
public const ushort TLS_DH_anon_WITH_AES_128_GCM_SHA256 = 166;
public const ushort TLS_DH_anon_WITH_AES_256_GCM_SHA384 = 167;
public const ushort TLS_PSK_WITH_AES_128_GCM_SHA256 = 168;
public const ushort TLS_PSK_WITH_AES_256_GCM_SHA384 = 169;
public const ushort TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 = 170;
public const ushort TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 = 171;
public const ushort TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 = 172;
public const ushort TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 = 173;
public const ushort TLS_PSK_WITH_AES_128_CBC_SHA256 = 174;
public const ushort TLS_PSK_WITH_AES_256_CBC_SHA384 = 175;
public const ushort TLS_PSK_WITH_NULL_SHA256 = 176;
public const ushort TLS_PSK_WITH_NULL_SHA384 = 177;
public const ushort TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 = 178;
public const ushort TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 = 179;
public const ushort TLS_DHE_PSK_WITH_NULL_SHA256 = 180;
public const ushort TLS_DHE_PSK_WITH_NULL_SHA384 = 181;
public const ushort TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 = 182;
public const ushort TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 = 183;
public const ushort TLS_RSA_PSK_WITH_NULL_SHA256 = 184;
public const ushort TLS_RSA_PSK_WITH_NULL_SHA384 = 185;
public const ushort TLS_AES_128_GCM_SHA256 = 4865;
public const ushort TLS_AES_256_GCM_SHA384 = 4866;
public const ushort TLS_CHACHA20_POLY1305_SHA256 = 4867;
public const ushort TLS_AES_128_CCM_SHA256 = 4868;
public const ushort TLS_AES_128_CCM_8_SHA256 = 4869;
public const ushort TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = 49187;
public const ushort TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = 49188;
public const ushort TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = 49189;
public const ushort TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = 49190;
public const ushort TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = 49191;
public const ushort TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = 49192;
public const ushort TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = 49193;
public const ushort TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = 49194;
public const ushort TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 49195;
public const ushort TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 49196;
public const ushort TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = 49197;
public const ushort TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = 49198;
public const ushort TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 49199;
public const ushort TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 49200;
public const ushort TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = 49201;
public const ushort TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = 49202;
public const ushort TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52392;
public const ushort TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = 52393;
public const ushort TLS_EMPTY_RENEGOTIATION_INFO_SCSV = 255;
public const ushort SSL_RSA_WITH_RC2_CBC_MD5 = 65408;
public const ushort SSL_RSA_WITH_IDEA_CBC_MD5 = 65409;
public const ushort SSL_RSA_WITH_DES_CBC_MD5 = 65410;
public const ushort SSL_RSA_WITH_3DES_EDE_CBC_MD5 = 65411;
public const ushort SSL_NO_SUCH_CIPHERSUITE = 65535;
#else
public const uint SSL_NULL_WITH_NULL_NULL = 0;
public const uint SSL_RSA_WITH_NULL_MD5 = 1;
public const uint SSL_RSA_WITH_NULL_SHA = 2;
public const uint SSL_RSA_EXPORT_WITH_RC4_40_MD5 = 3;
public const uint SSL_RSA_WITH_RC4_128_MD5 = 4;
public const uint SSL_RSA_WITH_RC4_128_SHA = 5;
public const uint SSL_RSA_EXPORT_WITH_RC2_CBC_40_MD5 = 6;
public const uint SSL_RSA_WITH_IDEA_CBC_SHA = 7;
public const uint SSL_RSA_EXPORT_WITH_DES40_CBC_SHA = 8;
public const uint SSL_RSA_WITH_DES_CBC_SHA = 9;
public const uint SSL_RSA_WITH_3DES_EDE_CBC_SHA = 10;
public const uint SSL_DH_DSS_EXPORT_WITH_DES40_CBC_SHA = 11;
public const uint SSL_DH_DSS_WITH_DES_CBC_SHA = 12;
public const uint SSL_DH_DSS_WITH_3DES_EDE_CBC_SHA = 13;
public const uint SSL_DH_RSA_EXPORT_WITH_DES40_CBC_SHA = 14;
public const uint SSL_DH_RSA_WITH_DES_CBC_SHA = 15;
public const uint SSL_DH_RSA_WITH_3DES_EDE_CBC_SHA = 16;
public const uint SSL_DHE_DSS_EXPORT_WITH_DES40_CBC_SHA = 17;
public const uint SSL_DHE_DSS_WITH_DES_CBC_SHA = 18;
public const uint SSL_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 19;
public const uint SSL_DHE_RSA_EXPORT_WITH_DES40_CBC_SHA = 20;
public const uint SSL_DHE_RSA_WITH_DES_CBC_SHA = 21;
public const uint SSL_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 22;
public const uint SSL_DH_anon_EXPORT_WITH_RC4_40_MD5 = 23;
public const uint SSL_DH_anon_WITH_RC4_128_MD5 = 24;
public const uint SSL_DH_anon_EXPORT_WITH_DES40_CBC_SHA = 25;
public const uint SSL_DH_anon_WITH_DES_CBC_SHA = 26;
public const uint SSL_DH_anon_WITH_3DES_EDE_CBC_SHA = 27;
public const uint SSL_FORTEZZA_DMS_WITH_NULL_SHA = 28;
public const uint SSL_FORTEZZA_DMS_WITH_FORTEZZA_CBC_SHA = 29;
public const uint TLS_RSA_WITH_AES_128_CBC_SHA = 47;
public const uint TLS_DH_DSS_WITH_AES_128_CBC_SHA = 48;
public const uint TLS_DH_RSA_WITH_AES_128_CBC_SHA = 49;
public const uint TLS_DHE_DSS_WITH_AES_128_CBC_SHA = 50;
public const uint TLS_DHE_RSA_WITH_AES_128_CBC_SHA = 51;
public const uint TLS_DH_anon_WITH_AES_128_CBC_SHA = 52;
public const uint TLS_RSA_WITH_AES_256_CBC_SHA = 53;
public const uint TLS_DH_DSS_WITH_AES_256_CBC_SHA = 54;
public const uint TLS_DH_RSA_WITH_AES_256_CBC_SHA = 55;
public const uint TLS_DHE_DSS_WITH_AES_256_CBC_SHA = 56;
public const uint TLS_DHE_RSA_WITH_AES_256_CBC_SHA = 57;
public const uint TLS_DH_anon_WITH_AES_256_CBC_SHA = 58;
public const uint TLS_ECDH_ECDSA_WITH_NULL_SHA = 49153;
public const uint TLS_ECDH_ECDSA_WITH_RC4_128_SHA = 49154;
public const uint TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA = 49155;
public const uint TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA = 49156;
public const uint TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA = 49157;
public const uint TLS_ECDHE_ECDSA_WITH_NULL_SHA = 49158;
public const uint TLS_ECDHE_ECDSA_WITH_RC4_128_SHA = 49159;
public const uint TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA = 49160;
public const uint TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA = 49161;
public const uint TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA = 49162;
public const uint TLS_ECDH_RSA_WITH_NULL_SHA = 49163;
public const uint TLS_ECDH_RSA_WITH_RC4_128_SHA = 49164;
public const uint TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA = 49165;
public const uint TLS_ECDH_RSA_WITH_AES_128_CBC_SHA = 49166;
public const uint TLS_ECDH_RSA_WITH_AES_256_CBC_SHA = 49167;
public const uint TLS_ECDHE_RSA_WITH_NULL_SHA = 49168;
public const uint TLS_ECDHE_RSA_WITH_RC4_128_SHA = 49169;
public const uint TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA = 49170;
public const uint TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA = 49171;
public const uint TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA = 49172;
public const uint TLS_ECDH_anon_WITH_NULL_SHA = 49173;
public const uint TLS_ECDH_anon_WITH_RC4_128_SHA = 49174;
public const uint TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA = 49175;
public const uint TLS_ECDH_anon_WITH_AES_128_CBC_SHA = 49176;
public const uint TLS_ECDH_anon_WITH_AES_256_CBC_SHA = 49177;
public const uint TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA = 49205;
public const uint TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA = 49206;
public const uint TLS_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52395;
public const uint TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 = 52396;
public const uint TLS_NULL_WITH_NULL_NULL = 0;
public const uint TLS_RSA_WITH_NULL_MD5 = 1;
public const uint TLS_RSA_WITH_NULL_SHA = 2;
public const uint TLS_RSA_WITH_RC4_128_MD5 = 4;
public const uint TLS_RSA_WITH_RC4_128_SHA = 5;
public const uint TLS_RSA_WITH_3DES_EDE_CBC_SHA = 10;
public const uint TLS_RSA_WITH_NULL_SHA256 = 59;
public const uint TLS_RSA_WITH_AES_128_CBC_SHA256 = 60;
public const uint TLS_RSA_WITH_AES_256_CBC_SHA256 = 61;
public const uint TLS_DH_DSS_WITH_3DES_EDE_CBC_SHA = 13;
public const uint TLS_DH_RSA_WITH_3DES_EDE_CBC_SHA = 16;
public const uint TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA = 19;
public const uint TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA = 22;
public const uint TLS_DH_DSS_WITH_AES_128_CBC_SHA256 = 62;
public const uint TLS_DH_RSA_WITH_AES_128_CBC_SHA256 = 63;
public const uint TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 = 64;
public const uint TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 = 103;
public const uint TLS_DH_DSS_WITH_AES_256_CBC_SHA256 = 104;
public const uint TLS_DH_RSA_WITH_AES_256_CBC_SHA256 = 105;
public const uint TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 = 106;
public const uint TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 = 107;
public const uint TLS_DH_anon_WITH_RC4_128_MD5 = 24;
public const uint TLS_DH_anon_WITH_3DES_EDE_CBC_SHA = 27;
public const uint TLS_DH_anon_WITH_AES_128_CBC_SHA256 = 108;
public const uint TLS_DH_anon_WITH_AES_256_CBC_SHA256 = 109;
public const uint TLS_PSK_WITH_RC4_128_SHA = 138;
public const uint TLS_PSK_WITH_3DES_EDE_CBC_SHA = 139;
public const uint TLS_PSK_WITH_AES_128_CBC_SHA = 140;
public const uint TLS_PSK_WITH_AES_256_CBC_SHA = 141;
public const uint TLS_DHE_PSK_WITH_RC4_128_SHA = 142;
public const uint TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA = 143;
public const uint TLS_DHE_PSK_WITH_AES_128_CBC_SHA = 144;
public const uint TLS_DHE_PSK_WITH_AES_256_CBC_SHA = 145;
public const uint TLS_RSA_PSK_WITH_RC4_128_SHA = 146;
public const uint TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA = 147;
public const uint TLS_RSA_PSK_WITH_AES_128_CBC_SHA = 148;
public const uint TLS_RSA_PSK_WITH_AES_256_CBC_SHA = 149;
public const uint TLS_PSK_WITH_NULL_SHA = 44;
public const uint TLS_DHE_PSK_WITH_NULL_SHA = 45;
public const uint TLS_RSA_PSK_WITH_NULL_SHA = 46;
public const uint TLS_RSA_WITH_AES_128_GCM_SHA256 = 156;
public const uint TLS_RSA_WITH_AES_256_GCM_SHA384 = 157;
public const uint TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 = 158;
public const uint TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 = 159;
public const uint TLS_DH_RSA_WITH_AES_128_GCM_SHA256 = 160;
public const uint TLS_DH_RSA_WITH_AES_256_GCM_SHA384 = 161;
public const uint TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 = 162;
public const uint TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 = 163;
public const uint TLS_DH_DSS_WITH_AES_128_GCM_SHA256 = 164;
public const uint TLS_DH_DSS_WITH_AES_256_GCM_SHA384 = 165;
public const uint TLS_DH_anon_WITH_AES_128_GCM_SHA256 = 166;
public const uint TLS_DH_anon_WITH_AES_256_GCM_SHA384 = 167;
public const uint TLS_PSK_WITH_AES_128_GCM_SHA256 = 168;
public const uint TLS_PSK_WITH_AES_256_GCM_SHA384 = 169;
public const uint TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 = 170;
public const uint TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 = 171;
public const uint TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 = 172;
public const uint TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 = 173;
public const uint TLS_PSK_WITH_AES_128_CBC_SHA256 = 174;
public const uint TLS_PSK_WITH_AES_256_CBC_SHA384 = 175;
public const uint TLS_PSK_WITH_NULL_SHA256 = 176;
public const uint TLS_PSK_WITH_NULL_SHA384 = 177;
public const uint TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 = 178;
public const uint TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 = 179;
public const uint TLS_DHE_PSK_WITH_NULL_SHA256 = 180;
public const uint TLS_DHE_PSK_WITH_NULL_SHA384 = 181;
public const uint TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 = 182;
public const uint TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 = 183;
public const uint TLS_RSA_PSK_WITH_NULL_SHA256 = 184;
public const uint TLS_RSA_PSK_WITH_NULL_SHA384 = 185;
public const uint TLS_AES_128_GCM_SHA256 = 4865;
public const uint TLS_AES_256_GCM_SHA384 = 4866;
public const uint TLS_CHACHA20_POLY1305_SHA256 = 4867;
public const uint TLS_AES_128_CCM_SHA256 = 4868;
public const uint TLS_AES_128_CCM_8_SHA256 = 4869;
public const uint TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 = 49187;
public const uint TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 = 49188;
public const uint TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 = 49189;
public const uint TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA384 = 49190;
public const uint TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 = 49191;
public const uint TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 = 49192;
public const uint TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256 = 49193;
public const uint TLS_ECDH_RSA_WITH_AES_256_CBC_SHA384 = 49194;
public const uint TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 = 49195;
public const uint TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 = 49196;
public const uint TLS_ECDH_ECDSA_WITH_AES_128_GCM_SHA256 = 49197;
public const uint TLS_ECDH_ECDSA_WITH_AES_256_GCM_SHA384 = 49198;
public const uint TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 = 49199;
public const uint TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 = 49200;
public const uint TLS_ECDH_RSA_WITH_AES_128_GCM_SHA256 = 49201;
public const uint TLS_ECDH_RSA_WITH_AES_256_GCM_SHA384 = 49202;
public const uint TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 = 52392;
public const uint TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 = 52393;
public const uint TLS_EMPTY_RENEGOTIATION_INFO_SCSV = 255;
public const uint SSL_RSA_WITH_RC2_CBC_MD5 = 65408;
public const uint SSL_RSA_WITH_IDEA_CBC_MD5 = 65409;
public const uint SSL_RSA_WITH_DES_CBC_MD5 = 65410;
public const uint SSL_RSA_WITH_3DES_EDE_CBC_MD5 = 65411;
public const uint SSL_NO_SUCH_CIPHERSUITE = 65535;
#endif

public enum SSLCiphersuiteGroup : int
{
    Default = 0,
    Compatibility = 1,
    Legacy = 2,
    ATS = 3,
    ATSCompatibility = 4,
}

#endif
