// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Security.framework (cssmaci.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Security;

#if MACOS

#pragma comment(framework, "Security")

public delegate CSSM_RETURN cssm_spi_ac_funcsAuthComputeFunction(CSSM_AC_HANDLE arg0, CSSM_TUPLEGROUP* arg1, CSSM_TUPLEGROUP* arg2, uint32 arg3, CSSM_LIST* arg4, CSSM_LIST* arg5, CSSM_LIST* arg6, CSSM_TUPLEGROUP_PTR arg7);

public delegate CSSM_RETURN cssm_spi_ac_funcsPassThroughFunction(CSSM_AC_HANDLE arg0, CSSM_TP_HANDLE arg1, CSSM_CL_HANDLE arg2, CSSM_CC_HANDLE arg3, CSSM_DL_DB_LIST* arg4, uint32 arg5, void* arg6, void** arg7);

/// Deprecated in macOS 10.7.
public struct cssm_spi_ac_funcs
{
    public cssm_spi_ac_funcsAuthComputeFunction AuthCompute;
    public cssm_spi_ac_funcsPassThroughFunction PassThrough;
}

/// Deprecated in macOS 10.7.
public using CSSM_SPI_AC_FUNCS = cssm_spi_ac_funcs;

/// Deprecated in macOS 10.7.
public using CSSM_SPI_AC_FUNCS_PTR = cssm_spi_ac_funcs*;

public const int _CSSMACI_H_ = 1;

#endif
