// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AudioToolbox.framework (AudioFileStream.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AudioToolbox;

import MacOS.CoreAudioTypes;
import MacOS.System;

#if MACOS

#pragma comment(framework, "AudioToolbox")

[Flags]
public enum AudioFileStreamPropertyFlags : uint
{
    PropertyIsCached = 1,
    CacheProperty = 2,
}

[Flags]
public enum AudioFileStreamParseFlags : uint
{
    kAudioFileStreamParseFlag_Discontinuity = 1,
}

[Flags]
public enum AudioFileStreamSeekFlags : uint
{
    kAudioFileStreamSeekFlag_OffsetIsEstimated = 1,
}

public using AudioFileStreamPropertyID = UInt32;

public struct OpaqueAudioFileStreamID;

public using AudioFileStreamID = OpaqueAudioFileStreamID*;

public delegate void AudioFileStream_PropertyListenerProc(void* arg0, AudioFileStreamID arg1, AudioFileStreamPropertyID arg2, AudioFileStreamPropertyFlags* arg3);

public delegate void AudioFileStream_PacketsProc(void* arg0, UInt32 arg1, UInt32 arg2, void* arg3, AudioStreamPacketDescription* arg4);

public const int kAudioFileStreamError_UnsupportedFileType = 1954115647;
public const int kAudioFileStreamError_UnsupportedDataFormat = 1718449215;
public const int kAudioFileStreamError_UnsupportedProperty = 1886681407;
public const int kAudioFileStreamError_BadPropertySize = 561211770;
public const int kAudioFileStreamError_NotOptimized = 1869640813;
public const int kAudioFileStreamError_InvalidPacketOffset = 1885563711;
public const int kAudioFileStreamError_InvalidFile = 1685348671;
public const int kAudioFileStreamError_ValueUnknown = 1970170687;
public const int kAudioFileStreamError_DataUnavailable = 1836020325;
public const int kAudioFileStreamError_IllegalOperation = 1852797029;
public const int kAudioFileStreamError_UnspecifiedError = 2003334207;
public const int kAudioFileStreamError_DiscontinuityCantRecover = 1685283617;

public const uint kAudioFileStreamProperty_ReadyToProducePackets = 1919247481;
public const uint kAudioFileStreamProperty_FileFormat = 1717988724;
public const uint kAudioFileStreamProperty_DataFormat = 1684434292;
public const uint kAudioFileStreamProperty_FormatList = 1718383476;
public const uint kAudioFileStreamProperty_MagicCookieData = 1835493731;
public const uint kAudioFileStreamProperty_AudioDataByteCount = 1650683508;
public const uint kAudioFileStreamProperty_AudioDataPacketCount = 1885564532;
public const uint kAudioFileStreamProperty_MaximumPacketSize = 1886616165;
public const uint kAudioFileStreamProperty_DataOffset = 1685022310;
public const uint kAudioFileStreamProperty_ChannelLayout = 1668112752;
public const uint kAudioFileStreamProperty_PacketToFrame = 1886086770;
public const uint kAudioFileStreamProperty_FrameToPacket = 1718775915;
public const uint kAudioFileStreamProperty_RestrictsRandomAccess = 1920098672;
public const uint kAudioFileStreamProperty_PacketToRollDistance = 1886089836;
public const uint kAudioFileStreamProperty_PreviousIndependentPacket = 1885957732;
public const uint kAudioFileStreamProperty_NextIndependentPacket = 1852403300;
public const uint kAudioFileStreamProperty_PacketToDependencyInfo = 1886086256;
public const uint kAudioFileStreamProperty_PacketToByte = 1886085753;
public const uint kAudioFileStreamProperty_ByteToPacket = 1652125803;
public const uint kAudioFileStreamProperty_PacketTableInfo = 1886283375;
public const uint kAudioFileStreamProperty_PacketSizeUpperBound = 1886090594;
public const uint kAudioFileStreamProperty_AverageBytesPerPacket = 1633841264;
public const uint kAudioFileStreamProperty_BitRate = 1651663220;
public const uint kAudioFileStreamProperty_InfoDictionary = 1768842863;

public extern "C" OSStatus AudioFileStreamOpen(void* inClientData, AudioFileStream_PropertyListenerProc inPropertyListenerProc, AudioFileStream_PacketsProc inPacketsProc, AudioFileTypeID inFileTypeHint, AudioFileStreamID* outAudioFileStream);

public extern "C" OSStatus AudioFileStreamParseBytes(AudioFileStreamID inAudioFileStream, UInt32 inDataByteSize, void* inData, AudioFileStreamParseFlags inFlags);

public extern "C" OSStatus AudioFileStreamSeek(AudioFileStreamID inAudioFileStream, SInt64 inPacketOffset, SInt64* outDataByteOffset, AudioFileStreamSeekFlags* ioFlags);

public extern "C" OSStatus AudioFileStreamGetPropertyInfo(AudioFileStreamID inAudioFileStream, AudioFileStreamPropertyID inPropertyID, UInt32* outPropertyDataSize, Boolean* outWritable);

public extern "C" OSStatus AudioFileStreamGetProperty(AudioFileStreamID inAudioFileStream, AudioFileStreamPropertyID inPropertyID, UInt32* ioPropertyDataSize, void* outPropertyData);

public extern "C" OSStatus AudioFileStreamSetProperty(AudioFileStreamID inAudioFileStream, AudioFileStreamPropertyID inPropertyID, UInt32 inPropertyDataSize, void* inPropertyData);

public extern "C" OSStatus AudioFileStreamClose(AudioFileStreamID inAudioFileStream);

#endif
