// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AudioToolbox.framework (AudioConverter.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AudioToolbox;

import MacOS.CoreAudioTypes;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "AudioToolbox")

public struct OpaqueAudioConverter;

public using AudioConverterRef = OpaqueAudioConverter*;

public using AudioConverterPropertyID = UInt32;

public const uint kAudioConverterPropertyMinimumInputBufferSize = 1835623027;
public const uint kAudioConverterPropertyMinimumOutputBufferSize = 1836016243;
public const uint kAudioConverterPropertyMaximumInputPacketSize = 2020175987;
public const uint kAudioConverterPropertyMaximumOutputPacketSize = 2020569203;
public const uint kAudioConverterPropertyCalculateInputBufferSize = 1667850867;
public const uint kAudioConverterPropertyCalculateOutputBufferSize = 1668244083;
public const uint kAudioConverterPropertyInputCodecParameters = 1768121456;
public const uint kAudioConverterPropertyOutputCodecParameters = 1868784752;
public const uint kAudioConverterSampleRateConverterComplexity = 1936876385;
public const uint kAudioConverterSampleRateConverterQuality = 1936876401;
public const uint kAudioConverterSampleRateConverterInitialPhase = 1936876400;
public const uint kAudioConverterCodecQuality = 1667527029;
public const uint kAudioConverterPrimeMethod = 1886547309;
public const uint kAudioConverterPrimeInfo = 1886546285;
public const uint kAudioConverterChannelMap = 1667788144;
public const uint kAudioConverterDecompressionMagicCookie = 1684891491;
public const uint kAudioConverterCompressionMagicCookie = 1668114275;
public const uint kAudioConverterEncodeBitRate = 1651663220;
public const uint kAudioConverterEncodeAdjustableSampleRate = 1634366322;
public const uint kAudioConverterInputChannelLayout = 1768123424;
public const uint kAudioConverterOutputChannelLayout = 1868786720;
public const uint kAudioConverterApplicableEncodeBitRates = 1634034290;
public const uint kAudioConverterAvailableEncodeBitRates = 1986355826;
public const uint kAudioConverterApplicableEncodeSampleRates = 1634038642;
public const uint kAudioConverterAvailableEncodeSampleRates = 1986360178;
public const uint kAudioConverterAvailableEncodeChannelLayoutTags = 1634034540;
public const uint kAudioConverterCurrentOutputStreamDescription = 1633906532;
public const uint kAudioConverterCurrentInputStreamDescription = 1633904996;
public const uint kAudioConverterPropertySettings = 1633906803;
public const uint kAudioConverterPropertyBitDepthHint = 1633903204;
public const uint kAudioConverterPropertyFormatList = 1718383476;
public const uint kAudioConverterPropertyPerformDownmix = 1684892024;
public const uint kAudioConverterPropertyChannelMixMap = 1835884912;

public const uint kAudioConverterPropertyDithering = 1684632680;
public const uint kAudioConverterPropertyDitherBitDepth = 1684171124;

public const uint kDitherAlgorithm_TPDF = 1;
public const uint kDitherAlgorithm_NoiseShaping = 2;

public const uint kAudioConverterQuality_Max = 127;
public const uint kAudioConverterQuality_High = 96;
public const uint kAudioConverterQuality_Medium = 64;
public const uint kAudioConverterQuality_Low = 32;
public const uint kAudioConverterQuality_Min = 0;

public const uint kAudioConverterSampleRateConverterComplexity_Linear = 1818848869;
public const uint kAudioConverterSampleRateConverterComplexity_Normal = 1852797549;
public const uint kAudioConverterSampleRateConverterComplexity_Mastering = 1650553971;
public const uint kAudioConverterSampleRateConverterComplexity_MinimumPhase = 1835626096;

public const uint kConverterPrimeMethod_Pre = 0;
public const uint kConverterPrimeMethod_Normal = 1;
public const uint kConverterPrimeMethod_None = 2;

public struct AudioConverterPrimeInfo
{
    public UInt32 leadingFrames;
    public UInt32 trailingFrames;
}

[Flags]
public enum AudioConverterOptions : uint
{
    kAudioConverterOption_Unbuffered = 65536,
}

public const int kAudioConverterErr_FormatNotSupported = 1718449215;
public const int kAudioConverterErr_OperationNotSupported = 1869627199;
public const int kAudioConverterErr_PropertyNotSupported = 1886547824;
public const int kAudioConverterErr_InvalidInputSize = 1768846202;
public const int kAudioConverterErr_InvalidOutputSize = 1869902714;
public const int kAudioConverterErr_UnspecifiedError = 2003329396;
public const int kAudioConverterErr_BadPropertySizeError = 561211770;
public const int kAudioConverterErr_RequiresPacketDescriptionsError = 561015652;
public const int kAudioConverterErr_InputSampleRateOutOfRange = 560558962;
public const int kAudioConverterErr_OutputSampleRateOutOfRange = 560952178;

public objc closure void AudioConverterPrepareInCompletionBlock(OSStatus arg0);

/// macOS 15.0 and later.
public extern "C" void AudioConverterPrepare(UInt32 inFlags, void* ioReserved, AudioConverterPrepareInCompletionBlock? inCompletionBlock);

public extern "C" OSStatus AudioConverterNew(AudioStreamBasicDescription* inSourceFormat, AudioStreamBasicDescription* inDestinationFormat, AudioConverterRef* outAudioConverter);

public extern "C" OSStatus AudioConverterNewSpecific(AudioStreamBasicDescription* inSourceFormat, AudioStreamBasicDescription* inDestinationFormat, UInt32 inNumberClassDescriptions, AudioClassDescription* inClassDescriptions, AudioConverterRef* outAudioConverter);

/// macOS 15.0 and later.
public extern "C" OSStatus AudioConverterNewWithOptions(AudioStreamBasicDescription* inSourceFormat, AudioStreamBasicDescription* inDestinationFormat, AudioConverterOptions inOptions, AudioConverterRef* outAudioConverter);

public extern "C" OSStatus AudioConverterDispose(AudioConverterRef inAudioConverter);

public extern "C" OSStatus AudioConverterReset(AudioConverterRef inAudioConverter);

public extern "C" OSStatus AudioConverterGetPropertyInfo(AudioConverterRef inAudioConverter, AudioConverterPropertyID inPropertyID, UInt32* outSize, Boolean* outWritable);

public extern "C" OSStatus AudioConverterGetProperty(AudioConverterRef inAudioConverter, AudioConverterPropertyID inPropertyID, UInt32* ioPropertyDataSize, void* outPropertyData);

public extern "C" OSStatus AudioConverterSetProperty(AudioConverterRef inAudioConverter, AudioConverterPropertyID inPropertyID, UInt32 inPropertyDataSize, void* inPropertyData);

public extern "C" OSStatus AudioConverterConvertBuffer(AudioConverterRef inAudioConverter, UInt32 inInputDataSize, void* inInputData, UInt32* ioOutputDataSize, void* outOutputData);

public delegate OSStatus AudioConverterComplexInputDataProc(AudioConverterRef arg0, UInt32* arg1, AudioBufferList* arg2, AudioStreamPacketDescription** arg3, void* arg4);

public delegate OSStatus AudioConverterComplexInputDataProcRealtimeSafe(AudioConverterRef arg0, UInt32* arg1, AudioBufferList* arg2, AudioStreamPacketDescription** arg3, void* arg4);

public extern "C" OSStatus AudioConverterFillComplexBuffer(AudioConverterRef inAudioConverter, AudioConverterComplexInputDataProc inInputDataProc, void* inInputDataProcUserData, UInt32* ioOutputDataPacketSize, AudioBufferList* outOutputData, AudioStreamPacketDescription* outPacketDescription);

/// macOS 26.0 and later.
public extern "C" OSStatus AudioConverterFillComplexBufferRealtimeSafe(AudioConverterRef inAudioConverter, AudioConverterComplexInputDataProcRealtimeSafe inInputDataProc, void* inInputDataProcUserData, UInt32* ioOutputDataPacketSize, AudioBufferList* outOutputData, AudioStreamPacketDescription* outPacketDescription);

/// macOS 26.0 and later.
public extern "C" OSStatus AudioConverterFillComplexBufferWithPacketDependencies(AudioConverterRef inAudioConverter, AudioConverterComplexInputDataProc inInputDataProc, void* inInputDataProcUserData, UInt32* ioOutputDataPacketSize, AudioBufferList* outOutputData, AudioStreamPacketDescription* outPacketDescriptions, AudioStreamPacketDependencyDescription* outPacketDependencies);

public extern "C" OSStatus AudioConverterConvertComplexBuffer(AudioConverterRef inAudioConverter, UInt32 inNumberPCMFrames, AudioBufferList* inInputData, AudioBufferList* outOutputData);

public const uint kAudioConverterPropertyMaximumInputBufferSize = 2020172403;
public const uint kAudioConverterSampleRateConverterAlgorithm = 1936876393;

public delegate OSStatus AudioConverterInputDataProc(AudioConverterRef arg0, UInt32* arg1, void** arg2, void* arg3);

/// Deprecated in macOS 10.5.
public extern "C" OSStatus AudioConverterFillBuffer(AudioConverterRef inAudioConverter, AudioConverterInputDataProc inInputDataProc, void* inInputDataProcUserData, UInt32* ioOutputDataSize, void* outOutputData);

#endif
