// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AudioToolbox.framework (MusicDevice.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AudioToolbox;

import MacOS.CoreMIDI;
import MacOS.System;

#if MACOS

#pragma comment(framework, "AudioToolbox")

public using MusicDeviceInstrumentID = UInt32;

public struct MusicDeviceStdNoteParams
{
    public UInt32 argCount;
    public Float32 mPitch;
    public Float32 mVelocity;
}

public struct NoteParamsControlValue
{
    public AudioUnitParameterID mID;
    public AudioUnitParameterValue mValue;
}

public struct MusicDeviceNoteParams
{
    public UInt32 argCount;
    public Float32 mPitch;
    public Float32 mVelocity;
    public NoteParamsControlValue[1] mControls;
}

public const uint kMusicNoteEvent_UseGroupInstrument = 4294967295u;
public const uint kMusicNoteEvent_Unused = 4294967295u;

public using MusicDeviceGroupID = UInt32;

public using NoteInstanceID = UInt32;

public using MusicDeviceComponent = AudioComponentInstance;

public extern "C" OSStatus MusicDeviceMIDIEvent(MusicDeviceComponent inUnit, UInt32 inStatus, UInt32 inData1, UInt32 inData2, UInt32 inOffsetSampleFrame);

public extern "C" OSStatus MusicDeviceSysEx(MusicDeviceComponent inUnit, UInt8* inData, UInt32 inLength);

public extern "C" OSStatus MusicDeviceMIDIEventList(MusicDeviceComponent inUnit, UInt32 inOffsetSampleFrame, MIDIEventList* evtList);

public extern "C" OSStatus MusicDeviceStartNote(MusicDeviceComponent inUnit, MusicDeviceInstrumentID inInstrument, MusicDeviceGroupID inGroupID, NoteInstanceID* outNoteInstanceID, UInt32 inOffsetSampleFrame, MusicDeviceNoteParams* inParams);

public extern "C" OSStatus MusicDeviceStopNote(MusicDeviceComponent inUnit, MusicDeviceGroupID inGroupID, NoteInstanceID inNoteInstanceID, UInt32 inOffsetSampleFrame);

public const int kMusicDeviceRange = 256;
public const int kMusicDeviceMIDIEventSelect = 257;
public const int kMusicDeviceSysExSelect = 258;
public const int kMusicDevicePrepareInstrumentSelect = 259;
public const int kMusicDeviceReleaseInstrumentSelect = 260;
public const int kMusicDeviceStartNoteSelect = 261;
public const int kMusicDeviceStopNoteSelect = 262;
public const int kMusicDeviceMIDIEventListSelect = 263;

public delegate OSStatus MusicDeviceMIDIEventProc(void* arg0, UInt32 arg1, UInt32 arg2, UInt32 arg3, UInt32 arg4);

public delegate OSStatus MusicDeviceSysExProc(void* arg0, UInt8* arg1, UInt32 arg2);

public delegate OSStatus MusicDeviceStartNoteProc(void* arg0, MusicDeviceInstrumentID arg1, MusicDeviceGroupID arg2, NoteInstanceID* arg3, UInt32 arg4, MusicDeviceNoteParams* arg5);

public delegate OSStatus MusicDeviceStopNoteProc(void* arg0, MusicDeviceGroupID arg1, NoteInstanceID arg2, UInt32 arg3);

/// Deprecated in macOS 10.5.
public extern "C" OSStatus MusicDevicePrepareInstrument(MusicDeviceComponent inUnit, MusicDeviceInstrumentID inInstrument);

/// Deprecated in macOS 10.5.
public extern "C" OSStatus MusicDeviceReleaseInstrument(MusicDeviceComponent inUnit, MusicDeviceInstrumentID inInstrument);

#endif
