// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from DiscRecording.framework (DRContentFolder.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.DiscRecording;

import MacOS.CoreFoundation;
import MacOS.CoreServices;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "DiscRecording")

public extern "C" CFTypeID DRFolderGetTypeID();

/// Deprecated in macOS 10.14.
[ReturnsRetained] public extern "C" DRFolderRef? DRFolderCreateReal(FSRef* fsRef);

[ReturnsRetained] public extern "C" DRFolderRef? DRFolderCreateRealWithURL(CFURLRef? urlRef);

[ReturnsRetained] public extern "C" DRFolderRef? DRFolderCreateVirtual(CFStringRef? baseName);

public extern "C" void DRFolderConvertRealToVirtual(DRFolderRef? realFolder);

public extern "C" void DRFolderAddChild(DRFolderRef? parent, DRFSObjectRef? newChild);

public extern "C" void DRFolderRemoveChild(DRFolderRef? parent, DRFSObjectRef? child);

public extern "C" UInt32 DRFolderCountChildren(DRFolderRef? folder);

[ReturnsRetained] public extern "C" CFArrayRef? DRFolderCopyChildren(DRFolderRef? folder);

#endif
