// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from DiscRecording.framework (DRContentObject.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.DiscRecording;

import MacOS.CoreFoundation;
import MacOS.CoreServices;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "DiscRecording")

public struct __DRFile;

[CFType("DRFileGetTypeID")]
public extern objc class DRFileRef : CFTypeRef { }

public struct __DRFolder;

[CFType("DRFolderGetTypeID")]
public extern objc class DRFolderRef : CFTypeRef { }

public using DRFSObjectRef = DRTypeRef;

public using DRFilesystemMask = UInt32;

public const uint kDRFilesystemMaskISO9660 = 1;
public const uint kDRFilesystemMaskJoliet = 2;
public const uint kDRFilesystemMaskUDF = 4;
public const uint kDRFilesystemMaskHFSPlus = 8;
public const uint kDRFilesystemMaskDefault = 4294967295u;

public extern "C" Boolean DRFSObjectIsVirtual(DRFSObjectRef? object);

/// Deprecated in macOS 10.14.
public extern "C" void DRFSObjectGetRealFSRef(DRFSObjectRef? object, FSRef* fsRef);

[ReturnsRetained]
public extern "C" CFURLRef? DRFSObjectCopyRealURL(DRFSObjectRef? object);

public extern "C" DRFolderRef? DRFSObjectGetParent(DRFSObjectRef? object);

[ReturnsRetained]
public extern "C" CFStringRef? DRFSObjectCopyBaseName(DRFSObjectRef? object);

[ReturnsRetained]
public extern "C" CFStringRef? DRFSObjectCopySpecificName(DRFSObjectRef? object, CFStringRef? fsKey);

[ReturnsRetained]
public extern "C" CFDictionaryRef? DRFSObjectCopySpecificNames(DRFSObjectRef? object);

[ReturnsRetained]
public extern "C" CFStringRef? DRFSObjectCopyMangledName(DRFSObjectRef? object, CFStringRef? fsKey);

[ReturnsRetained]
public extern "C" CFDictionaryRef? DRFSObjectCopyMangledNames(DRFSObjectRef? object);

[ReturnsRetained]
public extern "C" CFTypeRef? DRFSObjectCopyFilesystemProperty(DRFSObjectRef? object, CFStringRef? fsKey, CFStringRef? propertyKey, Boolean coalesce);

[ReturnsRetained]
public extern "C" CFDictionaryRef? DRFSObjectCopyFilesystemProperties(DRFSObjectRef? object, CFStringRef? fsKey, Boolean coalesce);

public extern "C" DRFilesystemMask DRFSObjectGetFilesystemMask(DRFSObjectRef? object, DRFilesystemMask* explicitMask, DRFilesystemMask* effectiveMask);

public extern "C" void DRFSObjectSetBaseName(DRFSObjectRef? object, CFStringRef? baseName);

public extern "C" void DRFSObjectSetSpecificName(DRFSObjectRef? object, CFStringRef? fsKey, CFStringRef? specificName);

public extern "C" void DRFSObjectSetSpecificNames(DRFSObjectRef? object, CFDictionaryRef? specificNames);

public extern "C" void DRFSObjectSetFilesystemProperty(DRFSObjectRef? object, CFStringRef? fsKey, CFStringRef? propertyKey, CFTypeRef? value);

public extern "C" void DRFSObjectSetFilesystemProperties(DRFSObjectRef? object, CFStringRef? fsKey, CFDictionaryRef? properties);

public extern "C" void DRFSObjectSetFilesystemMask(DRFSObjectRef? object, DRFilesystemMask newMask);

#endif
