// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

using System.Text;
using Stainless.Binding;
using Stainless.Syntax;

namespace Stainless.Driver;

/// <summary>
/// The module definition file that gives a Windows library the export names its
/// source asked for.
///
/// <para>
/// The rule this exists to keep is the one the documentation already states:
/// <b>a library's export table is exactly its <c>export "C"</c> functions</b>.
/// On x64 that is true without help, because the symbol and the name are the
/// same string. On 32-bit x86 they are not — a calling convention decorates the
/// symbol, so <c>export "C" __stdcall int DllGetClassObject(...)</c> is
/// <c>_DllGetClassObject@12</c> in the object file, and a table built from
/// symbols exports that.
/// </para>
///
/// <para>
/// Which is the wrong name. Windows' own COM loader calls
/// <c>GetProcAddress(module, "DllGetClassObject")</c>, and a server whose export
/// is decorated is a server COM cannot find. Every C++ COM server solves this
/// the same way and has since 1993: a <c>.def</c> naming the exports, which the
/// linker uses in place of what the symbols happen to be called.
/// </para>
///
/// <para>
/// The convention itself is not the problem and must not change: <c>__stdcall</c>
/// is what the caller will use, and a callee that popped nothing where the
/// caller expected it to would unbalance the stack. Only the *name* is wrong,
/// so only the name is what this fixes.
/// </para>
/// </summary>
public static class ModuleDefinition
{
    /// <summary>
    /// The file's text, or null when this build needs none.
    ///
    /// Null is the common answer: a target whose symbols are already the names
    /// the source wrote needs no renaming, and writing a <c>.def</c> anyway
    /// would replace the linker's own export list with one that has to be kept
    /// correct for no gain.
    /// </summary>
    public static string? For(BoundProgram program)
    {
        // A .def is a PE concept. ELF and Mach-O export by visibility and have
        // no decoration to undo.
        if (!TargetPlatform.Current.IsWindows) return null;

        var renamed = program.Functions
            .Select(f => f.Symbol)
            .Where(f => f.Linkage is LinkageKind.ExportC && Mangler.IsDecorated(f))
            .OrderBy(f => f.Name, StringComparer.Ordinal)
            .ToList();

        if (renamed.Count == 0) return null;

        var text = new StringBuilder();
        text.AppendLine("; Generated by the Stainless compiler. Do not edit.");
        text.AppendLine(";");
        text.AppendLine("; Each line below exports a function under the name its source declared,");
        text.AppendLine("; rather than under the symbol its calling convention decorated. The");
        text.AppendLine("; convention is unchanged -- only the name in the export table is.");
        text.AppendLine();
        text.AppendLine("EXPORTS");

        foreach (var function in renamed)
            text.AppendLine($"    {function.Name} = {Mangler.Decorated(function)}");

        return text.ToString();
    }
}
