// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreFoundation.framework (CFLocale.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreFoundation;

import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CoreFoundation")

public using CFLocaleIdentifier = CFStringRef;

public using CFLocaleKey = CFStringRef;

public struct __CFLocale;

[CFType("CFLocaleGetTypeID")]
public extern objc class CFLocaleRef : CFTypeRef { }

public extern "C" CFTypeID CFLocaleGetTypeID();

public extern "C" CFLocaleRef? CFLocaleGetSystem();

[ReturnsRetained]
public extern "C" CFLocaleRef? CFLocaleCopyCurrent();

[ReturnsRetained]
public extern "C" CFArrayRef? CFLocaleCopyAvailableLocaleIdentifiers();

[ReturnsRetained]
public extern "C" CFArrayRef? CFLocaleCopyISOLanguageCodes();

[ReturnsRetained]
public extern "C" CFArrayRef? CFLocaleCopyISOCountryCodes();

[ReturnsRetained]
public extern "C" CFArrayRef? CFLocaleCopyISOCurrencyCodes();

[ReturnsRetained]
public extern "C" CFArrayRef? CFLocaleCopyCommonISOCurrencyCodes();

[ReturnsRetained]
public extern "C" CFArrayRef? CFLocaleCopyPreferredLanguages();

[ReturnsRetained]
public extern "C" CFLocaleIdentifier? CFLocaleCreateCanonicalLanguageIdentifierFromString(CFAllocatorRef? allocator, CFStringRef? localeIdentifier);

[ReturnsRetained]
public extern "C" CFLocaleIdentifier? CFLocaleCreateCanonicalLocaleIdentifierFromString(CFAllocatorRef? allocator, CFStringRef? localeIdentifier);

[ReturnsRetained]
public extern "C" CFLocaleIdentifier? CFLocaleCreateCanonicalLocaleIdentifierFromScriptManagerCodes(CFAllocatorRef? allocator, LangCode lcode, RegionCode rcode);

[ReturnsRetained]
public extern "C" CFLocaleIdentifier? CFLocaleCreateLocaleIdentifierFromWindowsLocaleCode(CFAllocatorRef? allocator, uint lcid);

public extern "C" uint CFLocaleGetWindowsLocaleCodeFromLocaleIdentifier(CFLocaleIdentifier? localeIdentifier);

public enum CFLocaleLanguageDirection : long
{
    Unknown = 0,
    LeftToRight = 1,
    RightToLeft = 2,
    TopToBottom = 3,
    BottomToTop = 4,
}

public extern "C" CFLocaleLanguageDirection CFLocaleGetLanguageCharacterDirection(CFStringRef? isoLangCode);

public extern "C" CFLocaleLanguageDirection CFLocaleGetLanguageLineDirection(CFStringRef? isoLangCode);

[ReturnsRetained]
public extern "C" CFDictionaryRef? CFLocaleCreateComponentsFromLocaleIdentifier(CFAllocatorRef? allocator, CFLocaleIdentifier? localeID);

[ReturnsRetained]
public extern "C" CFLocaleIdentifier? CFLocaleCreateLocaleIdentifierFromComponents(CFAllocatorRef? allocator, CFDictionaryRef? dictionary);

[ReturnsRetained]
public extern "C" CFLocaleRef? CFLocaleCreate(CFAllocatorRef? allocator, CFLocaleIdentifier? localeIdentifier);

[ReturnsRetained]
public extern "C" CFLocaleRef? CFLocaleCreateCopy(CFAllocatorRef? allocator, CFLocaleRef? locale);

public extern "C" CFLocaleIdentifier? CFLocaleGetIdentifier(CFLocaleRef? locale);

public extern "C" CFTypeRef? CFLocaleGetValue(CFLocaleRef? locale, CFLocaleKey? key);

[ReturnsRetained]
public extern "C" CFStringRef? CFLocaleCopyDisplayNameForPropertyValue(CFLocaleRef? displayLocale, CFLocaleKey? key, CFStringRef? value);

public extern "C" CFNotificationName? kCFLocaleCurrentLocaleDidChangeNotification;

public extern "C" CFLocaleKey? kCFLocaleIdentifier;

public extern "C" CFLocaleKey? kCFLocaleLanguageCode;

public extern "C" CFLocaleKey? kCFLocaleCountryCode;

public extern "C" CFLocaleKey? kCFLocaleScriptCode;

public extern "C" CFLocaleKey? kCFLocaleVariantCode;

public extern "C" CFLocaleKey? kCFLocaleExemplarCharacterSet;

public extern "C" CFLocaleKey? kCFLocaleCalendarIdentifier;

public extern "C" CFLocaleKey? kCFLocaleCalendar;

public extern "C" CFLocaleKey? kCFLocaleCollationIdentifier;

public extern "C" CFLocaleKey? kCFLocaleUsesMetricSystem;

public extern "C" CFLocaleKey? kCFLocaleMeasurementSystem;

public extern "C" CFLocaleKey? kCFLocaleDecimalSeparator;

public extern "C" CFLocaleKey? kCFLocaleGroupingSeparator;

public extern "C" CFLocaleKey? kCFLocaleCurrencySymbol;

public extern "C" CFLocaleKey? kCFLocaleCurrencyCode;

public extern "C" CFLocaleKey? kCFLocaleCollatorIdentifier;

public extern "C" CFLocaleKey? kCFLocaleQuotationBeginDelimiterKey;

public extern "C" CFLocaleKey? kCFLocaleQuotationEndDelimiterKey;

public extern "C" CFLocaleKey? kCFLocaleAlternateQuotationBeginDelimiterKey;

public extern "C" CFLocaleKey? kCFLocaleAlternateQuotationEndDelimiterKey;

public using CFCalendarIdentifier = CFStringRef;

public extern "C" CFCalendarIdentifier? kCFGregorianCalendar;

public extern "C" CFCalendarIdentifier? kCFBuddhistCalendar;

public extern "C" CFCalendarIdentifier? kCFChineseCalendar;

public extern "C" CFCalendarIdentifier? kCFHebrewCalendar;

public extern "C" CFCalendarIdentifier? kCFIslamicCalendar;

public extern "C" CFCalendarIdentifier? kCFIslamicCivilCalendar;

public extern "C" CFCalendarIdentifier? kCFJapaneseCalendar;

public extern "C" CFCalendarIdentifier? kCFRepublicOfChinaCalendar;

public extern "C" CFCalendarIdentifier? kCFPersianCalendar;

public extern "C" CFCalendarIdentifier? kCFIndianCalendar;

public extern "C" CFCalendarIdentifier? kCFISO8601Calendar;

public extern "C" CFCalendarIdentifier? kCFIslamicTabularCalendar;

public extern "C" CFCalendarIdentifier? kCFIslamicUmmAlQuraCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFBanglaCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFGujaratiCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFKannadaCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFMalayalamCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFMarathiCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFOdiaCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFTamilCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFTeluguCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFVikramCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFDangiCalendar;

/// macOS 26.0 and later.
public extern "C" CFCalendarIdentifier? kCFVietnameseCalendar;

#endif
