// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreFoundation.framework (CFPropertyList.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreFoundation;

import MacOS.System;

#if MACOS

#pragma comment(framework, "CoreFoundation")

[Flags]
public enum CFPropertyListMutabilityOptions : ulong
{
    Immutable = 0,
    MutableContainers = 1,
    MutableContainersAndLeaves = 2,
}

/// Deprecated in macOS 10.10.
public extern "C" CFPropertyListRef CFPropertyListCreateFromXMLData(CFAllocatorRef allocator, CFDataRef xmlData, CFOptionFlags mutabilityOption, CFStringRef* errorString);

/// Deprecated in macOS 10.10.
public extern "C" CFDataRef CFPropertyListCreateXMLData(CFAllocatorRef allocator, CFPropertyListRef propertyList);

public extern "C" CFPropertyListRef CFPropertyListCreateDeepCopy(CFAllocatorRef allocator, CFPropertyListRef propertyList, CFOptionFlags mutabilityOption);

public enum CFPropertyListFormat : long
{
    OpenStepFormat = 1,
    XMLFormat_v1_0 = 100,
    BinaryFormat_v1_0 = 200,
}

public extern "C" Boolean CFPropertyListIsValid(CFPropertyListRef plist, CFPropertyListFormat format);

/// Deprecated in macOS 10.10.
public extern "C" CFIndex CFPropertyListWriteToStream(CFPropertyListRef propertyList, CFWriteStreamRef stream, CFPropertyListFormat format, CFStringRef* errorString);

/// Deprecated in macOS 10.10.
public extern "C" CFPropertyListRef CFPropertyListCreateFromStream(CFAllocatorRef allocator, CFReadStreamRef stream, CFIndex streamLength, CFOptionFlags mutabilityOption, CFPropertyListFormat* format, CFStringRef* errorString);

public const long kCFPropertyListReadCorruptError = 3840;
public const long kCFPropertyListReadUnknownVersionError = 3841;
public const long kCFPropertyListReadStreamError = 3842;
public const long kCFPropertyListWriteStreamError = 3851;

public extern "C" CFPropertyListRef CFPropertyListCreateWithData(CFAllocatorRef allocator, CFDataRef data, CFOptionFlags options, CFPropertyListFormat* format, CFErrorRef* error);

public extern "C" CFPropertyListRef CFPropertyListCreateWithStream(CFAllocatorRef allocator, CFReadStreamRef stream, CFIndex streamLength, CFOptionFlags options, CFPropertyListFormat* format, CFErrorRef* error);

public extern "C" CFIndex CFPropertyListWrite(CFPropertyListRef propertyList, CFWriteStreamRef stream, CFPropertyListFormat format, CFOptionFlags options, CFErrorRef* error);

public extern "C" CFDataRef CFPropertyListCreateData(CFAllocatorRef allocator, CFPropertyListRef propertyList, CFPropertyListFormat format, CFOptionFlags options, CFErrorRef* error);

#endif
