// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreFoundation.framework (CFStringTokenizer.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreFoundation;

import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CoreFoundation")

[ReturnsRetained]
public extern "C" CFStringRef? CFStringTokenizerCopyBestStringLanguage(CFStringRef? string, CFRange range);

public struct __CFStringTokenizer;

[CFType("CFStringTokenizerGetTypeID")]
public extern objc class CFStringTokenizerRef : CFTypeRef { }

public const ulong kCFStringTokenizerUnitWord = 0;
public const ulong kCFStringTokenizerUnitSentence = 1;
public const ulong kCFStringTokenizerUnitParagraph = 2;
public const ulong kCFStringTokenizerUnitLineBreak = 3;
public const ulong kCFStringTokenizerUnitWordBoundary = 4;
public const ulong kCFStringTokenizerAttributeLatinTranscription = 65536;
public const ulong kCFStringTokenizerAttributeLanguage = 131072;

[Flags]
public enum CFStringTokenizerTokenType : ulong
{
    None = 0,
    Normal = 1,
    HasSubTokensMask = 2,
    HasDerivedSubTokensMask = 4,
    HasHasNumbersMask = 8,
    HasNonLettersMask = 16,
    IsCJWordMask = 32,
}

public extern "C" CFTypeID CFStringTokenizerGetTypeID();

[ReturnsRetained]
public extern "C" CFStringTokenizerRef? CFStringTokenizerCreate(CFAllocatorRef? alloc, CFStringRef? string, CFRange range, CFOptionFlags options, CFLocaleRef? locale);

public extern "C" void CFStringTokenizerSetString(CFStringTokenizerRef? tokenizer, CFStringRef? string, CFRange range);

public extern "C" CFStringTokenizerTokenType CFStringTokenizerGoToTokenAtIndex(CFStringTokenizerRef? tokenizer, CFIndex index);

public extern "C" CFStringTokenizerTokenType CFStringTokenizerAdvanceToNextToken(CFStringTokenizerRef? tokenizer);

public extern "C" CFRange CFStringTokenizerGetCurrentTokenRange(CFStringTokenizerRef? tokenizer);

[ReturnsRetained]
public extern "C" CFTypeRef? CFStringTokenizerCopyCurrentTokenAttribute(CFStringTokenizerRef? tokenizer, CFOptionFlags @attribute);

public extern "C" CFIndex CFStringTokenizerGetCurrentSubTokens(CFStringTokenizerRef? tokenizer, CFRange* ranges, CFIndex maxRangeLength, CFMutableArrayRef? derivedSubTokens);

#endif
