// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from MetricKit.framework (MXAppExitMetric.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.MetricKit;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "MetricKit")

public extern objc class MXForegroundExitData : NSObject, NSSecureCoding
{
    [Selector("cumulativeNormalAppExitCount")]
    public NSUInteger CumulativeNormalAppExitCount { get; }
    [Selector("cumulativeMemoryResourceLimitExitCount")]
    public NSUInteger CumulativeMemoryResourceLimitExitCount { get; }
    [Selector("cumulativeBadAccessExitCount")]
    public NSUInteger CumulativeBadAccessExitCount { get; }
    [Selector("cumulativeAbnormalExitCount")]
    public NSUInteger CumulativeAbnormalExitCount { get; }
    [Selector("cumulativeIllegalInstructionExitCount")]
    public NSUInteger CumulativeIllegalInstructionExitCount { get; }
    [Selector("cumulativeAppWatchdogExitCount")]
    public NSUInteger CumulativeAppWatchdogExitCount { get; }
}

public extern objc class MXBackgroundExitData : NSObject, NSSecureCoding
{
    [Selector("cumulativeNormalAppExitCount")]
    public NSUInteger CumulativeNormalAppExitCount { get; }
    [Selector("cumulativeMemoryResourceLimitExitCount")]
    public NSUInteger CumulativeMemoryResourceLimitExitCount { get; }
    [Selector("cumulativeCPUResourceLimitExitCount")]
    public NSUInteger CumulativeCPUResourceLimitExitCount { get; }
    [Selector("cumulativeMemoryPressureExitCount")]
    public NSUInteger CumulativeMemoryPressureExitCount { get; }
    [Selector("cumulativeBadAccessExitCount")]
    public NSUInteger CumulativeBadAccessExitCount { get; }
    [Selector("cumulativeAbnormalExitCount")]
    public NSUInteger CumulativeAbnormalExitCount { get; }
    [Selector("cumulativeIllegalInstructionExitCount")]
    public NSUInteger CumulativeIllegalInstructionExitCount { get; }
    [Selector("cumulativeAppWatchdogExitCount")]
    public NSUInteger CumulativeAppWatchdogExitCount { get; }
    [Selector("cumulativeSuspendedWithLockedFileExitCount")]
    public NSUInteger CumulativeSuspendedWithLockedFileExitCount { get; }
    [Selector("cumulativeBackgroundTaskAssertionTimeoutExitCount")]
    public NSUInteger CumulativeBackgroundTaskAssertionTimeoutExitCount { get; }
}

public extern objc class MXAppExitMetric : MXMetric
{
    [Selector("foregroundExitData")]
    public MXForegroundExitData ForegroundExitData { get; }
    [Selector("backgroundExitData")]
    public MXBackgroundExitData BackgroundExitData { get; }
}

#endif
