// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreML.framework (MLModelError.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreML;

import MacOS.Foundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CoreML")

public extern "C" NSString MLModelErrorDomain;

public enum MLModelError : long
{
    Generic = 0,
    FeatureType = 1,
    IO = 3,
    CustomLayer = 4,
    CustomModel = 5,
    Update = 6,
    Parameters = 7,
    ModelDecryptionKeyFetch = 8,
    ModelDecryption = 9,
    ModelCollection = 10,
    PredictionCancelled = 11,
}

#endif
