// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from BrowserEngineKit.framework (BETextSelectionTypes.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.BrowserEngineKit;

#if MACOS

#pragma comment(framework, "BrowserEngineKit")

public enum BEGestureType : long
{
    Loupe = 0,
    OneFingerTap = 1,
    DoubleTapAndHold = 2,
    DoubleTap = 3,
    OneFingerDoubleTap = 8,
    OneFingerTripleTap = 9,
    TwoFingerSingleTap = 10,
    TwoFingerRangedSelectGesture = 11,
    IMPhraseBoundaryDrag = 14,
    ForceTouch = 15,
}

public enum BESelectionTouchPhase : long
{
    Started = 0,
    Moved = 1,
    Ended = 2,
    EndedMovingForward = 3,
    EndedMovingBackward = 4,
    EndedNotMoving = 5,
}

[Flags]
public enum BESelectionFlags : ulong
{
    SelectionFlagsNone = 0,
    WordIsNearTap = 1,
    SelectionFlipped = 2,
    PhraseBoundaryChanged = 4,
}

#endif
