// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CloudKit.framework (CKFetchRecordZoneChangesOperation.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CloudKit;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CloudKit")

public objc closure void CKFetchRecordZoneChangesOperationRecordChangedBlock(CKRecord arg0);

public objc closure void CKFetchRecordZoneChangesOperationRecordWasChangedBlock(CKRecordID arg0, CKRecord? arg1, NSError? arg2);

public objc closure void CKFetchRecordZoneChangesOperationRecordWithIDWasDeletedBlock(CKRecordID arg0, CKRecordType arg1);

public objc closure void CKFetchRecordZoneChangesOperationRecordZoneChangeTokensUpdatedBlock(CKRecordZoneID arg0, CKServerChangeToken? arg1, NSData? arg2);

public objc closure void CKFetchRecordZoneChangesOperationRecordZoneFetchCompletionBlock(CKRecordZoneID arg0, CKServerChangeToken? arg1, NSData? arg2, bool arg3, NSError? arg4);

public objc closure void CKFetchRecordZoneChangesOperationFetchRecordZoneChangesCompletionBlock(NSError? arg0);

public extern objc class CKFetchRecordZoneChangesOperation : CKDatabaseOperation
{
    [Selector("recordZoneIDs", "setRecordZoneIDs:")]
    public NSArray? RecordZoneIDs { get; set; }
    [Selector("configurationsByRecordZoneID", "setConfigurationsByRecordZoneID:")]
    public NSDictionary? ConfigurationsByRecordZoneID { get; set; }
    [Selector("fetchAllChanges", "setFetchAllChanges:")]
    public bool FetchAllChanges { get; set; }
    /// Deprecated in macOS 12.0.
    [Selector("recordChangedBlock", "setRecordChangedBlock:")]
    public CKFetchRecordZoneChangesOperationRecordChangedBlock? RecordChangedBlock { get; set; }
    [Selector("recordWasChangedBlock", "setRecordWasChangedBlock:")]
    public CKFetchRecordZoneChangesOperationRecordWasChangedBlock? RecordWasChangedBlock { get; set; }
    [Selector("recordWithIDWasDeletedBlock", "setRecordWithIDWasDeletedBlock:")]
    public CKFetchRecordZoneChangesOperationRecordWithIDWasDeletedBlock? RecordWithIDWasDeletedBlock { get; set; }
    [Selector("recordZoneChangeTokensUpdatedBlock", "setRecordZoneChangeTokensUpdatedBlock:")]
    public CKFetchRecordZoneChangesOperationRecordZoneChangeTokensUpdatedBlock? RecordZoneChangeTokensUpdatedBlock { get; set; }
    [Selector("recordZoneFetchCompletionBlock", "setRecordZoneFetchCompletionBlock:")]
    public CKFetchRecordZoneChangesOperationRecordZoneFetchCompletionBlock? RecordZoneFetchCompletionBlock { get; set; }
    [Selector("fetchRecordZoneChangesCompletionBlock", "setFetchRecordZoneChangesCompletionBlock:")]
    public CKFetchRecordZoneChangesOperationFetchRecordZoneChangesCompletionBlock? FetchRecordZoneChangesCompletionBlock { get; set; }
    [Selector("init")]
    public Self Init();
    [Selector("initWithRecordZoneIDs:configurationsByRecordZoneID:")]
    public Self InitWithRecordZoneIDsConfigurationsByRecordZoneID(NSArray recordZoneIDs, NSDictionary? configurationsByRecordZoneID);
}

/// Deprecated, a category of CKFetchRecordZoneChangesOperation.
public extern objc class CKFetchRecordZoneChangesOperation
{
    /// Deprecated in macOS 10.14.
    [Selector("optionsByRecordZoneID", "setOptionsByRecordZoneID:")]
    public NSDictionary? OptionsByRecordZoneID { get; set; }
    /// Deprecated in macOS 10.14.
    [Selector("initWithRecordZoneIDs:optionsByRecordZoneID:")]
    public Self InitWithRecordZoneIDsOptionsByRecordZoneID(NSArray recordZoneIDs, NSDictionary? optionsByRecordZoneID);
}

public extern objc class CKFetchRecordZoneChangesConfiguration : NSObject, NSSecureCoding, NSCopying
{
    [Selector("previousServerChangeToken", "setPreviousServerChangeToken:")]
    public CKServerChangeToken? PreviousServerChangeToken { get; set; }
    [Selector("resultsLimit", "setResultsLimit:")]
    public NSUInteger ResultsLimit { get; set; }
    [Selector("desiredKeys", "setDesiredKeys:")]
    public NSArray? DesiredKeys { get; set; }
}

/// Deprecated in macOS 10.14.
public extern objc class CKFetchRecordZoneChangesOptions : NSObject, NSSecureCoding, NSCopying
{
    [Selector("previousServerChangeToken", "setPreviousServerChangeToken:")]
    public CKServerChangeToken? PreviousServerChangeToken { get; set; }
    [Selector("resultsLimit", "setResultsLimit:")]
    public NSUInteger ResultsLimit { get; set; }
    [Selector("desiredKeys", "setDesiredKeys:")]
    public NSArray? DesiredKeys { get; set; }
}

#endif
