// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CloudKit.framework (CKShare.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CloudKit;

import MacOS.Foundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CloudKit")

public extern "C" CKRecordType CKRecordTypeShare;

public extern "C" NSString CKRecordNameZoneWideShare;

public extern "C" CKRecordFieldKey CKShareTitleKey;

public extern "C" CKRecordFieldKey CKShareThumbnailImageDataKey;

public extern "C" CKRecordFieldKey CKShareTypeKey;

public extern objc class CKShare : CKRecord, NSSecureCoding, NSCopying
{
    [Selector("publicPermission", "setPublicPermission:")] public CKShareParticipantPermission PublicPermission { get; set; }
    [Selector("URL")] public NSURL? URL { get; }
    [Selector("participants")] public NSArray Participants { get; }
    [Selector("owner")] public CKShareParticipant Owner { get; }
    [Selector("currentUserParticipant")] public CKShareParticipant? CurrentUserParticipant { get; }
    /// macOS 26.0 and later.
    [Selector("requesters")] public NSArray Requesters { get; }
    /// macOS 26.0 and later.
    [Selector("blockedIdentities")] public NSArray BlockedIdentities { get; }
    /// macOS 26.0 and later.
    [Selector("allowsAccessRequests", "setAllowsAccessRequests:")] public bool AllowsAccessRequests { get; set; }
    [Selector("initWithRootRecord:")] public Self InitWithRootRecord(CKRecord rootRecord);
    [Selector("initWithRootRecord:shareID:")] public Self InitWithRootRecordShareID(CKRecord rootRecord, CKRecordID shareID);
    [Selector("initWithRecordZoneID:")] public Self InitWithRecordZoneID(CKRecordZoneID recordZoneID);
    [Selector("initWithCoder:")] public Self InitWithCoder(NSCoder aDecoder);
    [Selector("addParticipant:")] public void AddParticipant(CKShareParticipant participant);
    [Selector("removeParticipant:")] public void RemoveParticipant(CKShareParticipant participant);
    /// macOS 15.0 and later.
    [Selector("oneTimeURLForParticipantID:")] public NSURL? OneTimeURLForParticipantID(NSString participantID);
    /// macOS 26.0 and later.
    [Selector("denyRequesters:")] public void DenyRequesters(NSArray requesters);
    /// macOS 26.0 and later.
    [Selector("blockRequesters:")] public void BlockRequesters(NSArray requesters);
    /// macOS 26.0 and later.
    [Selector("unblockIdentities:")] public void UnblockIdentities(NSArray blockedIdentities);
}

#endif
