// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from SecurityFoundation.framework (SFAuthorization.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.SecurityFoundation;

import MacOS.Foundation;
import MacOS.Security;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "SecurityFoundation")

public extern objc class SFAuthorization : NSObject, NSSecureCoding
{
    [Selector("authorization")] public static AnyObject? Authorization();
    [Selector("authorizationRef")] public AuthorizationRef AuthorizationRef();
    [Selector("authorizationWithFlags:rights:environment:")] public static AnyObject? AuthorizationWithFlagsRightsEnvironment(AuthorizationFlags flags, AuthorizationRights* rights, AuthorizationEnvironment* environment);
    [Selector("initWithFlags:rights:environment:")] public AnyObject? InitWithFlagsRightsEnvironment(AuthorizationFlags flags, AuthorizationRights* rights, AuthorizationEnvironment* environment);
    [Selector("init")] public AnyObject? Init();
    [Selector("invalidateCredentials")] public void InvalidateCredentials();
    [Selector("obtainWithRight:flags:error:")] public bool ObtainWithRightFlagsError(AuthorizationString rightName, AuthorizationFlags flags, out NSError? error);
    [Selector("obtainWithRights:flags:environment:authorizedRights:error:")] public bool ObtainWithRightsFlagsEnvironmentAuthorizedRightsError(AuthorizationRights* rights, AuthorizationFlags flags, AuthorizationEnvironment* environment, AuthorizationRights** authorizedRights, out NSError? error);
}

/// SFAuthorizationDeprecated, a category of SFAuthorization.
public extern objc class SFAuthorization
{
    /// Deprecated in macOS 10.5.
    [Selector("permitWithRights:flags:environment:authorizedRights:")] public OSStatus PermitWithRightsFlagsEnvironmentAuthorizedRights(AuthorizationRights* rights, AuthorizationFlags flags, AuthorizationEnvironment* environment, AuthorizationRights* authorizedRights);
    /// Deprecated in macOS 10.5.
    [Selector("permitWithRight:flags:")] public OSStatus PermitWithRightFlags(AuthorizationString rightName, AuthorizationFlags flags);
}

#endif
