// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from SafariServices.framework (SFSafariApplication.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.SafariServices;

import MacOS.AppKit;
import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "SafariServices")

public extern "C" NSString? SFExtensionMessageKey;

public extern "C" NSString? SFExtensionProfileKey;

public objc closure void SFSafariApplicationGetActiveWindowWithCompletionHandlerCompletionHandlerBlock(SFSafariWindow? arg0);

public objc closure void SFSafariApplicationGetAllWindowsWithCompletionHandlerCompletionHandlerBlock(NSArray arg0);

public objc closure void SFSafariApplicationOpenWindowWithURLCompletionHandlerCompletionHandlerBlock(SFSafariWindow? arg0);

public objc closure void SFSafariApplicationGetHostApplicationWithCompletionHandlerCompletionHandlerBlock(NSRunningApplication arg0);

public objc closure void SFSafariApplicationShowPreferencesForExtensionWithIdentifierCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void SFSafariApplicationDispatchMessageWithNameToExtensionWithIdentifierUserInfoCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public extern objc class SFSafariApplication : NSObject
{
    [Selector("getActiveWindowWithCompletionHandler:")]
    public static void GetActiveWindowWithCompletionHandler(SFSafariApplicationGetActiveWindowWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("getAllWindowsWithCompletionHandler:")]
    public static void GetAllWindowsWithCompletionHandler(SFSafariApplicationGetAllWindowsWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("openWindowWithURL:completionHandler:")]
    public static void OpenWindowWithURLCompletionHandler(NSURL url, SFSafariApplicationOpenWindowWithURLCompletionHandlerCompletionHandlerBlock? completionHandler);
    [Selector("setToolbarItemsNeedUpdate")]
    public static void SetToolbarItemsNeedUpdate();
    [Selector("getHostApplicationWithCompletionHandler:")]
    public static void GetHostApplicationWithCompletionHandler(SFSafariApplicationGetHostApplicationWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("showPreferencesForExtensionWithIdentifier:completionHandler:")]
    public static void ShowPreferencesForExtensionWithIdentifierCompletionHandler(NSString identifier, SFSafariApplicationShowPreferencesForExtensionWithIdentifierCompletionHandlerCompletionHandlerBlock? completionHandler);
    [Selector("dispatchMessageWithName:toExtensionWithIdentifier:userInfo:completionHandler:")]
    public static void DispatchMessageWithNameToExtensionWithIdentifierUserInfoCompletionHandler(NSString messageName, NSString identifier, NSDictionary? userInfo, SFSafariApplicationDispatchMessageWithNameToExtensionWithIdentifierUserInfoCompletionHandlerCompletionHandlerBlock? completionHandler);
}

#endif
