// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Matter.framework (MTRDeviceControllerStartupParams.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Matter;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Matter")

public extern objc class MTRDeviceControllerStartupParams : NSObject
{
    [Selector("nocSigner")]
    public MTRKeypair? NocSigner { get; }
    [Selector("fabricID")]
    public NSNumber FabricID { get; }
    [Selector("ipk")]
    public NSData Ipk { get; }
    [Selector("vendorID", "setVendorID:")]
    public NSNumber? VendorID { get; set; }
    [Selector("nodeID", "setNodeID:")]
    public NSNumber? NodeID { get; set; }
    [Selector("caseAuthenticatedTags", "setCaseAuthenticatedTags:")]
    public NSSet? CaseAuthenticatedTags { get; set; }
    [Selector("rootCertificate", "setRootCertificate:")]
    public MTRCertificateDERBytes? RootCertificate { get; set; }
    [Selector("intermediateCertificate", "setIntermediateCertificate:")]
    public MTRCertificateDERBytes? IntermediateCertificate { get; set; }
    [Selector("operationalCertificate")]
    public MTRCertificateDERBytes? OperationalCertificate { get; }
    [Selector("operationalKeypair", "setOperationalKeypair:")]
    public MTRKeypair? OperationalKeypair { get; set; }
    [Selector("operationalCertificateIssuer", "setOperationalCertificateIssuer:")]
    public MTROperationalCertificateIssuer? OperationalCertificateIssuer { get; set; }
    [Selector("operationalCertificateIssuerQueue", "setOperationalCertificateIssuerQueue:")]
    public dispatch_queue_t? OperationalCertificateIssuerQueue { get; set; }
    [Selector("initWithIPK:fabricID:nocSigner:")]
    public Self InitWithIPKFabricIDNocSigner(NSData ipk, NSNumber fabricID, MTRKeypair nocSigner);
    [Selector("initWithIPK:operationalKeypair:operationalCertificate:intermediateCertificate:rootCertificate:")]
    public Self InitWithIPKOperationalKeypairOperationalCertificateIntermediateCertificateRootCertificate(NSData ipk, MTRKeypair operationalKeypair, MTRCertificateDERBytes operationalCertificate, MTRCertificateDERBytes? intermediateCertificate, MTRCertificateDERBytes rootCertificate);
}

/// Deprecated, a category of MTRDeviceControllerStartupParams.
public extern objc class MTRDeviceControllerStartupParams
{
    /// Deprecated in macOS 13.3.
    [Selector("fabricId")]
    public ulong FabricId { get; }
    /// Deprecated in macOS 13.3.
    [Selector("vendorId", "setVendorId:")]
    public NSNumber? VendorId { get; set; }
    /// Deprecated in macOS 13.3.
    [Selector("nodeId", "setNodeId:")]
    public NSNumber? NodeId { get; set; }
    /// Deprecated in macOS 13.3.
    [Selector("initWithSigningKeypair:fabricId:ipk:")]
    public Self InitWithSigningKeypairFabricIdIpk(MTRKeypair nocSigner, ulong fabricId, NSData ipk);
    /// Deprecated in macOS 13.3.
    [Selector("initWithOperationalKeypair:operationalCertificate:intermediateCertificate:rootCertificate:ipk:")]
    public Self InitWithOperationalKeypairOperationalCertificateIntermediateCertificateRootCertificateIpk(MTRKeypair operationalKeypair, MTRCertificateDERBytes operationalCertificate, MTRCertificateDERBytes? intermediateCertificate, MTRCertificateDERBytes rootCertificate, NSData ipk);
}

#endif
