// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Matter.framework (MTROTAHeader.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Matter;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Matter")

public enum MTROTAImageDigestType : ulong
{
    Sha256 = 1,
    Sha256_128 = 2,
    Sha256_120 = 3,
    Sha256_96 = 4,
    Sha256_64 = 5,
    Sha256_32 = 6,
    Sha384 = 7,
    Sha512 = 8,
    Sha3_224 = 9,
    Sha3_256 = 10,
    Sha3_384 = 11,
    Sha3_512 = 12,
}

public extern objc class MTROTAHeader : NSObject
{
    [Selector("vendorID", "setVendorID:")]
    public NSNumber VendorID { get; set; }
    [Selector("productID", "setProductID:")]
    public NSNumber ProductID { get; set; }
    [Selector("payloadSize", "setPayloadSize:")]
    public NSNumber PayloadSize { get; set; }
    [Selector("softwareVersion", "setSoftwareVersion:")]
    public NSNumber SoftwareVersion { get; set; }
    [Selector("softwareVersionString", "setSoftwareVersionString:")]
    public NSString SoftwareVersionString { get; set; }
    [Selector("releaseNotesURL", "setReleaseNotesURL:")]
    public NSString? ReleaseNotesURL { get; set; }
    [Selector("imageDigest", "setImageDigest:")]
    public NSData ImageDigest { get; set; }
    [Selector("imageDigestType", "setImageDigestType:")]
    public MTROTAImageDigestType ImageDigestType { get; set; }
    [Selector("minApplicableVersion", "setMinApplicableVersion:")]
    public NSNumber? MinApplicableVersion { get; set; }
    [Selector("maxApplicableVersion", "setMaxApplicableVersion:")]
    public NSNumber? MaxApplicableVersion { get; set; }
    [Selector("initWithData:")]
    public Self InitWithData(NSData data);
}

/// Deprecated in macOS 13.3.
public extern objc class MTROTAHeaderParser : NSObject
{
    [Selector("headerFromData:error:")]
    public static MTROTAHeader? HeaderFromDataError(NSData data, out NSError? error);
}

#endif
