// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from AuthenticationServices.framework (ASPasskeyCredentialIdentity.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.AuthenticationServices;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "AuthenticationServices")

public extern objc class ASPasskeyCredentialIdentity : NSObject, NSCopying, NSSecureCoding, ASCredentialIdentity
{
    [Selector("relyingPartyIdentifier")]
    public NSString RelyingPartyIdentifier { get; }
    [Selector("userName")]
    public NSString UserName { get; }
    [Selector("credentialID")]
    public NSData CredentialID { get; }
    [Selector("userHandle")]
    public NSData UserHandle { get; }
    [Selector("recordIdentifier")]
    public NSString? RecordIdentifier { get; }
    [Selector("rank", "setRank:")]
    public NSInteger Rank { get; set; }
    [Selector("initWithRelyingPartyIdentifier:userName:credentialID:userHandle:recordIdentifier:")]
    public Self InitWithRelyingPartyIdentifierUserNameCredentialIDUserHandleRecordIdentifier(NSString relyingPartyIdentifier, NSString userName, NSData credentialID, NSData userHandle, NSString? recordIdentifier);
    [Selector("identityWithRelyingPartyIdentifier:userName:credentialID:userHandle:recordIdentifier:")]
    public static Self IdentityWithRelyingPartyIdentifierUserNameCredentialIDUserHandleRecordIdentifier(NSString relyingPartyIdentifier, NSString userName, NSData credentialID, NSData userHandle, NSString? recordIdentifier);
}

#endif
