// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from HealthKit.framework (HKCategorySample.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.HealthKit;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "HealthKit")

public extern objc class HKCategorySample : HKSample
{
    [Selector("categoryType")]
    public HKCategoryType CategoryType { get; }
    [Selector("value")]
    public NSInteger Value { get; }
    [Selector("categorySampleWithType:value:startDate:endDate:metadata:")]
    public static Self CategorySampleWithTypeValueStartDateEndDateMetadata(HKCategoryType type, NSInteger value, NSDate startDate, NSDate endDate, NSDictionary? metadata);
    [Selector("categorySampleWithType:value:startDate:endDate:")]
    public static Self CategorySampleWithTypeValueStartDateEndDate(HKCategoryType type, NSInteger value, NSDate startDate, NSDate endDate);
    [Selector("categorySampleWithType:value:startDate:endDate:device:metadata:")]
    public static Self CategorySampleWithTypeValueStartDateEndDateDeviceMetadata(HKCategoryType type, NSInteger value, NSDate startDate, NSDate endDate, HKDevice? device, NSDictionary? metadata);
}

public extern "C" NSString HKPredicateKeyPathCategoryValue;

#endif
