// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Metal.framework (MTL4Archive.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Metal;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Metal")

/// macOS 26.0 and later.
public objc interface MTL4Archive : NSObjectProtocol
{
    [Selector("label", "setLabel:")]
    NSString? Label { get; set; }
    [Selector("newComputePipelineStateWithDescriptor:error:")]
    MTLComputePipelineState? NewComputePipelineStateWithDescriptorError(MTL4ComputePipelineDescriptor descriptor, out NSError? error);
    [Selector("newComputePipelineStateWithDescriptor:dynamicLinkingDescriptor:error:")]
    MTLComputePipelineState? NewComputePipelineStateWithDescriptorDynamicLinkingDescriptorError(MTL4ComputePipelineDescriptor descriptor, MTL4PipelineStageDynamicLinkingDescriptor dynamicLinkingDescriptor, out NSError? error);
    [Selector("newRenderPipelineStateWithDescriptor:error:")]
    MTLRenderPipelineState? NewRenderPipelineStateWithDescriptorError(MTL4PipelineDescriptor descriptor, out NSError? error);
    [Selector("newRenderPipelineStateWithDescriptor:dynamicLinkingDescriptor:error:")]
    MTLRenderPipelineState? NewRenderPipelineStateWithDescriptorDynamicLinkingDescriptorError(MTL4PipelineDescriptor descriptor, MTL4RenderPipelineDynamicLinkingDescriptor dynamicLinkingDescriptor, out NSError? error);
    [Selector("newBinaryFunctionWithDescriptor:error:")]
    MTL4BinaryFunctionProtocol? NewBinaryFunctionWithDescriptorError(MTL4BinaryFunctionDescriptor descriptor, out NSError? error);
}

#endif
