// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Metal.framework (MTLCommandEncoder.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Metal;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Metal")

[Flags]
public enum MTLResourceUsage : ulong
{
    Read = 1,
    Write = 2,
    Sample = 4,
}

[Flags]
public enum MTLBarrierScope : ulong
{
    Buffers = 1,
    Textures = 2,
    RenderTargets = 4,
}

/// macOS 26.0 and later.
[Flags]
public enum MTLStages : ulong
{
    Vertex = 1,
    Fragment = 2,
    Tile = 4,
    Object = 8,
    Mesh = 16,
    ResourceState = 67108864,
    Dispatch = 134217728,
    Blit = 268435456,
    AccelerationStructure = 536870912,
    MachineLearning = 1073741824,
    All = 9223372036854775807u,
}

public objc interface MTLCommandEncoder : NSObjectProtocol
{
    [Selector("device")] MTLDevice Device { get; }
    [Selector("label", "setLabel:")] NSString? Label { get; set; }
    [Selector("endEncoding")] void EndEncoding();
    /// macOS 26.0 and later.
    [Selector("barrierAfterQueueStages:beforeStages:")] void BarrierAfterQueueStagesBeforeStages(MTLStages afterQueueStages, MTLStages beforeStages);
    [Selector("insertDebugSignpost:")] void InsertDebugSignpost(NSString string);
    [Selector("pushDebugGroup:")] void PushDebugGroup(NSString string);
    [Selector("popDebugGroup")] void PopDebugGroup();
}

#endif
