// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Metal.framework (MTLRenderPass.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Metal;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Metal")

public struct MTLClearColor
{
    public double red;
    public double green;
    public double blue;
    public double alpha;
}

public enum MTLLoadAction : ulong
{
    DontCare = 0,
    Load = 1,
    Clear = 2,
}

public enum MTLStoreAction : ulong
{
    DontCare = 0,
    Store = 1,
    MultisampleResolve = 2,
    StoreAndMultisampleResolve = 3,
    Unknown = 4,
    CustomSampleDepthStore = 5,
}

[Flags]
public enum MTLStoreActionOptions : ulong
{
    None = 0,
    CustomSamplePositions = 1,
}

/// macOS 26.0 and later.
public enum MTLVisibilityResultType : long
{
    Reset = 0,
    Accumulate = 1,
}

public extern objc class MTLRenderPassAttachmentDescriptor : NSObject, NSCopying
{
    [Selector("texture", "setTexture:")] public MTLTexture? Texture { get; set; }
    [Selector("level", "setLevel:")] public NSUInteger Level { get; set; }
    [Selector("slice", "setSlice:")] public NSUInteger Slice { get; set; }
    [Selector("depthPlane", "setDepthPlane:")] public NSUInteger DepthPlane { get; set; }
    [Selector("resolveTexture", "setResolveTexture:")] public MTLTexture? ResolveTexture { get; set; }
    [Selector("resolveLevel", "setResolveLevel:")] public NSUInteger ResolveLevel { get; set; }
    [Selector("resolveSlice", "setResolveSlice:")] public NSUInteger ResolveSlice { get; set; }
    [Selector("resolveDepthPlane", "setResolveDepthPlane:")] public NSUInteger ResolveDepthPlane { get; set; }
    [Selector("loadAction", "setLoadAction:")] public MTLLoadAction LoadAction { get; set; }
    [Selector("storeAction", "setStoreAction:")] public MTLStoreAction StoreAction { get; set; }
    [Selector("storeActionOptions", "setStoreActionOptions:")] public MTLStoreActionOptions StoreActionOptions { get; set; }
}

public extern objc class MTLRenderPassColorAttachmentDescriptor : MTLRenderPassAttachmentDescriptor
{
    [Selector("clearColor", "setClearColor:")] public MTLClearColor ClearColor { get; set; }
}

public enum MTLMultisampleDepthResolveFilter : ulong
{
    Sample0 = 0,
    Min = 1,
    Max = 2,
}

public extern objc class MTLRenderPassDepthAttachmentDescriptor : MTLRenderPassAttachmentDescriptor
{
    [Selector("clearDepth", "setClearDepth:")] public double ClearDepth { get; set; }
    [Selector("depthResolveFilter", "setDepthResolveFilter:")] public MTLMultisampleDepthResolveFilter DepthResolveFilter { get; set; }
}

public enum MTLMultisampleStencilResolveFilter : ulong
{
    Sample0 = 0,
    DepthResolvedSample = 1,
}

public extern objc class MTLRenderPassStencilAttachmentDescriptor : MTLRenderPassAttachmentDescriptor
{
    [Selector("clearStencil", "setClearStencil:")] public uint ClearStencil { get; set; }
    [Selector("stencilResolveFilter", "setStencilResolveFilter:")] public MTLMultisampleStencilResolveFilter StencilResolveFilter { get; set; }
}

public extern objc class MTLRenderPassColorAttachmentDescriptorArray : NSObject
{
    [Selector("objectAtIndexedSubscript:")] public MTLRenderPassColorAttachmentDescriptor ObjectAtIndexedSubscript(NSUInteger attachmentIndex);
    [Selector("setObject:atIndexedSubscript:")] public void SetObjectAtIndexedSubscript(MTLRenderPassColorAttachmentDescriptor? attachment, NSUInteger attachmentIndex);
}

public extern objc class MTLRenderPassSampleBufferAttachmentDescriptor : NSObject, NSCopying
{
    [Selector("sampleBuffer", "setSampleBuffer:")] public MTLCounterSampleBuffer? SampleBuffer { get; set; }
    [Selector("startOfVertexSampleIndex", "setStartOfVertexSampleIndex:")] public NSUInteger StartOfVertexSampleIndex { get; set; }
    [Selector("endOfVertexSampleIndex", "setEndOfVertexSampleIndex:")] public NSUInteger EndOfVertexSampleIndex { get; set; }
    [Selector("startOfFragmentSampleIndex", "setStartOfFragmentSampleIndex:")] public NSUInteger StartOfFragmentSampleIndex { get; set; }
    [Selector("endOfFragmentSampleIndex", "setEndOfFragmentSampleIndex:")] public NSUInteger EndOfFragmentSampleIndex { get; set; }
}

public extern objc class MTLRenderPassSampleBufferAttachmentDescriptorArray : NSObject
{
    [Selector("objectAtIndexedSubscript:")] public MTLRenderPassSampleBufferAttachmentDescriptor ObjectAtIndexedSubscript(NSUInteger attachmentIndex);
    [Selector("setObject:atIndexedSubscript:")] public void SetObjectAtIndexedSubscript(MTLRenderPassSampleBufferAttachmentDescriptor? attachment, NSUInteger attachmentIndex);
}

public extern objc class MTLRenderPassDescriptor : NSObject, NSCopying
{
    [Selector("colorAttachments")] public MTLRenderPassColorAttachmentDescriptorArray ColorAttachments { get; }
    [Selector("depthAttachment", "setDepthAttachment:")] public MTLRenderPassDepthAttachmentDescriptor? DepthAttachment { get; set; }
    [Selector("stencilAttachment", "setStencilAttachment:")] public MTLRenderPassStencilAttachmentDescriptor? StencilAttachment { get; set; }
    [Selector("visibilityResultBuffer", "setVisibilityResultBuffer:")] public MTLBuffer? VisibilityResultBuffer { get; set; }
    [Selector("renderTargetArrayLength", "setRenderTargetArrayLength:")] public NSUInteger RenderTargetArrayLength { get; set; }
    [Selector("imageblockSampleLength", "setImageblockSampleLength:")] public NSUInteger ImageblockSampleLength { get; set; }
    [Selector("threadgroupMemoryLength", "setThreadgroupMemoryLength:")] public NSUInteger ThreadgroupMemoryLength { get; set; }
    [Selector("tileWidth", "setTileWidth:")] public NSUInteger TileWidth { get; set; }
    [Selector("tileHeight", "setTileHeight:")] public NSUInteger TileHeight { get; set; }
    [Selector("defaultRasterSampleCount", "setDefaultRasterSampleCount:")] public NSUInteger DefaultRasterSampleCount { get; set; }
    [Selector("renderTargetWidth", "setRenderTargetWidth:")] public NSUInteger RenderTargetWidth { get; set; }
    [Selector("renderTargetHeight", "setRenderTargetHeight:")] public NSUInteger RenderTargetHeight { get; set; }
    [Selector("rasterizationRateMap", "setRasterizationRateMap:")] public MTLRasterizationRateMap? RasterizationRateMap { get; set; }
    [Selector("sampleBufferAttachments")] public MTLRenderPassSampleBufferAttachmentDescriptorArray SampleBufferAttachments { get; }
    /// macOS 26.0 and later.
    [Selector("visibilityResultType", "setVisibilityResultType:")] public MTLVisibilityResultType VisibilityResultType { get; set; }
    /// macOS 26.0 and later.
    [Selector("supportColorAttachmentMapping", "setSupportColorAttachmentMapping:")] public bool SupportColorAttachmentMapping { get; set; }
    [Selector("renderPassDescriptor")] public static MTLRenderPassDescriptor RenderPassDescriptor();
    [Selector("setSamplePositions:count:")] public void SetSamplePositionsCount(MTLSamplePosition* positions, NSUInteger count);
    [Selector("getSamplePositions:count:")] public NSUInteger GetSamplePositionsCount(MTLSamplePosition* positions, NSUInteger count);
}

#endif
