// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Metal.framework (MTLResource.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Metal;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Metal")

public enum MTLPurgeableState : ulong
{
    KeepCurrent = 1,
    NonVolatile = 2,
    Volatile = 3,
    Empty = 4,
}

public enum MTLCPUCacheMode : ulong
{
    DefaultCache = 0,
    WriteCombined = 1,
}

public enum MTLStorageMode : ulong
{
    Shared = 0,
    Managed = 1,
    Private = 2,
    Memoryless = 3,
}

public enum MTLHazardTrackingMode : ulong
{
    Default = 0,
    Untracked = 1,
    Tracked = 2,
}

[Flags]
public enum MTLResourceOptions : ulong
{
    CPUCacheModeDefaultCache = 0,
    CPUCacheModeWriteCombined = 1,
    StorageModeShared = 0,
    StorageModeManaged = 16,
    StorageModePrivate = 32,
    StorageModeMemoryless = 48,
    HazardTrackingModeDefault = 0,
    HazardTrackingModeUntracked = 256,
    HazardTrackingModeTracked = 512,
    OptionCPUCacheModeDefault = 0,
    OptionCPUCacheModeWriteCombined = 1,
}

public enum MTLSparsePageSize : long
{
    Size16 = 101,
    Size64 = 102,
    Size256 = 103,
}

/// macOS 26.0 and later.
public enum MTLBufferSparseTier : long
{
    MTLBufferSparseTierNone = 0,
    MTLBufferSparseTier1 = 1,
}

/// macOS 26.0 and later.
public enum MTLTextureSparseTier : long
{
    MTLTextureSparseTierNone = 0,
    MTLTextureSparseTier1 = 1,
    MTLTextureSparseTier2 = 2,
}

public objc interface MTLResource : MTLAllocation
{
    [Selector("label", "setLabel:")] NSString? Label { get; set; }
    [Selector("device")] MTLDevice Device { get; }
    [Selector("cpuCacheMode")] MTLCPUCacheMode CpuCacheMode { get; }
    [Selector("storageMode")] MTLStorageMode StorageMode { get; }
    [Selector("hazardTrackingMode")] MTLHazardTrackingMode HazardTrackingMode { get; }
    [Selector("resourceOptions")] MTLResourceOptions ResourceOptions { get; }
    [Selector("heap")] MTLHeap? Heap { get; }
    [Selector("heapOffset")] NSUInteger HeapOffset { get; }
    [Selector("allocatedSize")] NSUInteger AllocatedSize { get; }
    [Selector("setPurgeableState:")] MTLPurgeableState SetPurgeableState(MTLPurgeableState state);
    [Selector("makeAliasable")] void MakeAliasable();
    [Selector("isAliasable")] bool IsAliasable();
    [Selector("setOwnerWithIdentity:")] kern_return_t SetOwnerWithIdentity(task_id_token_t task_id_token);
}

public const int MTLResourceCPUCacheModeShift = 0;

public const ulong MTLResourceCPUCacheModeMask = 15;

public const int MTLResourceStorageModeShift = 4;

public const ulong MTLResourceStorageModeMask = 240;

public const int MTLResourceHazardTrackingModeShift = 8;

public const ulong MTLResourceHazardTrackingModeMask = 768;

#endif
