// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Intents.framework (INIntentErrors.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Intents;

import MacOS.Foundation;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Intents")

public extern "C" NSString? INIntentErrorDomain;

public enum INIntentErrorCode : long
{
    InteractionOperationNotSupported = 1900,
    DonatingInteraction = 1901,
    DeletingAllInteractions = 1902,
    DeletingInteractionWithIdentifiers = 1903,
    DeletingInteractionWithGroupIdentifier = 1904,
    IntentSupportedByMultipleExtension = 2001,
    RestrictedIntentsNotSupportedByExtension = 2002,
    NoHandlerProvidedForIntent = 2003,
    InvalidIntentName = 2004,
    NoAppAvailable = 2005,
    RequestTimedOut = 3001,
    MissingInformation = 3002,
    InvalidUserVocabularyFileLocation = 4000,
    ExtensionLaunchingTimeout = 5000,
    ExtensionBringUpFailed = 5001,
    ImageGeneric = 6000,
    ImageNoServiceAvailable = 6001,
    ImageStorageFailed = 6002,
    ImageLoadingFailed = 6003,
    ImageRetrievalFailed = 6004,
    ImageProxyLoop = 6005,
    ImageProxyInvalid = 6006,
    ImageProxyTimeout = 6007,
    ImageServiceFailure = 6008,
    ImageScalingFailed = 6009,
    PermissionDenied = 6010,
    VoiceShortcutCreationFailed = 7000,
    VoiceShortcutGetFailed = 7001,
    VoiceShortcutDeleteFailed = 7002,
    EncodingGeneric = 8000,
    EncodingFailed = 8001,
    DecodingGeneric = 9000,
    UnableToCreateAppIntentRepresentation = 10000,
    NoAppIntent = 10001,
}

#endif
