// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Intents.framework (INSendMessageIntent.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Intents;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Intents")

public extern objc class INSendMessageIntent : INIntent
{
    [Selector("recipients")]
    public NSArray? Recipients { get; }
    [Selector("outgoingMessageType")]
    public INOutgoingMessageType OutgoingMessageType { get; }
    [Selector("content")]
    public NSString? Content { get; }
    [Selector("speakableGroupName")]
    public INSpeakableString? SpeakableGroupName { get; }
    [Selector("conversationIdentifier")]
    public NSString? ConversationIdentifier { get; }
    [Selector("serviceName")]
    public NSString? ServiceName { get; }
    [Selector("sender")]
    public INPerson? Sender { get; }
    [Selector("attachments")]
    public NSArray? Attachments { get; }
    [Selector("initWithRecipients:outgoingMessageType:content:speakableGroupName:conversationIdentifier:serviceName:sender:attachments:")]
    public Self InitWithRecipientsOutgoingMessageTypeContentSpeakableGroupNameConversationIdentifierServiceNameSenderAttachments(NSArray? recipients, INOutgoingMessageType outgoingMessageType, NSString? content, INSpeakableString? speakableGroupName, NSString? conversationIdentifier, NSString? serviceName, INPerson? sender, NSArray? attachments);
}

public objc closure void INSendMessageIntentHandlingHandleSendMessageCompletionCompletionBlock(INSendMessageIntentResponse arg0);

public objc closure void INSendMessageIntentHandlingConfirmSendMessageCompletionCompletionBlock(INSendMessageIntentResponse arg0);

public objc closure void INSendMessageIntentHandlingResolveRecipientsForSendMessageWithCompletionCompletionBlock(NSArray arg0);

public objc closure void INSendMessageIntentHandlingResolveRecipientsForSendMessageCompletionCompletionBlock(NSArray arg0);

public objc closure void INSendMessageIntentHandlingResolveGroupNameForSendMessageWithCompletionCompletionBlock(INStringResolutionResult arg0);

public objc closure void INSendMessageIntentHandlingResolveOutgoingMessageTypeForSendMessageWithCompletionCompletionBlock(INOutgoingMessageTypeResolutionResult arg0);

public objc closure void INSendMessageIntentHandlingResolveContentForSendMessageWithCompletionCompletionBlock(INStringResolutionResult arg0);

public objc interface INSendMessageIntentHandling : NSObjectProtocol
{
    [Selector("handleSendMessage:completion:")]
    void HandleSendMessageCompletion(INSendMessageIntent intent, INSendMessageIntentHandlingHandleSendMessageCompletionCompletionBlock completion);
    [Optional]
    [Selector("confirmSendMessage:completion:")]
    void ConfirmSendMessageCompletion(INSendMessageIntent intent, INSendMessageIntentHandlingConfirmSendMessageCompletionCompletionBlock completion);
    [Optional]
    [Selector("resolveRecipientsForSendMessage:withCompletion:")]
    void ResolveRecipientsForSendMessageWithCompletion(INSendMessageIntent intent, INSendMessageIntentHandlingResolveRecipientsForSendMessageWithCompletionCompletionBlock completion);
    [Optional]
    [Selector("resolveRecipientsForSendMessage:completion:")]
    void ResolveRecipientsForSendMessageCompletion(INSendMessageIntent intent, INSendMessageIntentHandlingResolveRecipientsForSendMessageCompletionCompletionBlock completion);
    /// Deprecated in macOS 12.0.
    [Optional]
    [Selector("resolveGroupNameForSendMessage:withCompletion:")]
    void ResolveGroupNameForSendMessageWithCompletion(INSendMessageIntent intent, INSendMessageIntentHandlingResolveGroupNameForSendMessageWithCompletionCompletionBlock completion);
    [Optional]
    [Selector("resolveOutgoingMessageTypeForSendMessage:withCompletion:")]
    void ResolveOutgoingMessageTypeForSendMessageWithCompletion(INSendMessageIntent intent, INSendMessageIntentHandlingResolveOutgoingMessageTypeForSendMessageWithCompletionCompletionBlock completion);
    [Optional]
    [Selector("resolveContentForSendMessage:withCompletion:")]
    void ResolveContentForSendMessageWithCompletion(INSendMessageIntent intent, INSendMessageIntentHandlingResolveContentForSendMessageWithCompletionCompletionBlock completion);
}

#endif
