// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from GameplayKit.framework (GKBehavior.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.GameplayKit;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "GameplayKit")

public extern objc class GKBehavior : NSObject, NSFastEnumeration, NSCopying
{
    [Selector("goalCount")] public NSInteger GoalCount { get; }
    [Selector("behaviorWithGoal:weight:")] public static Self BehaviorWithGoalWeight(GKGoal goal, float weight);
    [Selector("behaviorWithGoals:")] public static Self BehaviorWithGoals(NSArray goals);
    [Selector("behaviorWithGoals:andWeights:")] public static Self BehaviorWithGoalsAndWeights(NSArray goals, NSArray weights);
    [Selector("behaviorWithWeightedGoals:")] public static Self BehaviorWithWeightedGoals(NSDictionary weightedGoals);
    [Selector("setWeight:forGoal:")] public void SetWeightForGoal(float weight, GKGoal goal);
    [Selector("weightForGoal:")] public float WeightForGoal(GKGoal goal);
    [Selector("removeGoal:")] public void RemoveGoal(GKGoal goal);
    [Selector("removeAllGoals")] public void RemoveAllGoals();
    [Selector("objectAtIndexedSubscript:")] public GKGoal ObjectAtIndexedSubscript(NSUInteger idx);
    [Selector("setObject:forKeyedSubscript:")] public void SetObjectForKeyedSubscript(NSNumber weight, GKGoal goal);
    [Selector("objectForKeyedSubscript:")] public NSNumber? ObjectForKeyedSubscript(GKGoal goal);
}

#endif
