// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from IOKit.framework (IOLLEvent.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.IOKit;

import MacOS.System;

#if MACOS

#pragma comment(framework, "IOKit")

public using NXCoord = float;

public struct _NXPoint
{
    public NXCoord x;
    public NXCoord y;
}

public using NXPoint = _NXPoint;

public struct _NXSize
{
    public NXCoord width;
    public NXCoord height;
}

public using NXSize = _NXSize;

public struct _NXTabletPointDataTilt
{
    public SInt16 x;
    public SInt16 y;
}

public struct _NXTabletPointData
{
    public SInt32 x;
    public SInt32 y;
    public SInt32 z;
    public UInt16 buttons;
    public UInt16 pressure;
    public _NXTabletPointDataTilt tilt;
    public UInt16 rotation;
    public SInt16 tangentialPressure;
    public UInt16 deviceID;
    public SInt16 vendor1;
    public SInt16 vendor2;
    public SInt16 vendor3;
}

public using NXTabletPointData = _NXTabletPointData;

public using NXTabletPointDataPtr = _NXTabletPointData*;

public struct _NXTabletProximityData
{
    public UInt16 vendorID;
    public UInt16 tabletID;
    public UInt16 pointerID;
    public UInt16 deviceID;
    public UInt16 systemTabletID;
    public UInt16 vendorPointerType;
    public UInt32 pointerSerialNumber;
    [Packed] public UInt64 uniqueID;
    public UInt32 capabilityMask;
    public UInt8 pointerType;
    public UInt8 enterProximity;
    public SInt16 reserved1;
}

public using NXTabletProximityData = _NXTabletProximityData;

public using NXTabletProximityDataPtr = _NXTabletProximityData*;

public union NXEventDataMouseTablet
{
    public NXTabletPointData point;
    public NXTabletProximityData proximity;
}

public struct NXEventDataMouse
{
    public UInt8 subx;
    public UInt8 suby;
    public SInt16 eventNum;
    public SInt32 click;
    public UInt8 pressure;
    public UInt8 buttonNumber;
    public UInt8 subType;
    public UInt8 reserved2;
    public SInt32 reserved3;
    public NXEventDataMouseTablet tablet;
}

public union NXEventDataMouseMoveTablet
{
    public NXTabletPointData point;
    public NXTabletProximityData proximity;
}

public struct NXEventDataMouseMove
{
    public SInt32 dx;
    public SInt32 dy;
    public UInt8 subx;
    public UInt8 suby;
    public UInt8 subType;
    public UInt8 reserved1;
    public SInt32 reserved2;
    public NXEventDataMouseMoveTablet tablet;
}

public struct NXEventDataKey
{
    public UInt16 origCharSet;
    public SInt16 repeat;
    public UInt16 charSet;
    public UInt16 charCode;
    public UInt16 keyCode;
    public UInt16 origCharCode;
    public SInt32 reserved1;
    public UInt32 keyboardType;
    public SInt32 reserved2;
    public SInt32 reserved3;
    public SInt32 reserved4;
    public SInt32[4] reserved5;
}

public struct NXEventDataTracking
{
    public SInt16 reserved;
    public SInt16 eventNum;
    public SInt32 trackingNum;
    public SInt32 userData;
    public SInt32 reserved1;
    public SInt32 reserved2;
    public SInt32 reserved3;
    public SInt32 reserved4;
    public SInt32 reserved5;
    public SInt32[4] reserved6;
}

public struct NXEventDataScrollWheel
{
    public SInt16 deltaAxis1;
    public SInt16 deltaAxis2;
    public SInt16 deltaAxis3;
    public SInt16 reserved1;
    public SInt32 fixedDeltaAxis1;
    public SInt32 fixedDeltaAxis2;
    public SInt32 fixedDeltaAxis3;
    public SInt32 pointDeltaAxis1;
    public SInt32 pointDeltaAxis2;
    public SInt32 pointDeltaAxis3;
    public SInt32[4] reserved8;
}

public struct NXEventDataZoom
{
    public SInt16 deltaAxis1;
    public SInt16 deltaAxis2;
    public SInt16 deltaAxis3;
    public SInt16 reserved1;
    public SInt32 fixedDeltaAxis1;
    public SInt32 fixedDeltaAxis2;
    public SInt32 fixedDeltaAxis3;
    public SInt32 pointDeltaAxis1;
    public SInt32 pointDeltaAxis2;
    public SInt32 pointDeltaAxis3;
    public SInt32[4] reserved8;
}

public union NXEventDataCompoundMisc
{
    public float[11] F;
    public SInt32[11] L;
    public SInt16[22] S;
    public byte[44] C;
}

public struct NXEventDataCompound
{
    public SInt16 reserved;
    public SInt16 subType;
    public NXEventDataCompoundMisc misc;
}

public struct NXEventDataTabletTilt
{
    public SInt16 x;
    public SInt16 y;
}

public struct NXEventDataTablet
{
    public SInt32 x;
    public SInt32 y;
    public SInt32 z;
    public UInt16 buttons;
    public UInt16 pressure;
    public NXEventDataTabletTilt tilt;
    public UInt16 rotation;
    public SInt16 tangentialPressure;
    public UInt16 deviceID;
    public SInt16 vendor1;
    public SInt16 vendor2;
    public SInt16 vendor3;
    public SInt32[4] reserved;
}

public struct NXEventDataProximity
{
    public UInt16 vendorID;
    public UInt16 tabletID;
    public UInt16 pointerID;
    public UInt16 deviceID;
    public UInt16 systemTabletID;
    public UInt16 vendorPointerType;
    public UInt32 pointerSerialNumber;
    [Packed] public UInt64 uniqueID;
    public UInt32 capabilityMask;
    public UInt8 pointerType;
    public UInt8 enterProximity;
    public SInt16 reserved1;
    public SInt32[4] reserved2;
}

public union NXEventData
{
    public NXEventDataMouse mouse;
    public NXEventDataMouseMove mouseMove;
    public NXEventDataKey key;
    public NXEventDataTracking tracking;
    public NXEventDataScrollWheel scrollWheel;
    public NXEventDataZoom zoom;
    public NXEventDataCompound compound;
    public NXEventDataTablet tablet;
    public NXEventDataProximity proximity;
}

public struct _NXEventLocation
{
    public SInt32 x;
    public SInt32 y;
}

public struct _NXEvent
{
    public SInt32 type;
    public _NXEventLocation location;
    [Packed] public UInt64 time;
    public SInt32 flags;
    public UInt32 window;
    [Packed] public UInt64 service_id;
    public SInt32 ext_pid;
    public NXEventData data;
}

public using NXEvent = _NXEvent;

public using NXEventPtr = _NXEvent*;

public struct _NXEventExtension
{
    public UInt32 flags;
    public audit_token_t audit;
}

public using NXEventExtension = _NXEventExtension;

public struct _NXEventExt
{
    public NXEvent payload;
    public NXEventExtension extension;
}

public using NXEventExt = _NXEventExt;

#endif
