// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from PhotosUI.framework (PHProjectTypeDescription.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.PhotosUI;

import MacOS.AppKit;
import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "PhotosUI")

public extern objc class PHProjectTypeDescription : NSObject, NSSecureCoding
{
    [Selector("projectType")] public PHProjectType ProjectType { get; }
    [Selector("localizedTitle")] public NSString LocalizedTitle { get; }
    [Selector("localizedDescription")] public NSString? LocalizedDescription { get; }
    [Selector("localizedAttributedDescription")] public NSAttributedString? LocalizedAttributedDescription { get; }
    [Selector("image")] public NSImage? Image { get; }
    [Selector("subtypeDescriptions")] public NSArray SubtypeDescriptions { get; }
    [Selector("canProvideSubtypes")] public bool CanProvideSubtypes { get; }
    [Selector("initWithProjectType:title:description:image:subtypeDescriptions:")] public Self InitWithProjectTypeTitleDescriptionImageSubtypeDescriptions(PHProjectType projectType, NSString localizedTitle, NSString? localizedDescription, NSImage? image, NSArray subtypeDescriptions);
    [Selector("initWithProjectType:title:attributedDescription:image:subtypeDescriptions:")] public Self InitWithProjectTypeTitleAttributedDescriptionImageSubtypeDescriptions(PHProjectType projectType, NSString localizedTitle, NSAttributedString? localizedAttributedDescription, NSImage? image, NSArray subtypeDescriptions);
    [Selector("initWithProjectType:title:description:image:")] public Self InitWithProjectTypeTitleDescriptionImage(PHProjectType projectType, NSString localizedTitle, NSString? localizedDescription, NSImage? image);
    [Selector("initWithProjectType:title:description:image:canProvideSubtypes:")] public Self InitWithProjectTypeTitleDescriptionImageCanProvideSubtypes(PHProjectType projectType, NSString localizedTitle, NSString? localizedDescription, NSImage? image, bool canProvideSubtypes);
    [Selector("initWithProjectType:title:attributedDescription:image:canProvideSubtypes:")] public Self InitWithProjectTypeTitleAttributedDescriptionImageCanProvideSubtypes(PHProjectType projectType, NSString localizedTitle, NSAttributedString? localizedAttributedDescription, NSImage? image, bool canProvideSubtypes);
}

#endif
