// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from Virtualization.framework (VZVirtualMachine.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.Virtualization;

import MacOS.Foundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "Virtualization")

public enum VZVirtualMachineState : long
{
    Stopped = 0,
    Running = 1,
    Paused = 2,
    Error = 3,
    Starting = 4,
    Pausing = 5,
    Resuming = 6,
    Stopping = 7,
    Saving = 8,
    Restoring = 9,
}

#if ARM64
public objc closure void VZVirtualMachineStartWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachineStartWithOptionsCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachineStopWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachinePauseWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachineResumeWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachineRestoreMachineStateFromURLCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachineSaveMachineStateToURLCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public extern objc class VZVirtualMachine : NSObject
{
    /// macOS 26.0 and later.
    [Selector("queue")]
    public dispatch_queue_t? Queue { get; }
    [Selector("isSupported")]
    public static bool Supported { get; }
    [Selector("state")]
    public VZVirtualMachineState State { get; }
    [Selector("delegate", "setDelegate:")]
    public VZVirtualMachineDelegate? Delegate { get; set; }
    [Selector("canStart")]
    public bool CanStart { get; }
    [Selector("canStop")]
    public bool CanStop { get; }
    [Selector("canPause")]
    public bool CanPause { get; }
    [Selector("canResume")]
    public bool CanResume { get; }
    [Selector("canRequestStop")]
    public bool CanRequestStop { get; }
    [Selector("consoleDevices")]
    public NSArray? ConsoleDevices { get; }
    [Selector("directorySharingDevices")]
    public NSArray? DirectorySharingDevices { get; }
    [Selector("graphicsDevices")]
    public NSArray? GraphicsDevices { get; }
    [Selector("memoryBalloonDevices")]
    public NSArray MemoryBalloonDevices { get; }
    [Selector("networkDevices")]
    public NSArray? NetworkDevices { get; }
    [Selector("socketDevices")]
    public NSArray SocketDevices { get; }
    [Selector("usbControllers")]
    public NSArray? UsbControllers { get; }
    [Selector("initWithConfiguration:")]
    public Self InitWithConfiguration(VZVirtualMachineConfiguration configuration);
    [Selector("initWithConfiguration:queue:")]
    public Self InitWithConfigurationQueue(VZVirtualMachineConfiguration configuration, dispatch_queue_t queue);
    [Selector("startWithCompletionHandler:")]
    public void StartWithCompletionHandler(VZVirtualMachineStartWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("startWithOptions:completionHandler:")]
    public void StartWithOptionsCompletionHandler(VZVirtualMachineStartOptions options, VZVirtualMachineStartWithOptionsCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("stopWithCompletionHandler:")]
    public void StopWithCompletionHandler(VZVirtualMachineStopWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("pauseWithCompletionHandler:")]
    public void PauseWithCompletionHandler(VZVirtualMachinePauseWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("resumeWithCompletionHandler:")]
    public void ResumeWithCompletionHandler(VZVirtualMachineResumeWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("restoreMachineStateFromURL:completionHandler:")]
    public void RestoreMachineStateFromURLCompletionHandler(NSURL saveFileURL, VZVirtualMachineRestoreMachineStateFromURLCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("saveMachineStateToURL:completionHandler:")]
    public void SaveMachineStateToURLCompletionHandler(NSURL saveFileURL, VZVirtualMachineSaveMachineStateToURLCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("requestStopWithError:")]
    public bool RequestStopWithError(out NSError? error);
}
#else
public objc closure void VZVirtualMachineStartWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachineStartWithOptionsCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachineStopWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachinePauseWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public objc closure void VZVirtualMachineResumeWithCompletionHandlerCompletionHandlerBlock(NSError? arg0);

public extern objc class VZVirtualMachine : NSObject
{
    /// macOS 26.0 and later.
    [Selector("queue")]
    public dispatch_queue_t? Queue { get; }
    [Selector("isSupported")]
    public static bool Supported { get; }
    [Selector("state")]
    public VZVirtualMachineState State { get; }
    [Selector("delegate", "setDelegate:")]
    public VZVirtualMachineDelegate? Delegate { get; set; }
    [Selector("canStart")]
    public bool CanStart { get; }
    [Selector("canStop")]
    public bool CanStop { get; }
    [Selector("canPause")]
    public bool CanPause { get; }
    [Selector("canResume")]
    public bool CanResume { get; }
    [Selector("canRequestStop")]
    public bool CanRequestStop { get; }
    [Selector("consoleDevices")]
    public NSArray? ConsoleDevices { get; }
    [Selector("directorySharingDevices")]
    public NSArray? DirectorySharingDevices { get; }
    [Selector("graphicsDevices")]
    public NSArray? GraphicsDevices { get; }
    [Selector("memoryBalloonDevices")]
    public NSArray MemoryBalloonDevices { get; }
    [Selector("networkDevices")]
    public NSArray? NetworkDevices { get; }
    [Selector("socketDevices")]
    public NSArray SocketDevices { get; }
    [Selector("usbControllers")]
    public NSArray? UsbControllers { get; }
    [Selector("initWithConfiguration:")]
    public Self InitWithConfiguration(VZVirtualMachineConfiguration configuration);
    [Selector("initWithConfiguration:queue:")]
    public Self InitWithConfigurationQueue(VZVirtualMachineConfiguration configuration, dispatch_queue_t queue);
    [Selector("startWithCompletionHandler:")]
    public void StartWithCompletionHandler(VZVirtualMachineStartWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("startWithOptions:completionHandler:")]
    public void StartWithOptionsCompletionHandler(VZVirtualMachineStartOptions options, VZVirtualMachineStartWithOptionsCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("stopWithCompletionHandler:")]
    public void StopWithCompletionHandler(VZVirtualMachineStopWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("pauseWithCompletionHandler:")]
    public void PauseWithCompletionHandler(VZVirtualMachinePauseWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("resumeWithCompletionHandler:")]
    public void ResumeWithCompletionHandler(VZVirtualMachineResumeWithCompletionHandlerCompletionHandlerBlock completionHandler);
    [Selector("requestStopWithError:")]
    public bool RequestStopWithError(out NSError? error);
}
#endif

#endif
