// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreGraphics.framework (CGDataProvider.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreGraphics;

import MacOS.CoreFoundation;
import MacOS.System;
import Standard.ObjC;

#if MACOS

#pragma comment(framework, "CoreGraphics")

public struct CGDataProvider;

[CFType("CGDataProviderGetTypeID")]
public extern objc class CGDataProviderRef : CFTypeRef { }

public delegate nuint CGDataProviderGetBytesCallback(void* arg0, void* arg1, nuint arg2);

public delegate off_t CGDataProviderSkipForwardCallback(void* arg0, off_t arg1);

public delegate void CGDataProviderRewindCallback(void* arg0);

public delegate void CGDataProviderReleaseInfoCallback(void* arg0);

public struct CGDataProviderSequentialCallbacks
{
    public uint version;
    public CGDataProviderGetBytesCallback getBytes;
    public CGDataProviderSkipForwardCallback skipForward;
    public CGDataProviderRewindCallback rewind;
    public CGDataProviderReleaseInfoCallback releaseInfo;
}

public delegate void* CGDataProviderGetBytePointerCallback(void* arg0);

public delegate void CGDataProviderReleaseBytePointerCallback(void* arg0, void* arg1);

public delegate nuint CGDataProviderGetBytesAtPositionCallback(void* arg0, void* arg1, off_t arg2, nuint arg3);

public struct CGDataProviderDirectCallbacks
{
    public uint version;
    public CGDataProviderGetBytePointerCallback getBytePointer;
    public CGDataProviderReleaseBytePointerCallback releaseBytePointer;
    public CGDataProviderGetBytesAtPositionCallback getBytesAtPosition;
    public CGDataProviderReleaseInfoCallback releaseInfo;
}

public extern "C" CFTypeID CGDataProviderGetTypeID();

[ReturnsRetained]
public extern "C" CGDataProviderRef? CGDataProviderCreateSequential(void* info, CGDataProviderSequentialCallbacks* callbacks);

[ReturnsRetained]
public extern "C" CGDataProviderRef? CGDataProviderCreateDirect(void* info, off_t size, CGDataProviderDirectCallbacks* callbacks);

public delegate void CGDataProviderReleaseDataCallback(void* arg0, void* arg1, nuint arg2);

[ReturnsRetained]
public extern "C" CGDataProviderRef? CGDataProviderCreateWithData(void* info, void* data, nuint size, CGDataProviderReleaseDataCallback releaseData);

[ReturnsRetained]
public extern "C" CGDataProviderRef? CGDataProviderCreateWithCFData(CFDataRef? data);

[ReturnsRetained]
public extern "C" CGDataProviderRef? CGDataProviderCreateWithURL(CFURLRef? url);

[ReturnsRetained]
public extern "C" CGDataProviderRef? CGDataProviderCreateWithFilename(byte* filename);

[ReturnsRetained]
public extern "C" CFDataRef? CGDataProviderCopyData(CGDataProviderRef? provider);

public extern "C" void* CGDataProviderGetInfo(CGDataProviderRef? provider);

#endif
