// Stainless - an experimental general-purpose language.
// Copyright (C) 2026 Brandon Scott
//
// This file is part of the Stainless runtime library. It is free
// software: you can redistribute it and/or modify it under the terms of
// the GNU General Public License as published by the Free Software
// Foundation, either version 3 of the License, or (at your option) any
// later version.
//
// It is distributed in the hope that it will be useful, but WITHOUT ANY
// WARRANTY; without even the implied warranty of MERCHANTABILITY or
// FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
// for more details.
//
// As an additional permission under section 7 of that License, compiling
// a program with Stainless does not by itself place that program under
// the GNU General Public License. See LICENSE.RUNTIME.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Generated by tools/Stainless.Bindgen from CoreGraphics.framework (CGPDFDocument.h).
// Do not edit; regenerate with tools/bindgen.sh.
module MacOS.CoreGraphics;

import MacOS.CoreFoundation;

#if MACOS

#pragma comment(framework, "CoreGraphics")

public struct CGPDFDocument;

public using CGPDFDocumentRef = CGPDFDocument*;

[Flags]
public enum CGPDFAccessPermissions : uint
{
    LowQualityPrinting = 1,
    HighQualityPrinting = 2,
    DocumentChanges = 4,
    DocumentAssembly = 8,
    ContentCopying = 16,
    ContentAccessibility = 32,
    Commenting = 64,
    FormFieldEntry = 128,
}

public extern "C" CFStringRef kCGPDFOutlineTitle;

public extern "C" CFStringRef kCGPDFOutlineChildren;

public extern "C" CFStringRef kCGPDFOutlineDestination;

public extern "C" CFStringRef kCGPDFOutlineDestinationRect;

public extern "C" CGPDFDocumentRef CGPDFDocumentCreateWithProvider(CGDataProviderRef provider);

public extern "C" CGPDFDocumentRef CGPDFDocumentCreateWithURL(CFURLRef url);

public extern "C" CGPDFDocumentRef CGPDFDocumentRetain(CGPDFDocumentRef document);

public extern "C" void CGPDFDocumentRelease(CGPDFDocumentRef document);

public extern "C" void CGPDFDocumentGetVersion(CGPDFDocumentRef document, int* majorVersion, int* minorVersion);

public extern "C" bool CGPDFDocumentIsEncrypted(CGPDFDocumentRef document);

public extern "C" bool CGPDFDocumentUnlockWithPassword(CGPDFDocumentRef document, byte* password);

public extern "C" bool CGPDFDocumentIsUnlocked(CGPDFDocumentRef document);

public extern "C" bool CGPDFDocumentAllowsPrinting(CGPDFDocumentRef document);

public extern "C" bool CGPDFDocumentAllowsCopying(CGPDFDocumentRef document);

public extern "C" nuint CGPDFDocumentGetNumberOfPages(CGPDFDocumentRef document);

public extern "C" CGPDFPageRef CGPDFDocumentGetPage(CGPDFDocumentRef document, nuint pageNumber);

public extern "C" CGPDFDictionaryRef CGPDFDocumentGetCatalog(CGPDFDocumentRef document);

public extern "C" CGPDFDictionaryRef CGPDFDocumentGetInfo(CGPDFDocumentRef document);

public extern "C" CGPDFArrayRef CGPDFDocumentGetID(CGPDFDocumentRef document);

public extern "C" CFTypeID CGPDFDocumentGetTypeID();

public extern "C" CFDictionaryRef CGPDFDocumentGetOutline(CGPDFDocumentRef document);

public extern "C" CGPDFAccessPermissions CGPDFDocumentGetAccessPermissions(CGPDFDocumentRef document);

/// Deprecated in macOS 10.5.
public extern "C" CGRect CGPDFDocumentGetMediaBox(CGPDFDocumentRef document, int page);

/// Deprecated in macOS 10.5.
public extern "C" CGRect CGPDFDocumentGetCropBox(CGPDFDocumentRef document, int page);

/// Deprecated in macOS 10.5.
public extern "C" CGRect CGPDFDocumentGetBleedBox(CGPDFDocumentRef document, int page);

/// Deprecated in macOS 10.5.
public extern "C" CGRect CGPDFDocumentGetTrimBox(CGPDFDocumentRef document, int page);

/// Deprecated in macOS 10.5.
public extern "C" CGRect CGPDFDocumentGetArtBox(CGPDFDocumentRef document, int page);

/// Deprecated in macOS 10.5.
public extern "C" int CGPDFDocumentGetRotationAngle(CGPDFDocumentRef document, int page);

#endif
